### ISSUE TITLE
PGroonga 2.1.4 build failed

### ISSUE THREAD

**Issue by okadamasashi-ta** [pgroonga/pgroonga#103]
下記の環境にてpgroongaのソースインストールを試みていますが、makeコマンドでエラーが出ます

Verified environments:
・CentOS 7.6.1810
・PostgreSQL 9.6.13
・PGronga 2.1.4(http://packages.groonga.org/source/pgroonga/pgroonga-2.1.4.tar.gz)
・Groonga groonga-release-1.3.0-1(http://packages.groonga.org/centos/groonga-release-1.3.0-1.noarch.rpm)

Steps to build:

　# export POSTGRES_HOME=/usr/local/pgsql5433
　# export PGDATA=$POSTGRES_HOME/data
　# rpm -ivh http://packages.groonga.org/centos/groonga-release-1.3.0-1.noarch.rpm
　# yum --enablerepo=epel install groonga-devel
　# wget http://packages.groonga.org/source/pgroonga/pgroonga-2.1.4.tar.gz
　# tar xvf pgroonga-2.1.4.tar.gz
　# cd pgroonga-2.1.4
　# make clean
　# make

Log:

make -f pgroonga.mk all
make[1]: ディレクトリ `/usr/local/src/pgroonga-2.1.4' に入ります
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -Ivendor/xxHash -DPGRN_VERSION="\"2.1.4\"" -fPIC -I/usr/include/groonga   -I. -I./ -I/usr/local/pgsql5433/include/server -I/usr/local/pgsql5433/include/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o src/pgroonga.o src/pgroonga.c
src/pgroonga.c:75:6: エラー: ‘PGrnGroongaInitialized’ と型が競合しています
 bool PGrnGroongaInitialized = false;
 
In file included from src/pgroonga.c:1:0:
src/pgroonga.h:94:13: 備考: 前の ‘PGrnGroongaInitialized’ の宣言はここです
 extern bool PGrnGroongaInitialized;
             ^
src/pgroonga.c:6893:1: エラー: ‘PGrnIndexIsPGroonga’ と型が競合しています
 PGrnIndexIsPGroonga(Relation index)

In file included from src/pgroonga.c:1:0:
src/pgroonga.h:96:6: 備考: 前の ‘PGrnIndexIsPGroonga’ の宣言はここです
 bool PGrnIndexIsPGroonga(Relation index);
  
make[1]: *** [src/pgroonga.o] エラー 1
make[1]: ディレクトリ `/usr/local/src/pgroonga-2.1.4' から出ます
make: *** [all] エラー 2

**Comment by kou** [comment]
最新のPGroonga（2.2.0）を使ってもらえますか？

**Comment by okadamasashi-ta** [comment]
PGroonga（2.2.0）で問題なくコンパイルができました。ありがとうございました。
