### ISSUE TITLE
[Doc Improvement] Clarify `&@~ 'KEYWORD1 KEYWORD2'` is actually a AND search

### ISSUE THREAD

**Issue by sgon00** [pgroonga/pgroonga#104]
Hi, after I read https://pgroonga.github.io/tutorial/ and https://pgroonga.github.io/reference/operators/query-v2.html, there is no explicit explanation of what `&@~ 'KEYWORD1 KEYWORD2'` does. In the beginning, I thought it was a shorthand of `&@~ 'KEYWORD1 OR KEYWORD2'`, but I was wrong, It's actually a AND search instead of OR. I hope the documentation can clarify this so other new comers will not be confused like me at the beginning.

**Comment by komainu8** [comment]
Thank you for your report.
I will update this in a few weeks.

**Comment by kenhys** [comment]
@sgon00 I've fixed via https://github.com/pgroonga/pgroonga.github.io/commit/c48e591f7e1ab87af2cc82bc6bd2c9a66a168102
Thanks you!
