### ISSUE TITLE
[question] chinese pinyin search

### ISSUE THREAD

**Issue by DeoLeung** [pgroonga/pgroonga#107]
Hi , 

a question about searching Chinese, is there any built in support using romanian pinyin to search chinese, similar to katakana in Japanese?

like `ceshi` or `cs` to search `测试`?

**Comment by kou** [comment]
How about implementing auto complete feature and then search by completed query?
https://pgroonga.github.io/how-to/auto-complete.html

**Comment by kou** [comment]
```sql
CREATE TABLE terms (
  term text,
  readings text[]
);

CREATE INDEX pgroonga_terms_prefix_search ON terms USING pgroonga
  (term pgroonga_text_term_search_ops_v2,
   readings pgroonga_text_array_term_search_ops_v2);

CREATE INDEX pgroonga_terms_full_text_search ON terms USING pgroonga
  (term)
  WITH (tokenizer = 'TokenBigramSplitSymbolAlphaDigit');

INSERT INTO terms (term, readings) VALUES ('测试', ARRAY['ceshi', 'cs']);
```

You should use `&^` instead of `&^~`:

```sql
SELECT term
  FROM terms
 WHERE term &^ 'ceshi' OR
       readings &^ 'ceshi' OR
       term &@ 'ceshi'
 ORDER BY term;
--  term 
-- ------
--  测试
SELECT term
  FROM terms
 WHERE term &^ 'ce' OR
       readings &^ 'ce' OR
       term &@ 'ce'
 ORDER BY term;
--  term 
-- ------
--  测试
SELECT term
  FROM terms
 WHERE term &^ 'cs' OR
       readings &^ 'cs' OR
       term &@ 'cs'
 ORDER BY term;
--  term 
-- ------
--  测试
```

**Comment by DeoLeung** [comment]
yes I think the above solution should work.(but need to maintain a separate table)

alternatively, is using [indexes expression](https://www.postgresql.org/docs/11/indexes-expressional.html) with pgroonga recommended? I'm thinking to have a convert function and then just build a pgroonga index on it

**Comment by kou** [comment]
How to convert pinyin (`ceshi` or `cs`) to kanji (`测试`) without conversion table?

**Comment by DeoLeung** [comment]
yes a conversion table is mandatory.

actually I meant I don't want to explicitly search the conversion table when generating the search sql. but I think I get your idea, I could just wrap the search into the convert function.

now the rest is to built a proper term/reading [table](https://github.com/digoal/blog/blob/master/201709/20170925_01.md). thx~
