### ISSUE TITLE
text size

### ISSUE THREAD

**Issue by kengcher** [pgroonga/pgroonga#109]
hi

i am thinking of using pgroonga but was wondering if it has the same 1Mb limitation as when i try to index my column with gin i get this error:
CREATE INDEX desc_text_idx ON table USING GIN (to_tsvector('english', Desc_Text))
ERROR: string is too long for tsvector (1076204 bytes, max 1048575 bytes)

Thank you.

**Comment by kou** [comment]
There is no 1MiB limitation in PGroonga.

**Comment by kengcher** [comment]
That's great! Is it possible to build an index on multiple columns e.g.

CREATE INDEX text_idx ON pgroonga.test USING pgroonga (Title, Abstract, Desc);

and how should I query the created index?

Thanl you.

**Comment by kou** [comment]
Please don't use one issue for multiple topics.
Please create a new issue for another topic.
