### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by kengcher** [pgroonga/pgroonga#111]
Hi

1) Is there a way to get the list of tokens and their counts from the index for a record?
2) for very common tokens, e.g. "cat" it takes a long time to run? does it mean that it is picking up other tokens that have the letters "cat", e.g. "catastrophic"? is there a way to use SELECT * FROM RECORDS WHERE &@ ' cat '; or does it ignore the spaces?

Thank you!

**Comment by kou** [comment]
1. You can use `pgroonga_tokenize` function https://pgroonga.github.io/reference/functions/pgroonga-tokenize.html for it. But why do you want to do it?
2. It may take a long time to run but it doesn't take a long time in most cases. "cat" matches "catastrophic" by default. Spaces are ignored.

Please don't use one issue for multiple questions. Please use one issue for one question.
