### ISSUE TITLE
Using &~

### ISSUE THREAD

**Issue by anthonydafc** [pgroonga/pgroonga#116]
Hello, we are trying to use the &~ operator, but can we use for finding letters that are at the beginiing, middle and end of word.

For example, i have the word "superman", i want to find this word if i type "super", "man" or "perm". Is it possible with this operator ?
today we use something like this "(p.ftexte &~ '.*FIND' )"

**Comment by kou** [comment]
> For example, i have the word "superman", i want to find this word if i type "super", "man" or "perm". Is it possible with this operator ?

They should be matched.

Could you provide an example (`CREATE TABLE`/`CREATE INDEX`/`INSERT`/`SELECT`) that reproduces this case?

**Comment by anthonydafc** [comment]
it works now. i don't no what happened.
Still concerning my tests. Can we use "Score" with the &~ operator ?

**Comment by kou** [comment]
> Can we use "Score" with the &~ operator ?

Yes.
