### ISSUE TITLE
Race condition in PGrnLookupSourcesTable?

### ISSUE THREAD

**Issue by rtpg** [pgroonga/pgroonga#117]
Context:
 For a while, I have had a SQL dump that fails on several runs on some inserts with a `failed to insert record: <3>` style failure.

 This SQL dump relies on multiple connections (if I try to do it all on a single connection the error doesn't appear).

 I've also removed all `SELECT` statements from the SQL dump, so this file contains basically just a bunch of `INSERT`s, `UPDATE`s,`DELETE`s and `TRUNCATE`s (all happening within transactions, if that matters).

Unfortunately this dump still contains a lot of private information, so I cannot post it here (I am trying to rewrite stuff to try and keep a reproduction, but I am not there yet).

-----

While investigating this failure, I found the following thing out, by adding some logging into `PgrnInsert`.

For the most part in a run `pgroonga` is just calling to `groonga` by inserting stuff into a hashtable like so:
```
2019-11-07 13:55:43.388 JST [75794] WARNING:  YYQ ADD DATA #<key 1 table:#<hash Sources12327318 key:UInt64>>
2019-11-07 13:55:43.405 JST [75794] WARNING:  YYQ adding to table (from RAW INSERT)
2019-11-07 13:55:43.406 JST [75794] WARNING:  YYQ ADD DATA #<key 2 table:#<hash Sources12327318 key:UInt64>>
2019-11-07 13:55:43.469 JST [75690] WARNING:  YYQ adding to table (from RAW INSERT)
2019-11-07 13:55:43.469 JST [75690] WARNING:  YYQ ADD DATA #<key 3 table:#<hash Sources12327318 key:UInt64>>
2019-11-07 13:55:44.782 JST [75794] WARNING:  YYQ adding to table (from RAW INSERT)
20
```

When the SQL replay passes and there is no `groonga` failure, all the inserts are into hash tables and succeed.

_However_, when the SQL replay fails and I get the` pgroonga: failed to add a record: <3>: [table][add][pat] failed to add: #...`  error, what I see is a little different:

```
2019-11-07 13:56:23.450 JST [75953] WARNING:  YYQ ADD DATA #<key 1 table:#<hash Sources12357897 key:UInt64>>
2019-11-07 13:56:23.464 JST [75953] WARNING:  YYQ adding to table (from RAW INSERT)
2019-11-07 13:56:23.464 JST [75953] WARNING:  YYQ ADD DATA #<key 2 table:#<hash Sources12357897 key:UInt64>>�	�
2019-11-07 13:56:23.515 JST [75690] WARNING:  YYQ Looked up source table type was GRN_TABLE_PAT_KEY
2019-11-07 13:56:23.515 JST [75690] WARNING:  YYQ adding to table (from RAW INSERT)
2019-11-07 13:56:23.515 JST [75690] WARNING:  YYQ ADD DATA #<key "\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000" table:#<pat Sources12357897 key:ShortText>>
2019-11-07 13:56:23.520 JST [75690] ERROR:  pgroonga: failed to add a record: <3>: [table][add][pat] failed to add: #<key "\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0
```

While the first two inserts are into a hash table. For some reason the third command is trying to insert into the same table but it says it's a pat trie??

Digging deeper into this, I was able to figure out that, inside `pgroonga_insert_raw`,  there is a call to `PgrnLookupSourcesTable`:

`	sourcesTable = PGrnLookupSourcesTable(index, ERROR);`

^ this line is what gets the table, and this table `grn_obj*` remains basically untouched until it gets into `PgrnInsert`

I added logging around the `sourcesTable` call in `pgroonga_insert_raw` like so:

```
	sourcesTable = PGrnLookupSourcesTable(index, ERROR);
    if (sourcesTable->header.type != GRN_TABLE_HASH_KEY) {
		elog(WARNING, "YYQ Looked up source table type was %s ", obj_types[sourcesTable->header.type]);
	}
```

Running my tests again got me  the following when the test run failed:

```2019-11-07 13:56:23.515 JST [75690] WARNING:  YYQ Looked up source table type was GRN_TABLE_PAT_KEY```

So it looks like sometimes `PGrnLookupSourcesTable` will return a mis-shapen object, where the table is misidentified.

-----

`PGrnLookupSourcesTable` ends up bubbling down into the following function:
```
grn_obj *
PGrnLookupWithSize(const char *name,
				   size_t nameSize,
				   int errorLevel)
{
	grn_obj *object;
	PGrnEnsureDatabase();
	object = grn_ctx_get(ctx, name, nameSize);
	if (!object)
		ereport(errorLevel,
				(errcode(ERRCODE_INVALID_NAME),
				 errmsg("pgroonga: object isn't found: <%.*s>",
						(int)nameSize, name)));
	return object;
}
```

The `PGrnEnsureDatabase` function makes sure that `ctx` static is properly set up. 

So basically `grn_ctx_get` seems to be returning the wrong kind of info sometimes, but it seems to be happening only in multithreaded cases.

My current theory is that *PGrnLookupWithSize is not thread safe*. Or more specifically, `ctx` usage is not thread safe, and it's causing some sort of memory corruption in a multi-thread environment.

------

To summarise:
- `PGrnLookupWithSize` in certain cases returns object data that is incorrect
- This only seems to happen in cases where there are a bunch of connections 

My questions:
- I imagine this stuff is meant to be thread safe, should there be some locking going on on usage of `ctx`?
- Is this maybe a `groonga`-level issues?

I have set up complilation of `pgroonga` so I can test various things if needed. I would really like to have a SQL repro that I can share with everyone but we're not there yet.

**Comment by kou** [comment]
Interesting.

PostgreSQL uses multi process model instead of multi thread model. So PGroonga isn't run with multiple threads.

Could you try removing `TRUNCATE` in the reproducible test? If the test without `TRUNCATE` doesn't reproduce this case, `TRUNCATE` will be related.

**Comment by rtpg** [comment]
During my test, I saw different `ctx` objects being used, but only one groonga DB file being opened. Is there any locking that happens inside `groonga` during writes? 

In other words: what is the coordination mechanism inside pgroonga/groonga to make sure that multiple processes don't overwrite each other's work/potentially corrupt things?

I'll try to remove the `TRUNCATE`s, though it might be difficult because of uniqueness constraints.

**Comment by kou** [comment]
> I saw different `ctx` objects being used

In the same process?

> Is there any locking that happens inside groonga during writes?

Yes.

> what is the coordination mechanism inside pgroonga/groonga to make sure that multiple processes don't overwrite each other's work/potentially corrupt things?

`mmap()` and atomic count up/down: https://github.com/groonga/groonga/blob/master/lib/io.c#L1401

**Comment by kou** [comment]
I think that we can fix this.
