### ISSUE TITLE
question about root words searching

### ISSUE THREAD

**Issue by kengcher** [pgroonga/pgroonga#119]
Hi

I thought pgroonga picks out derivatives of the query string, e.g. "actual" in this case which i would like it to pull out both rows. but if i use SELECT * FROM memos WHERE content &@ 'actual' it only returns the 2nd row instead of both. if i use 'actua' then both rows are returned. is this something to do with the space after 'actual' in row 2?

How can i get the behavior that i was thinking of?

Thank you.

CREATE TABLE memos (
id integer,
content text
);

CREATE INDEX pgroonga_content_index
ON memos
USING pgroonga (content);

truncate table memos;

INSERT INTO memos VALUES (1, 'actualize potential');
INSERT INTO memos VALUES (2, 'actual potential');

SELECT * FROM memos WHERE content &@ 'actual'

**Comment by komainu8** [comment]
We can use "TokenFilterStem" as below in this case.
See also：http://groonga.org/docs/reference/token_filters/token_filter_stem.html

```sql
CREATE TABLE memos (
id integer,
content text
);

CREATE INDEX pgroonga_content_index
          ON memos
       USING pgroonga (content)
        WITH (plugins='token_filters/stem',
              token_filters='TokenFilterStem');

INSERT INTO memos VALUES (1, 'actualize potential');
INSERT INTO memos VALUES (2, 'actual potential');

SELECT * FROM memos WHERE content &@ 'actual';
 id |       content       
----+---------------------
  1 | actualize potential
  2 | actual potential
(2 rows)
```

Note: We need to install a groonga-token-filter-stem package to use this tokenizer.

**Comment by kou** [comment]
No response.

**Comment by at-hungnguyen** [comment]
@kengcher you can force to use Loosely Search to get response with 'actual'
