### ISSUE TITLE
Storange character found in When I use pgroonga.text_regexp_ops index and like query.

### ISSUE THREAD

**Issue by hiroyuki-sato** [pgroonga/pgroonga#12]
When I execute following query(q7.sql). I found strange characters in pgroonga.log.

```sql
SELECT
  u.url 
FROM 
  url_lists u,
  keywords k
WHERE
  u.url like k.url;
```

u.url has pgroonga.text_regexp_ops index.

[test sql](https://github.com/hiroyuki-sato/pgroonga_like_test)

![](https://gist.githubusercontent.com/hiroyuki-sato/a1b74c63b27dc4ed5988/raw/213e61b5883ae5d1d108bbe846db6ee2b86df1a6/pgroonga.png)

[detail](https://gist.github.com/hiroyuki-sato/a1b74c63b27dc4ed5988)

**Comment by kou** [comment]
It's not strange. The character is used for marking "the beginning of text". It's U+FFEF in unicode.

**Comment by hiroyuki-sato** [comment]
OK. thanks.
