### ISSUE TITLE
Failed to build for PostgreSQL12.x under Windows

### ISSUE THREAD

**Issue by mosynaq** [pgroonga/pgroonga#120]
Hey everybody and thanks a lot for this piece of software.
Since there is no pre-built version for PostgreSQL 12.x under Windows, I tried to build it from source. Following instructions [from this page](https://pgroonga.github.io/install/source.html#windows), I received the following error:

    ...
    "C:\path\to\pgroonga-2.2.2\ALL_BUILD.vcxproj" (default target) (1) ->
    "C:\path\to\pgroonga-2.2.2\vendor\groonga\src\grndb.vcxproj" (default target) (3) ->
    "C:\path\to\pgroonga-2.2.2\vendor\groonga\lib\libgroonga.vcxproj" (default target) (4) ->
    "C:\path\to\pgroonga-2.2.2\vendor\groonga\vendor\mruby\mruby.vcxproj" (default target) (6) ->
    (ClCompile target) ->
    C:\path\to\pgroonga-2.2.2\vendor\groonga\vendor\mruby\mruby-onig-regexp\src\mruby_onig_regexp.c(634): error C2275: 'mrb_value' : illegal use of this type as  an expression [C:\path\to\pgroonga-2.2.2\vendor\groonga\vendor\mruby\mruby.vcxproj]
    C:\path\to\pgroonga-2.2.2\vendor\groonga\vendor\mruby\mruby-onig-regexp\src\mruby_onig_regexp.c(634): error C2146: syntax error : missing ';' before identif ier 'ret' [C:\path\to\pgroonga-2.2.2\vendor\groonga\vendor\mruby\mruby.vcxproj]
    C:\path\to\pgroonga-2.2.2\vendor\groonga\vendor\mruby\mruby-onig-regexp\src\mruby_onig_regexp.c(634): error C2065: 'ret' : undeclared identifier [C:\Users\G vm\Desktop\pgroonga-2.2.2\vendor\groonga\vendor\mruby\mruby.vcxproj]
    C:\path\to\pgroonga-2.2.2\vendor\groonga\vendor\mruby\mruby-onig-regexp\src\mruby_onig_regexp.c(634): error C2440: '=' : cannot convert from 'mrb_value' to
    'int' [C:\path\to\pgroonga-2.2.2\vendor\groonga\vendor\mruby\mruby.vcxproj]
    C:\path\to\pgroonga-2.2.2\vendor\groonga\vendor\mruby\mruby-onig-regexp\src\mruby_onig_regexp.c(635): error C2065: 'ret' : undeclared identifier [C:\Users\G vm\Desktop\pgroonga-2.2.2\vendor\groonga\vendor\mruby\mruby.vcxproj]
    C:\path\to\pgroonga-2.2.2\vendor\groonga\vendor\mruby\mruby-onig-regexp\src\mruby_onig_regexp.c(635): error C2440: 'function' : cannot convert from 'int' to  'mrb_value' [C:\path\to\pgroonga-2.2.2\vendor\groonga\vendor\mruby\mruby.vcxproj]
    C:\path\to\pgroonga-2.2.2\vendor\groonga\vendor\mruby\mruby-onig-regexp\src\mruby_onig_regexp.c(636): error C2065: 'ret' : undeclared identifier [C:\Users\G vm\Desktop\pgroonga-2.2.2\vendor\groonga\vendor\mruby\mruby.vcxproj]
    C:\path\to\pgroonga-2.2.2\vendor\groonga\vendor\mruby\mruby-onig-regexp\src\mruby_onig_regexp.c(636): error C2440: 'function' : cannot convert from 'int' to  'mrb_value' [C:\path\to\pgroonga-2.2.2\vendor\groonga\vendor\mruby\mruby.vcxproj]
    C:\path\to\pgroonga-2.2.2\vendor\groonga\vendor\mruby\mruby-onig-regexp\src\mruby_onig_regexp.c(637): error C2065: 'ret' : undeclared identifier [C:\Users\G vm\Desktop\pgroonga-2.2.2\vendor\groonga\vendor\mruby\mruby.vcxproj]
    C:\path\to\pgroonga-2.2.2\vendor\groonga\vendor\mruby\mruby-onig-regexp\src\mruby_onig_regexp.c(637): error C2440: 'return' : cannot convert from 'int' to ' mrb_value' [C:\path\to\pgroonga-2.2.2\vendor\groonga\vendor\mruby\mruby.vcxproj]
    C:\path\to\pgroonga-2.2.2\vendor\groonga\vendor\mruby\mruby-onig-regexp\src\mruby_onig_regexp.c(770): error C2440: 'initializing' : cannot convert from 'mrb _value' to 'mrb_float' [C:\path\to\pgroonga-2.2.2\vendor\groonga\vendor\mruby\mruby.vcxproj]
    C:\path\to\pgroonga-2.2.2\vendor\groonga\vendor\mruby\mruby-onig-regexp\src\mruby_onig_regexp.c(770): error C2440: 'initializing' : cannot convert from 'mrb _value' to 'mrb_vtype' [C:\path\to\pgroonga-2.2.2\vendor\groonga\vendor\mruby\mruby.vcxproj]
    C:\path\to\pgroonga-2.2.2\vendor\groonga\vendor\mruby\mruby-onig-regexp\src\mruby_onig_regexp.c(998): error C2440: 'initializing' : cannot convert from 'mrb _value' to 'mrb_float' [C:\path\to\pgroonga-2.2.2\vendor\groonga\vendor\mruby\mruby.vcxproj]
    C:\path\to\pgroonga-2.2.2\vendor\groonga\vendor\mruby\mruby-onig-regexp\src\mruby_onig_regexp.c(998): error C2440: 'initializing' : cannot convert from 'mrb _value' to 'mrb_vtype' [C:\path\to\pgroonga-2.2.2\vendor\groonga\vendor\mruby\mruby.vcxproj]

    264 Warning(s)
    14 Error(s)

I cannot figure out the problem. What should I do?
p.s.
a prebuilt version for PostgreSQL 12.x 64 bit under Windows is highly welcome! :)

**Comment by kou** [comment]
Ah, We forgot to provide a Windows package for PostgreSQL 12.
We'll provide it.

**Comment by kou** [comment]
Done. We'll provide a Windows package for PostgreSQL 12 in the next release.
You can use a snapshot package at https://ci.appveyor.com/project/groonga/pgroonga/build/job/l7326413ujykd7m8/artifacts for now.
