### ISSUE TITLE
Question about `LIKE '%query%'`

### ISSUE THREAD

**Issue by OrKoN** [pgroonga/pgroonga#121]
The native query `LIKE '%query%'` will find anything that contains `query` as a substring. I am trying pgroonga and it seems that it'd return results only if the query is a prefix of a token. For example, if the data is `abcdefg` searching for it with `LIKE '%bcdefg%'` will return zero results. Is it intended to work this way? And is there a way to build the index in a different way so that queries like `LIKE '%bcdef%'` and `LIKE '%bcdefg%'` would match `abcdefg`?

Sorry, if I have overlooked the answer in the documentation.

**Comment by kou** [comment]
The following will solve your problem:

```sql
CREATE INDEX ...
  USING pgroonga (...)
  WITH (tokenizer='TokenNgram("unify_alphabet", false');
```

See also:

  * https://pgroonga.github.io/reference/create-index-using-pgroonga.html#custom-tokenizer
  * https://groonga.org/docs/reference/tokenizers/token_ngram.html

**Comment by OrKoN** [comment]
Thanks I will take a look! Do you know if it will work for other languages like Arabic? (the doc says `If we set false, TokenNgram uses bigram tokenize method for ASCII character.`)

**Comment by kou** [comment]
Yes, it will work for all languages.

If you want `LIKE` behavior, you may want to set `false` to `"unify_symbol"` and `"unify_digit` too.

* https://groonga.org/docs/reference/tokenizers/token_ngram.html#unify-symbol
* https://groonga.org/docs/reference/tokenizers/token_ngram.html#unify-digit

**Comment by OrKoN** [comment]
Thanks! It works. For others who might find this thread it was not immediately clear to me how to define multiple parameters, here is how:

```
USING pgroonga (name) WITH (tokenizer='TokenNgram("unify_alphabet", false, "unify_digit", false, "unify_symbol", false)')
```

**Comment by kou** [comment]
Thanks for the additional information.
