### ISSUE TITLE
 An error that pgroonga.dll is not found occurs.

### ISSUE THREAD

**Issue by sakaiSuzuki** [pgroonga/pgroonga#122]
environment:
　・ WindowsServer 2016 Standard
　・ PostgreSQL 12.1
　・ PGroonga2.2.2

Extract PGroonga to PostgreSQL folder and execute “CREATE EXTENSION pgroonga;” SQL
An error has occurred.

```text
pgroonga.dll The specified module could not be found
```

However, it actually exists in the directory indicated by the error.
I tried using PostgreSQL 11.6 with the same procedure, and it was successfully installed.

Could you tell me if there is a solution?
Thank you.

**Comment by kou** [comment]
How did you install PGroonga 2.2.2 for PostgreSQL 12.1?
We didn't release it: https://github.com/pgroonga/pgroonga/releases/tag/2.2.2

If you can use PGroonga with PostgreSQL 12.1, you can use unreleased version: https://ci.appveyor.com/project/groonga/pgroonga/builds/29704381/job/5i0fun39otr3n4um/artifacts

**Comment by sakaiSuzuki** [comment]
Thank you for the quick reply.
The following page says "Added support for PostgreSQL 12."
I assumed it was supported.
https://pgroonga.github.io/ja/news/

It was not released.
Thank you for your response.
