### ISSUE TITLE
Truncate on a table with pgroonga indexes causing an error

### ISSUE THREAD

**Issue by OrKoN** [pgroonga/pgroonga#123]
Hi,

It seems that calling a truncate command on a pgroonga table is causing an error for us:

```
TRUNCATE TABLE "project_item" CASCADE
```

causing 

```
error: pgroonga: failed to create table: <Lexicon3545989_0>: [object][register] already used name was assigned: <Lexicon3545989_0>
```

We have one field with a pgroonga index `WITH (tokenizer='TokenNgram("unify_alphabet", false, "unify_digit", false, "unify_symbol", false)')` and the table is empty.

Does truncating require some special steps? Or is it a bug?

pgroonga 2.2.2

**Comment by kou** [comment]
Could you provide SQL to reproduce this case from scratch?

**Comment by OrKoN** [comment]
@kou I will try to reproduce it outside of my app and will share the SQL as soon as I have it.

**Comment by kou** [comment]
Thanks!

**Comment by OrKoN** [comment]
Here is the SQL. The difference to the normal situation seems to be the presence of the transaction:

```
BEGIN TRANSACTION;
CREATE EXTENSION IF NOT EXISTS pgroonga;
CREATE TABLE test (
    id SERIAL PRIMARY KEY,
    content text
);
CREATE INDEX test_id ON test USING pgroonga (content) WITH (tokenizer='TokenNgram("unify_alphabet", false, "unify_digit", false, "unify_symbol", false)');
TRUNCATE TABLE test CASCADE;
ABORT;
```
Output:

```
NOTICE:  extension "pgroonga" already exists, skipping
BEGIN
CREATE EXTENSION
CREATE TABLE
CREATE INDEX
ERROR:  pgroonga: failed to create table: <Lexicon3549098_0>: [object][register] already used name was assigned: <Lexicon3549098_0>
```
In my case, I execute the truncate as part of database migrations so it's wrapped in a transaction.

**Comment by OrKoN** [comment]
The postgresql version is 12.1.0

**Comment by kou** [comment]
Thanks. I could reproduce this case.
I've added support for running `CREATE TABLE`, `CREATE INDEX` and `TRUNCATE` in the same transaction.

Workaround: Running `CREATE TABLE` and `TRUNCATE` in the different transaction:

```sql
BEGIN TRANSACTION;
CREATE EXTENSION IF NOT EXISTS pgroonga;
CREATE TABLE test (
    id SERIAL PRIMARY KEY,
    content text
);
CREATE INDEX test_id ON test USING pgroonga (content) WITH (tokenizer='TokenNgram("unify_alphabet", false, "unify_digit", false, "unify_symbol", false)');
COMMIT;

BEGIN TRANSACTION;
TRUNCATE TABLE test CASCADE;
COMMIT;
```

**Comment by OrKoN** [comment]
@kou Thanks for so fast reaction!

We also found another workaround: to remove the index before truncate and re-create it afterwards. Our migration tool does not allow us to split individual migrations into separate transactions. So for others who might have the same problem, I wanted to mention the other workaround.
