### ISSUE TITLE
postgresql-server-10 package is not available on Ubuntu

### ISSUE THREAD

**Issue by volo-zyko** [pgroonga/pgroonga#128]
postgresql-server-dev-10 can be found, for example [here](https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=postgresql-server&searchon=names) but due to dependency on postgresql-server-10 the newly built 2.2.3-1 cannot be installed. There is an error `postgresql-10-pgroonga : Depends: postgresql-server-10 but it is not installable`, for example [here](https://circleci.com/gh/zulip/zulip/36536?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).

https://github.com/pgroonga/pgroonga/blob/c6578d10a1db476eb83fa52c978fcf1307c7360f/packages/postgresql-10-pgroonga/debian/control.in#L20

**Comment by kou** [comment]
Oh...
Thanks for your report.

We'll release 2.2.4 soon.
