### ISSUE TITLE
Pgroonga  for Focal Ubuntu(20.04)

### ISSUE THREAD

**Issue by arpit551** [pgroonga/pgroonga#129]
As Ubuntu 20.04 (Focal) is due to be released on April 23, 2020.
Groonga PPA should now be available for Focal too.

**Comment by kou** [comment]
Oh, sorry for missing this.

**Comment by arpit551** [comment]
@kou duplicate for [#1084](https://github.com/groonga/groonga/issues/1084l)

**Comment by kou** [comment]
Done.
