### ISSUE TITLE
PGroonga fails when query returns a large number of results

### ISSUE THREAD

**Issue by mikeizbicki** [pgroonga/pgroonga#130]
I have a fairly large table (188 million rows) that contains a text field `title` with many different languages.  This field has the titles of newspaper articles gathered from around the web over the past year.  Recently, many of these articles have been about the coronavirus, and so I generated a query to count the number of articles.  

About 2 weeks ago, the query was working correctly, and returned approximately 50,000 entries in all languages.  Currently, however, the query is returning fewer matches (I am 100% sure that I have only performed inserts into this table since then), and in particular is not returning any english language entries.  Running a similar query on a `GIN` index shows that there are currently more than 400,000 articles matching the query.

I would like my query using pgroonga to return the full set of matching rows, and not only a subset.
I'm wondering if the groonga or pgroonga are designed is such a way that they intentionally do not return the full set of rows matching a query once that number of rows gets too large?  If so, is there a way to disable that behavior?

----

The full table schema is:
```
CREATE TABLE articles (
    id_articles BIGSERIAL PRIMARY KEY,
    id_responses BIGINT NOT NULL,
    id_urls BIGINT NOT NULL, 
    id_urls_canonical BIGINT NOT NULL, 
    hostname VARCHAR(253) NOT NULL,
    title TEXT,
    text TEXT,
    html TEXT,
    lang VARCHAR(2),
    pub_time TIMESTAMP,
    FOREIGN KEY (id_urls) REFERENCES urls(id_urls) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY (id_urls_canonical) REFERENCES urls(id_urls) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY (id_responses) REFERENCES responses(id_responses) DEFERRABLE INITIALLY DEFERRED
);
```
And the pgroonga index was created with
```
CREATE INDEX articles_index_pgroonga_title ON articles USING pgroonga(title);
```
The query in question is:
```
SELECT distinct on (hostname,title) lang,hostname,date_trunc('day',pub_time) as day,title 
FROM articles 
WHERE title &@~ 'coronavirus OR コロナウイ ルス OR ﺎﻠﺗﺎﺟﻯ OR 新冠病毒 OR 中国病毒 OR 코로나'  
```
And the query plan using `explain` is
```
 Unique  (cost=7089874.87..7091327.89 rows=192866 width=78)
   ->  Sort  (cost=7089874.87..7090359.21 rows=193735 width=78)
         Sort Key: hostname, title
         ->  Bitmap Heap Scan on articles  (cost=48.43..7064251.33 rows=193735 width=78)
               Recheck Cond: (title &@~ 'coronavirus OR コロナウイ ルス OR ﺎﻠﺗﺎﺟﻯ OR 新冠病毒 OR 中国病毒 ^C 코로나'::text)
               ->  Bitmap Index Scan on articles_index_pgroonga_title  (cost=0.00..0.00 rows=1937350 width=0)
                     Index Cond: (title &@~ 'coronavirus OR コロナウイ ルス OR ﺎﻠﺗﺎﺟﻯ OR 新冠病毒 OR 中国病毒 OR 코로나'::text)
```
I know that my text is still in the index, because if I modify my query to remove non-english text:
```
SELECT distinct on (hostname,title) lang,hostname,date_trunc('day',pub_time) as day,title 
FROM articles 
WHERE title &@~ 'coronavirus'  
```
then I get many more results than the original query.  This query also has essentially the same query plan as the original.

My version information:
```
$ psql --version
psql (PostgreSQL) 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1)

$ psql -c 'SELECT * FROM pg_extension';
      extname       | extowner | extnamespace | extrelocatable | extversion | extconfig | extcondition 
--------------------+----------+--------------+----------------+------------+-----------+--------------
 plpgsql            |       10 |           11 | f              | 1.0        |           | 
 pg_stat_statements |    16384 |         2200 | t              | 1.6        |           | 
 hll                |    16384 |         2200 | f              | 2.14       |           | 
 tablefunc          |    16384 |         2200 | t              | 1.0        |           | 
 btree_gist         |    16384 |         2200 | t              | 1.5        |           | 
 pgroonga           |    16384 |         2200 | f              | 2.2.5      |           | 
 btree_gin          |    16384 |         2200 | t              | 1.2        |           | 
 pgstattuple        |    16384 |         2200 | t              | 1.5        |           | 
(8 rows)
```

**Comment by mikeizbicki** [comment]
I just noticed that when I run the query
```
SELECT
    indexname,
    pg_size_pretty(rel_size) as size,
    tablespace
FROM (
    SELECT
        indexname,
        pg_relation_size(indexname::text) as rel_size,
        tablespace
    FROM pg_indexes
    WHERE
        schemaname = 'public'
    ORDER BY rel_size DESC
)t;
```
I get that my pgroonga index uses 0 bytes.  Is this expected output, or is this a sign that my index has been corrupted somehow?

**Comment by komainu8** [comment]
Thank you for your report.

Because of escalation is operating, PGroonga return records that match for as below query, probably.

```
SELECT distinct on (hostname,title) lang,hostname,date_trunc('day',pub_time) as day,title 
FROM articles 
WHERE title &@~ 'coronavirus'  
```

Groonga executes the exact match search basically.
However, if the result of the exact match search is 0 row, Groonga executes loosely search a little.

Therefore, I think that records hit by loosely search.

In the following query, Groonga does not execute loosely search.
Because keywords that except `coronavirus` have hit.

```
SELECT distinct on (hostname,title) lang,hostname,date_trunc('day',pub_time) as day,title 
FROM articles 
WHERE title &@~ 'coronavirus OR コロナウイ ルス OR ﺎﻠﺗﺎﺟﻯ OR 新冠病毒 OR 中国病毒 OR 코로나'  
```

In my opinion, if the definition of PGroonga's index changes to as below, I think that PGroonga returns just as result intended.

```
CREATE INDEX articles_index_pgroonga_title
ON articles
USING pgroonga(title)
WITH (tokenizer='TokenNgram("unify_alphabet", false, "unify_digit", false, "unify_symbol", false)');
```

Currently, PGroonga does not support `pg_relation_size()`.
Therefore, We can not confirm PGroonga's index size with `pg_relation_size()`.

We can calculate PGroonga's index size with du command.

```
du -sk ${PGDATA}/base/${DB_ID}/pgrn*
```

See: https://github.com/pgroonga/pgroonga/issues/15#issuecomment-179749455

Thanks,

**Comment by mikeizbicki** [comment]
Thank you for the helpful answer :)

When I try to run
```
CREATE INDEX articles_index_pgroonga_title
ON articles
USING pgroonga(title)
WITH (tokenizer='TokenNgram("unify_alphabet", false, "unify_digit", false, "unify_symbol", false)');
```
I get the error message
```
ERROR:  pgroonga: invalid tokenizer: <TokenNgram("unify_alphabet", false, "unify_digit", false, "unify_symbol", false)>: [options] MessagePack is required
```
Googling for `MessagePack` doesn't give me anything that looks relevent.

I can use the `TokenNgram` without parameters.  This command works fine:
```
SELECT pgroonga_tokenize('aBcDe 123','tokenizer', 'TokenNgram');
```
But with parameters things don't work.  This command gives the same error as above
```
SELECT pgroonga_tokenize('aBcDe 123','tokenizer', 'TokenNgram("unify_alphabet","false")');
```

**Comment by komainu8** [comment]
This error occurs when the MassgaePack is invalid.

Normally, if PGroonga installs by the package, the Message pack is valid.

Do you use PGroonga that built from source codes?
If so, we can use options of TokenNgram by rebuilding with `make HAVE_MSGPACK=1`.
Or we can also use them by using "postgresql-10-pgroonga" package.

If we use "postgresql-10-pgroonga" package, we need to remove PGroonga that is made from source codes.
Specifically, we need to remove the following files. (For this example, we specify "/usr/local" for the prefix.)

  * /usr/local/include/groonga/
  * /usr/local/sbin/groonga*
  * /usr/local/etc/groonga/
  * /usr/local/var/run/groonga/
  * /usr/local/var/log/groonga/
  * /usr/local/bin/grndb
  * /usr/local/bin/goonga*
  * /usr/local/share/groonga/
  * /usr/local/lib/pkgconfig/groonga*
  * /usr/local/lib/libgroonga*
  * /usr/local/lib/groonga/

Thanks,

**Comment by mikeizbicki** [comment]
I had installed groonga from source and used the `postgresql-10-pgroonga` package for pgroonga.  I have reinstalled both using only the package and wass able to successfully run the create index command you suggested.  

Unfortunately, when I re-run my query I get essentially the same results.  Running the query returns no english language results, but I am confident that there are several hundred thousand exact matches of the english text because I regular expression query without the index finds them.

**Comment by mikeizbicki** [comment]
With some more experimenting, I believe I have narrowed down the bug.  It seems that nothing in my query string before the Japanese text is being processed.  For example, if I run the same query as before, but with English at the end:
```
SELECT lang,count(1) 
FROM (SELECT distinct on (hostname,title) lang,hostname,date_trunc('day',pub_time) as day,title 
FROM articles 
WHERE title &@~ 'コロナウイ ルス OR ﺎﻠﺗﺎﺟﻯ OR 新冠病毒 OR 中国病毒 OR 코로나 OR coronavirus'  order by hostname,title,day)t 
GROUP BY lang
ORDER BY count(1) DESC;
```
I get  correct results:
```
 lang | count  
------+--------
 en   | 347385
 es   |  40782
 ko   |  37178
 ja   |  24741
 it   |  20869
 fr   |  17316
 zh   |  11918
 de   |   7072
 la   |   4534
 ro   |   2532
```
But if I rerun the original query with the English text before the Japanese:
```
SELECT lang,count(1) 
FROM (SELECT distinct on (hostname,title) lang,hostname,date_trunc('day',pub_time) as day,title 
FROM articles 
WHERE title &@~ 'coronavirus OR コロナウイ ルス OR ﺎﻠﺗﺎﺟﻯ OR 新冠病毒 OR 中国病毒  OR 코로나'  order by hostname,title,day)t 
GROUP BY lang
ORDER BY count(1) DESC;
```
Then the English results get ignored:
```
 lang | count 
------+-------
 ko   | 37087
 ja   | 24566
 zh   | 11615
 en   |  1139
 la   |   210
 ru   |    19
 ky   |    18
 qu   |    14
 eu   |    11
 sw   |     7
```
(Actually all the Latin-based languages get ignored, but this makes sense because they all had the string `coronavirus` inside of them.)

If I place the Korean string `코로나` before the Japanese:
```
SELECT lang,count(1) 
FROM (SELECT distinct on (hostname,title) lang,hostname,date_trunc('day',pub_time) as day,title 
FROM articles 
WHERE title &@~ '코로나 OR コロナウイ ルス OR ﺎﻠﺗﺎﺟﻯ OR 新冠病毒 OR 中国病毒 OR coronavirus'  order by hostname,title,day)t 
GROUP BY lang
ORDER BY count(1) DESC;
```
then I get no Korean results:
```
 lang | count  
------+--------
 en   | 346587
 es   |  40776
 ja   |  24734
 it   |  20870
 fr   |  17317
 zh   |  11912
 de   |   7076
 la   |   4476
 ro   |   2534
 id   |   1237
```
And if I place everything before the Japanese:
```
SELECT lang,count(1) 
FROM (SELECT distinct on (hostname,title) lang,hostname,date_trunc('day',pub_time) as day,title 
FROM articles 
WHERE title &@~ 'ﺎﻠﺗﺎﺟﻯ OR 新冠病毒 OR 中国病毒 OR 코로나 OR coronavirus OR コロナウイ ルス'  order by hostname,title,day)t 
GROUP BY lang
ORDER BY count(1) DESC;
```
Then I only get Japanese results:
```
 lang | count 
------+-------
 ja   | 24554
 en   |   157
 la   |    58
 ru   |     3
 rw   |     3
 fr   |     3
 qu   |     2
 ur   |     1
 jv   |     1
 el   |     1
```

----

This seems like it would be easy for me to work around by just ensuring that all my Japanese langauge queries come first.   But it does make me wonder if maybe there are more issues related to combining multiple languages in a single query that I may encounter.

**Comment by kou** [comment]
Did you run the queries as is?

`"コロナウイ ルス"` includes a white space between "イ" and "ウ". If the white space is really included, the query is interpreted as `"コロナウイ" AND "ルス"`.

`"coronavirus OR コロナウイ ルス OR ﺎﻠﺗﺎﺟﻯ OR 新冠病毒 OR 中国病毒  OR 코로나"` is interpreted as:

  * `(("coronavirus" OR "コロナウイ") AND "ルス")` OR
  * `ﺎﻠﺗﺎﺟﻯ` OR
  * `新冠病毒` OR
  * `中国病毒` OR
  * `코로나`

`"コロナウイ" AND "ルス"` matches "コロナウイ ... ルス" text, "ルス ... コロナウイ" text and "コロナウイルス" text. So Japanese entries will be matched with `"コロナウイ" AND "ルス"` query.
But English entries will not be matched with `"coronavirus" AND "ルス"` query. Because English entries don't include `"ルス"` normally.

**Comment by mikeizbicki** [comment]
Ahh... that makes sense.  I was confused about the order of operations.

Thank you both for all the help!  PGroonga has been a major help for me in my projects :)

**Comment by kou** [comment]
You can use `(...)` to control the order of operations: `"coronavirus OR (コロナウイ ルス) OR ﺎﻠﺗﺎﺟﻯ OR 新冠病毒 OR 中国病毒 OR 코로나"`

BTW, we're collecting use cases: https://pgroonga.github.io/users/ :-)
