### ISSUE TITLE
Assertion failures on PostgreSQL 12

### ISSUE THREAD

**Issue by dxscjx123** [pgroonga/pgroonga#135]
Hi
I'm a developer of postgresql. Recently, I tested the pgronnga, but found some problems. I used the postgresql-12 from git://git.postgresql.org/git/postgresql.git, the branch is "REL_12_STABLE". And when I run the test cases, I found some cores.
![image](https://user-images.githubusercontent.com/17701710/83865203-76c7fd00-a758-11ea-91b0-c6bc402f00bd.png)
![image](https://user-images.githubusercontent.com/17701710/83865198-73cd0c80-a758-11ea-8082-2ec97a364be3.png)
the cases: wal-truncate.sql and existent.sql.
I found existent.sql core because of the assert in "relation_open"，the assert code was added in postgresql-12 in recent one year. 
So, do I test wrong, or there are some problems on pgroonga. I used pgroonga-2.2.5(from  wget https://packages.groonga.org/source/pgroonga/pgroonga-2.2.5.tar.gz). And the groonga is groonga-10.0.3, msgpack is master branch on github.
Thanks a lot.

**Comment by kou** [comment]
Thanks for your report.
I've fixed them.
