### ISSUE TITLE
Can't load pgroonga extension on Postgres-XL 10r1.1

### ISSUE THREAD

**Issue by nateekarn-e** [pgroonga/pgroonga#140]
Detail below include Postgres-XL installation from source, cluster setup and pgroonga extension installation. 

I get error on step 4.2)
-----------------------------------------------------------------------------------
ERROR:  Internal subtransactions not supported in Postgres-XL
CONTEXT:  PL/pgSQL function inline_code_block line 2 during statement block entry
-----------------------------------------------------------------------------------

**1) Install Postgres-XL from source on CentOS 8:**

1.1) install pre-requisite package

```bash
sudo yum install -y readline-devel zlib-devel gcc make flex
```

1.2) download source

```bash
wget https://www.postgres-xl.org/downloads/postgres-xl-10r1.1.tar.gz
```

1.3) extract source

```bash
tar xvfz postgres-xl-10r1.1.tar.gz
```

1.4) create install binary directory

```bash
sudo mkdir -p /opt/PGXL/prg/
```

1.5) configure

```bash
cd postgres-xl-10r1.1/
./configure --prefix=/opt/PGXL/prg
```

1.6) make

```bash
make
sudo make install
```

1.7) add postgres user & assign permission to folder

```bash
sudo adduser postgres
sudo chown -R postgres: /opt/PGXL
```

1.8) create data path

```bash
sudo mkdir -p /opt/PGXL/data
sudo chown -R postgres:postgres /opt/PGXL/data
```

1.9) set postgres-xl path for postgres user

```bash
su - postgres
vi .bash_profile and .bashrc(for pgxc_ctl shell)
```

```text
#append line
-----------------------------------
# add path for Postgresql-XL
PATH=$PATH:/opt/PGXL/prg/bin
-----------------------------------
```

1.10) pgxc_ctl setup

```bash
su - postgres
pgxc_ctl
```

```text
PGXC> prepare config empty
PGXC> exit
```

_Ref -> https://www.postgres-xl.org/documentation/installation.html_

**2) Postgres-XL Cluster Setup (testing on same machine):**

2.1) setup "ssh postgres@localhost" without password prompt

```bash
ssh-keygen -t rsa; # if .ssh/id_rsa.pub not exist
ssh-copy-id postgres@localhost
```

2.2) setup gtm, co-ordinator, datanode by pgxc_ctl

```bash
su - postgres
pgxc_ctl
```

```text
PGXC> add gtm master gtm localhost 20001 /opt/PGXL/data/gtm
PGXC> add coordinator master coord1 localhost 30001 30011 /opt/PGXL/data/coord_master.1 none none
PGXC> add datanode master dn1 localhost 40001 40011 /opt/PGXL/data/dn_master.1 none none none
# checking service
PGXC> monitor all
# stop service
PGXC> stop all
# start service
PGXC> start all
```

_Ref -> https://www.postgres-xl.org/documentation/tutorial-createcluster.html_

**3) Install PGroonga Extension on CentOS 8:**
Ref -> https://pgroonga.github.io/install/source.html

3.1) Pre-requisite

3.1.1) enable repo (Ref -> https://pgroonga.github.io/install/centos.html)

```bash
sudo -H dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-$(cut -d: -f5 /etc/system-release-cpe)-$(rpm -qf --queryformat="%{ARCH}" /etc/redhat-release)/pgdg-redhat-repo-latest.noarch.rpm
sudo -H dnf install -y https://packages.groonga.org/centos/groonga-release-latest.noarch.rpm
```

3.1.2) groonga-devel

```bash
sudo dnf install -y groonga-devel
```

3.1.3) msgpack-devel

```bash
sudo dnf install -y msgpack-devel
```

3.2) Compile from source

3.2.1) export PATH to pg_ctl exist and correct version

```bash
export PATH=/opt/PGXL/prg/bin:$PATH
```

3.2.2) `make HAVE_MSGPACK=1`

3.2.3) `make install`

**4) Load pgroonga extension**
4.1) create database (using coordinator#1, port 30001)

```bash
su - postgres
psql -p 30001
```

```text
psql> create database pgroonga_test1;
```

4.2) create extension

```text
psql> \c pgroonga_test1;
psql> create extension pgroonga;
```

```text
# checking
psql> \dx
```

_Ref -> https://pgroonga.github.io/install/centos.html, https://pgroonga.github.io/tutorial/_

**Comment by kou** [comment]
Thanks.
The next release will support Postgres-XL.
