### ISSUE TITLE
PGroongaのWAL適用処理について

### ISSUE THREAD

**Issue by BiscuitsColonel** [pgroonga/pgroonga#154]
ストリーミングレプリケーション環境のマスタで、PGroongaインデックスが設定されているカラムに対して「REINDEX CONCURRENTLY」した場合、スレーブ側で自動的にPGroongaのWALが適用される方法があるでしょうか。
加えて、マスタで「REINDEX CONCURRENTLY」後に、スレーブ側で初めてSELECTを実行した際、全件分のPGroongaのWALファイルの適用処理が実行されるので数十秒のダウンタイムが発生しています。このダウンタイムを防止する方法はあるでしょうか。
裏で同じテーブルを用意し、それに対してPGroongaのWAL適用後に、差し替えるしかないのかなと思っています。

**Comment by kou** [comment]
> スレーブ側で自動的にPGroongaのWALが適用される方法があるでしょうか。

ないです。
https://slide.rabbit-shocker.org/authors/komainu8/postgresql-conference-japan-2020/?page=97 を実装すれば実現できるはずです。

> このダウンタイムを防止する方法はあるでしょうか。

`SELECT`前に`pgroonga_wal_apply()`を実行してください。

* https://pgroonga.github.io/ja/reference/functions/pgroonga-wal-apply.html
* https://slide.rabbit-shocker.org/authors/komainu8/postgresql-conference-japan-2020/?page=82

**Comment by BiscuitsColonel** [comment]
わかりました、ありがとうございました。
