### ISSUE TITLE
pgroonga_highlight_html also highlight fullsize space

### ISSUE THREAD

**Issue by at-hungnguyen** [pgroonga/pgroonga#155]
`SELECT
  pgroonga_highlight_html('上木　政人', ARRAY ['政人'], 'pgroonga_make_highlight_index') AS highlight_html;`
i used this query to highilght **政人** in **上木　政人**
but the result also contains fullsize space like this: `上木<span class="keyword">　政人</span>.`
Please help me. I also tried to use index at TokenNgram with "n" = 1, but the result has not change.

**Comment by kou** [comment]
Groonga 10.1.0 will remove leading full width spaces.

**Comment by at-hungnguyen** [comment]
@kou  could you tell me when it was released?

**Comment by kou** [comment]
2020-12-29

We release a new version each 29th.
