### ISSUE TITLE
pgroonga: does &@~ not force loosely search when searching AND keywords

### ISSUE THREAD

**Issue by at-hungnguyen** [pgroonga/pgroonga#157]
Example: i have column called **title** with record: **Verified Difficulty**
When i searching by this query: `select title from memos where title &@~ 'ver OR dif'` => this record matched
But when i searching by query AND: `select title from memos where title &@~ 'ver dif'` => this record is not matched.
I guess &@~ does not support loosely search for AND query. is this right?
If yes, then has anyway to force loosely search for AND query?

Hope you help soon.
Thank you

Title was indexed by TokenMecab tokenizer.

Environments:
postgres9-alpine
GROONGA_VERSION=10.0.5 \
PGROONGA_VERSION=2.2.6

**Comment by kou** [comment]
You can use `pgroonga.force_match_escalation` variable since the next release.
