### ISSUE TITLE
PGroongaのREINDEX時の影響について

### ISSUE THREAD

**Issue by BiscuitsColonel** [pgroonga/pgroonga#158]
お世話になっております。
何度も質問すみません。

以下の手順に沿ってREINDEXによるPGroongaのWALメンテの手法を試させていただきました。
そして、最終的にREINDEXによってデータベースディレクトリの大きさが小さくなっていることを確認しましたが、どういったロジックでこのような結果となっているのかわかりません。
REINDEX前のpgrnファイルの合計が40820kBに対し、REINDEX後は20044kBに減っているということが大きく関わっているとは思いますが、どういった経緯でこうなるのでしょうか。
教えていただけると嬉しく思います。

## 1. マスターからテーブルの作成

```
test=# DROP TABLE IF EXISTS test_tbl;
DROP TABLE
test=# CREATE TABLE test_tbl (id INTEGER PRIMARY KEY, val text);
CREATE TABLE
test=#    INSERT INTO
  test_tbl
SELECT i, string_agg(str, '') 
  FROM 
  (SELECT chr(12449 + (random() * 1000)::int % 85 ) as str , i 
    FROM  generate_series(1,20) length, generate_series(1,10000) num(i)
   )t
   GROUP BY i;
INSERT 0 10000
test=# CREATE INDEX pgrn_index ON test_tbl USING pgroonga(val);
CREATE INDEX
```
## 2. スレーブから適用とVacuum

```
[postgres@test2 149346596]$ psql test -c "select pgroonga_wal_apply('pgrn_index')"
 pgroonga_wal_apply 
--------------------
              10007
(1 行)

[postgres@test2 149346596]$ psql test -c 'select pgroonga_vacuum()'
 pgroonga_vacuum 
-----------------
 t
(1 行)
```
## 3. スレーブからPGroongaWALの確認

```
[postgres@test2 149346596]$ du -a -k > /tmp/s1
[postgres@test2 149346596]$ psql test -t -c '\di+ pgrn_index' | sed 's/|//g' |sed 's/  / /g' >> /tmp/s1
```
## 4. マスターから9万件データ挿入

```
test=#    INSERT INTO
  test_tbl
SELECT i, string_agg(str, '') 
  FROM 
  (SELECT chr(12449 + (random() * 1000)::int % 85 ) as str , i 
    FROM  generate_series(1,20) length, generate_series(10001,100000) num(i)
   )t
   GROUP BY I;

INSERT 0 90000
```
## 5. スレーブから適用とVacuum

```
[postgres@test2 149346596]$ psql test -c "select pgroonga_wal_apply('pgrn_index')"
 pgroonga_wal_apply 
--------------------
              90014
(1 行)

[postgres@test2 149346596]$ psql test -c 'select pgroonga_vacuum()'
 pgroonga_vacuum 
-----------------
 t
(1 行)
```
## 6. PGroongaWALの確認

```
[postgres@test2 149346596]$ du -a -k > /tmp/s2
[postgres@test2 149346596]$ psql test -t -c '\di+ pgrn_index' | sed 's/|//g' |sed 's/  / /g' >> /tmp/s2
```
## 7. この時点でのPGroongaWAL出力量について

```
[postgres@test2 149346596]$ diff /tmp/s1 /tmp/s2
317,318c317,318
< 4276	./pgrn.000012C
< 536	./pgrn.000012E.c
---
> 5692	./pgrn.000012C
> 8188	./pgrn.000012E.c
337,339c337,339
< 448	./154060999
< 1128	./154061001
< 1348	./pgrn.000012D
---
> 2776	./154060999
> 10472	./154061001
> 13300	./pgrn.000012D
345c345
< 1984	./154060993
---
> 9880	./154060993
348,350c348,350
< 888	./pgrn.000012E
< 2414964	.
<  public  pgrn_index インデックス postgres test_tbl 1128 kB 
---
> 21764	./pgrn.000012E
> 2476428	.
>  public  pgrn_index インデックス postgres test_tbl 10 MB 
```
## 8. マスターからインデックスの再作成

```
test=# REINDEX INDEX pgrn_index ;
REINDEX
```
## 9. スレーブから適用

```
[postgres@test2 149346596]$ psql test -c "select pgroonga_wal_apply('pgrn_index')"
 pgroonga_wal_apply 
--------------------
             100007
(1 行)

[postgres@test2 149346596]$ psql test -c 'select pgroonga_vacuum()'
 pgroonga_vacuum 
-----------------
 t
(1 行)
```
## 10.PGroongaWALの確認

```
[postgres@test2 149346596]$ du -a -k > /tmp/s3
[postgres@test2 149346596]$ psql test -t -c '\di+ pgrn_index' | sed 's/|//g' |sed 's/  / /g' >> /tmp/s3
```
## 11. PGroongaWALの出力比較

```
[postgres@test2 149346596]$ diff /tmp/s2 /tmp/s3
5c5
< 640	./1249
---
> 616	./1249
316a317,318
> 5692	./pgrn.000012B
> 900	./pgrn.000012E
322c324
< 148	./pgrn.0000101
---
> 152	./pgrn.0000101
334c336
< 16320	./154061037
---
> 9880	./154061037
336,339c338,340
< 4032	./154061043
< 17472	./154061045
< 172	./pgrn.0000123
< 21508	./pgrn.0000126
---
> 2776	./154061043
> 172	./pgrn.000012C
> 4576	./pgrn.000012E.c
343a345,346
> 11176	./154061046
> 13300	./pgrn.000012D
346,350c349,350
< 5692	./pgrn.0000124
< 13300	./pgrn.0000125
< 8148	./pgrn.0000126.c
< 2490888	.
<  public  pgrn_index インデックス postgres test_tbl 10 MB  
---
> 2452696	.
>  public  pgrn_index インデックス postgres test_tbl 11 MB  
```

**Comment by kou** [comment]
`REINDEX`をするとPostgreSQL内部では新しくインデックスを作成し、古いインデックスはそのまま単に使われない状態になります。この時点では古いインデックスと新しいインデックスが両方存在するため、使用量は2倍になります。

その後、`VACUUM`（あるいは`pgroonga_vacuum()`）をすると古いインデックス関連のファイルがすべて削除され新しいインデックスだけが残ります。

これだけだと`REINDEX`前と単に同じになるだけですが、`REINDEX`時は静的なインデックス構築方法 https://groonga.org/ja/docs/reference/indexing.html#offline-index-construction という方法を使うのでそれでサイズが小さくなっているんだと思います。

`CREATE INDEX`した後に`INSERT`する場合は動的なインデックス構築方法 https://groonga.org/ja/docs/reference/indexing.html#online-index-construction を使っています。これは、作成したインデックスに対して順次データを登録していきます。すぐにインデックスを使えるのがメリットですが、構築速度や空間効率は静的な方法に劣ります。静的なインデックス構築方法はすでにあるデータをまとめて一気にインデックスを作成します。登録すべきデータがあらかじめわかっているため動的な方法よりも高速かつ空間効率よく構築できます。ただし、構築中は利用できません。しかし、そもそも`REINDEX`中のインデックスは構築完了後でないと使えないので問題にはなりません。

**Comment by BiscuitsColonel** [comment]
お早いご回答ありがとうございます。
Groonga特有の動作によって大きさが変わったのですね。
とてもわかりやすいです。
ということは、この場合ですとPGroongaのWALが9万件分溜まってしまうという話は関係ないということですかね？
REINDEXによって9万件分のPGroongaのWALが消えたからだと思っていました。
このWALを都度消しつつ、レプリケーション運用を可能にするにはpgroonga_truncate()を使う以外は成し得ないということに繋がってきますか？

**Comment by kou** [comment]
`REINDEX`するときは「9万件のデータ→インデックス作成」という手順の操作ログがPGroongaのWALとしてスタンバイサーバーに送られるのでPGroongaのWALデータの差ではないと思います。

PGroongaのWALの使用領域を一定に抑えるには、定期的に`pgroonga_truncate()`を使ってもいいですし、定期的に`REINDEX`を使ってもいいです。`REINDEX`を使えば、現在利用可能なデータだけがPGroongaのWALとしてスタンバイサーバーに転送されるので、それまでの「追加→削除→更新」というようなPGroongaのWALデータはなくなるからです。

**Comment by BiscuitsColonel** [comment]
なるほど、ありがとうございます。
PGroongaのWALの使用領域を一定に抑えるだけであって、常に最低限の使用領域を確保されているということも理解させ絵いただきました。
最後に聞かせていただきたいのですが、今回の場合のPGroongaのWALは「9万件のデータ→インデックス作成」という手順の操作ログが送られるだけということになりますと、「1万件のデータ→1万件のデータ→1万件のデータ→インデックス作成」という計4回の操作WALの方が「9万件のデータ→インデックス作成」のWALよりも大きくなりますか？

**Comment by kou** [comment]
「1万件のデータ→1万件のデータ→1万件のデータ」が「9万件のデータ」より大きければ「1万件のデータ→1万件のデータ→1万件のデータ→インデックス作成」のPGroongaのWALの方が大きくなりますし、小さければPGroongaのWALも小さくなります。

なお、「○○件のデータ→インデックス作成」というWALは`REINDEX`をすると発生しますが、「○○件のデータ→○○件のデータ→インデックス作成」というようにデータが複数に分かれるようなWALは発生しえません。`REINDEX`のときはデータを一気に登録するからです。（実際は「1件のデータ×9万」とかなので見方によっては「○○件のデータ→○○件のデータ→…」と言えなくもないですが。。。）

**Comment by BiscuitsColonel** [comment]
すみません、「9万件のデータ→インデックス作成」という動きはGroonga上の動作の話だったのですね。
PostgreSQL上での操作とごちゃごちゃになっていました。
ありがとうございました。
