### ISSUE TITLE
「PGroongaのWALはPostgreSQLのデータブロックに記録してあります」という意味について

### ISSUE THREAD

**Issue by BiscuitsColonel** [pgroonga/pgroonga#159]
お世話になっております。
たびたび申し訳ございません。

[pgroonga_wal_truncate](https://pgroonga.github.io/ja/reference/functions/pgroonga-wal-truncate.html)の内容についてお伺いしたいことがございましてお聞きいたします。

「PGroongaのWALはPostgreSQLのデータブロックに記録してあります」という一言がその関数の説明事項に書いてありますが、「PostgreSQLのデータブロック」というのは #153 の内容に記されているもののことですか？

ご回答いただけると嬉しいです。
よろしくお願いいたします。

**Comment by kou** [comment]
そのとおりです。
