### ISSUE TITLE
Install into public schema

### ISSUE THREAD

**Issue by patrick-jones** [pgroonga/pgroonga#16]
According to the [postgres wiki](https://wiki.postgresql.org/wiki/ExtensionPackaging#installing_and_removing_an_extension), 

> authors are not supposed to explicitly create a schema where to live in, because that means users will have to think about adapting their search_path, which can get pretty hairy sometimes

Most extensions just install to `public` so that there is no need to grant special permissions (as in #8 and #9) and the functions are available without qualification or changes to search_path.

I made a build on my machine that installed to `public` and was able to go through the tutorial without problems.

**Comment by kou** [comment]
We'll do it when PGroonga 2.0.0. Because it's a backward incompatible change.

**Comment by patrick-jones** [comment]
Understandable.  You might also want to consider prefixing some of the function names to make sure you don't collide with other extensions (for example, `pgroonga.score` -> `pgroonga_score`).

By the way, thanks for this great software. We have to support mixed English and Chinese, and pgroonga is a big help.

**Comment by kou** [comment]
> You might also want to consider prefixing some of the function names

Yes. We'll do.

> By the way, thanks for this great software. We have to support mixed English and Chinese, and pgroonga is a big help.

Thanks. If you can make your use case public, we want to list your use case in http://pgroonga.github.io/users/ . It's for spreading PGroonga.

**Comment by patrick-jones** [comment]
We're still early in development.  I'll be happy to be on your list when we are up and running.

**Comment by kou** [comment]
OK. I'll wait for it.

**Comment by kou** [comment]
Done.
It ships PGroonga 2.0.0.
