### ISSUE TITLE
PGroongaの各オブジェクトとコマンドの関係性について

### ISSUE THREAD

**Issue by BiscuitsColonel** [pgroonga/pgroonga#160]
お世話になっております。

PGroongaの各オブジェクトとコマンドについて個人的にまとめさせていただきました。
以下の認識で問題がないかご確認頂けると幸いです。

| オブジェクト | 存在場所 | 名前 | 作成タイミング | 不要になるタイミング | 削除タイミング |
| --- | --- | --- | --- | --- |---|
| PGroongaWALファイル（見た目は、PostgreSQLインデックス） | データベースディレクトリ内 | 数値で始まるファイル | 各種更新処理（※1）、インデックス作成処理（※2） | ー | データ削除処理（※3）、pgroonga_wal_truncate() |
| PGroongaインデックス（＝Groongaテーブル） | データベースディレクトリ内 | pgrnで始まるファイル |  各種更新処理（※1）、WAL適用処理（※4） |  データ削除処理（※3） | VACUUM（不要になったものだけ）、pgroonga_vacuum()（不要になったものだけ） |

※1. INSERT、UPDATE、DELETE
※2. CREATE INDEX、REINDEX INDEX
※3. DROP INDEX、REINDEX INDEX、TRUNCATE TABLE
※4. pgroonga_wal_apply、初回SELECT

**Comment by kou** [comment]
PGroongaWALファイルの削除タイミングも`VACUUM`な気がするんですが、※3で削除されましたか？

`pgroonga_wal_truncate()`はPGroongaWALファイルを削除するわけではなくてすでにあるファイルの中身を空にするだけです。

PGroongaWALファイルもデータ削除処理で不要になると思うのですが、不要になるとはどういう状態を想定していますか？

PGroongaインデックスはプライマリーの場合はインデックス作成処理でも作成されます。スタンバイの場合はたしかにインデックス作成処理ではなくWAL適用処理のときです。

**Comment by BiscuitsColonel** [comment]
>PGroongaWALファイルの削除タイミングもVACUUMな気がするんですが、※3で削除されましたか？

すみません、「削除」という表現に誤りがありました。
正しくは「空」にするでした。

>PGroongaWALファイルもデータ削除処理で不要になると思うのですが、不要になるとはどういう状態を想定していますか？

論理的に削除されている状態を想定しておりました。
PGroongaからもう一切使わない状態のことです。
VACUUM処理であとは物理的に削除されます。

>PGroongaインデックスはプライマリーの場合はインデックス作成処理でも作成されます。スタンバイの場合はたしかにインデックス作成処理ではなくWAL適用処理のときです。

確認できました。ありがとうございます。

再度表を編集させていただきますと、

| オブジェクト | 存在場所 | 名前 | 作成タイミング | 不要になるタイミング(論理削除) | 物理削除のタイミング |
| --- | --- | --- | --- | --- |---|
| PGroongaWALファイル（見た目は、PostgreSQLインデックス） | データベースディレクトリ内 | 数値で始まるファイル | 各種更新処理（※1）、インデックス作成処理（※2） | データ削除処理（※3）、pgroonga_wal_truncate() | VACUUM、pgroonga_vacuum() |
| PGroongaインデックス（＝Groongaテーブル） | データベースディレクトリ内 | pgrnで始まるファイル |  インデックス作成処理（※2）(プライマリー)、WAL適用処理（※4）(スタンバイ) |  データ削除処理（※3） | VACUUM、pgroonga_vacuum() |

※1. INSERT、UPDATE、DELETE
※2. CREATE INDEX、REINDEX INDEX
※3. DROP INDEX、REINDEX INDEX、TRUNCATE TABLE
※4. pgroonga_wal_apply、初回SELECT

**Comment by kou** [comment]
PGroongaWALファイルは各種更新処理をしなくてもインデックス作成処理のときに作成されると思います。「作成」タイミングではなく「更新」タイミングだったりしますか？

PGroongaWALファイルはPostgreSQL管理なので`pgroonga_vacuum()`では削除されないはずです。スタンバイではプライマリーでの`VACUUM`の処理がストリームレプリケーションされた時点で削除されると思います。

**Comment by kou** [comment]
PGroongaWALファイルは`pgroonga_wal_truncate()`で空になりますが、その後の処理では同じファイルを引き続き使うので不要になるわけではありません。

**Comment by BiscuitsColonel** [comment]
ご返信ありがとうございます。

>PGroongaWALファイルは各種更新処理をしなくてもインデックス作成処理のときに作成されると思います。「作成」タイミングではなく「更新」タイミングだったりしますか？

更新の意味も含めていました。わかりづらく、すみません。表に書き足させていただきます。

>PGroongaWALファイルはPostgreSQL管理なのでpgroonga_vacuum()では削除されないはずです。スタンバイではプライマリーでのVACUUMの処理がストリームレプリケーションされた時点で削除されると思います。

>PGroongaWALファイルはpgroonga_wal_truncate()で空になりますが、その後の処理では同じファイルを引き続き使うので不要になるわけではありません。

参考にさせていただき、表を再作成いたします。

| オブジェクト | 存在場所 | 名前 | 作成&更新タイミング | 不要になるタイミング(論理削除) | 物理削除のタイミング |
| --- | --- | --- | --- | --- |---|
| PGroongaWALファイル（見た目は、PostgreSQLインデックス） | データベースディレクトリ内 | 数値で始まるファイル | 各種更新処理（※1）、インデックス作成処理（※2） | データ削除処理（※3） | VACUUM |
| PGroongaインデックス（＝Groongaテーブル） | データベースディレクトリ内 | pgrnで始まるファイル |  インデックス作成処理（※2）(プライマリー)、WAL適用処理（※4）(スタンバイ) |  データ削除処理（※3） | VACUUM(プライマリーのみ)、pgroonga_vacuum() |

**Comment by kou** [comment]
更新であればPGroongaインデックスも各種更新処理で更新されます。

**Comment by BiscuitsColonel** [comment]
ありがとうございます。

以下の表を再度ご確認いただけると嬉しいです。

| オブジェクト | 存在場所 | 名前 | 作成タイミング | 更新タイミング | 不要になるタイミング(論理削除) | 物理削除のタイミング |
| --- | --- | --- | --- | --- |---|
| PGroongaWALファイル（見た目は、PostgreSQLインデックス） | データベースディレクトリ内 | 数値で始まるファイル | インデックス作成処理（※2）| 各種更新処理（※1） | データ削除処理（※3） | VACUUM |
| PGroongaインデックス（＝Groongaテーブル） | データベースディレクトリ内 | pgrnで始まるファイル |  インデックス作成処理（※2）(プライマリー)、WAL適用処理（※4）(スタンバイ)| 各種更新処理（※1） |  データ削除処理（※3） | VACUUM(プライマリーのみ)、pgroonga_vacuum() |

※1. INSERT、UPDATE、DELETE
※2. CREATE INDEX、REINDEX INDEX
※3. DROP INDEX、REINDEX INDEX、TRUNCATE TABLE
※4. pgroonga_wal_apply、初回SELECT

**Comment by kou** [comment]
PGroongaインデックスの更新タイミングですが、プライマリーは各種更新処理でいいのですが、スタンバイではWAL適用処理になります。

**Comment by BiscuitsColonel** [comment]
なるほど、細かいところまでありがとうございます。
何度もすみませんが、再度ご確認いただけると嬉しいです。

| オブジェクト | 存在場所 | 名前 | 作成タイミング | 更新タイミング | 不要になるタイミング(論理削除) | 物理削除のタイミング |
| --- | --- | --- | --- | --- |---|---|
| PGroongaWALファイル（見た目は、PostgreSQLインデックス） | データベースディレクトリ内 | 数値で始まるファイル | インデックス作成処理（※2）| 各種更新処理（※1） | データ削除処理（※3） | VACUUM |
| PGroongaインデックス（＝Groongaテーブル） | データベースディレクトリ内 | pgrnで始まるファイル |  インデックス作成処理（※2）(プライマリー)、WAL適用処理（※4）(スタンバイ)| 各種更新処理（※1）(プライマリー)、WAL適用処理（※4）(スタンバイ) |  データ削除処理（※3） | VACUUM(プライマリーのみ)、pgroonga_vacuum() |

※1. INSERT、UPDATE、DELETE
※2. CREATE INDEX、REINDEX INDEX
※3. DROP INDEX、REINDEX INDEX、TRUNCATE TABLE
※4. pgroonga_wal_apply、初回SELECT

**Comment by kou** [comment]
あっていると思います。

**Comment by BiscuitsColonel** [comment]
お時間いただき、ありがとうございました。
