### ISSUE TITLE
RHEL8でpostgresql10-pgroongaをインストールできない

### ISSUE THREAD

**Issue by usaken** [pgroonga/pgroonga#161]
こちらで質問すべき事項かわからなかったのですが、適切でなければご容赦ください。
下記手順を踏んだのですが、postgresql10-pgroongaをインストールできません。

```
# dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
# dnf install -y https://packages.groonga.org/centos/groonga-release-latest.noarch.rpm
# dnf module -y disable postgresql
# dnf install -y postgresql10-pgroonga
```

「一致するものが見つかりません」となります。試しに検索するとたしかにありませんでした。

```
# dnf search pgroonga
postgresql12-pgdg-pgroonga.x86_64 : Fast full-text search plugin for PostgreSQL based on Groonga
postgresql12-pgroonga.x86_64 : Fast full-text search plugin for PostgreSQL based on Groonga
postgresql13-pgdg-pgroonga.x86_64 : Fast full-text search plugin for PostgreSQL based on Groonga
```

ただ以下の場所にはpostgresql10-pgroongaがあります。
https://packages.groonga.org/centos/latest/x86_64/Packages/

dnfを使ってこれを取得するにはどうすればよいか教えて頂けないでしょうか。
特にpostgresql10にこだわっているわけではないのですがハードウェアリプレイスがあり、もともとpostgresql10で運用していたのでできるだけ問題が発生しないようバージョンを変えたくないのです。
2020年7月頃にテストしたときはインストールできていた記憶があります。
どうぞよろしくお願いいたします。

**Comment by kou** [comment]
RHEL 8向けのPostgreSQL 10用のパッケージは提供していないのでPostgreSQL 12か13を使ってください。

2020年7月頃に動いたときはRHEL 7を使っていたりしませんか？

ちなみに https://packages.groonga.org/centos/latest/ は気にしないでください。いまだに https://packages.groonga.org/centos/6/ を指していてぜんぜんlatestじゃないんです。。。

**Comment by usaken** [comment]
早速返信くださり、ありがとうございました。
そうなんですね・・・、クライアントと相談してみます。
7月のときもRHEL8でした。VirtualBoxでテストしてイメージがまだ残っておりましたので・・・。

**Comment by kou** [comment]
そのイメージで`dnf info postgresql10-pgroonga`するとどうなりますか？

**Comment by usaken** [comment]
お手を煩わせてすみません。どうも私の勘違いだったようです。
historyを除いたら、たくさんコマンドをうって試行錯誤した形跡が残っていて、最終的に以下のようにしてテストを終了したようでした。

```
#  yum install https://packages.groonga.org/centos/latest/x86_64/Packages/postgresql10-pgroonga-2.2.6-1.el6.x86_64.rpm
```

dnf infoの出力は下記です。

```
インストール済みパッケージ
名前         : postgresql10-pgroonga
バージョン   : 2.2.6
リリース     : 1.el6
Arch         : x86_64
サイズ       : 1.4 M
ソース       : postgresql10-pgroonga-2.2.6-1.el6.src.rpm
リポジトリー : @System
repo から    : @commandline
概要         : Fast full-text search plugin for PostgreSQL based on Groonga
URL          : https://pgroonga.github.io/
ライセンス   : PostgreSQL
説明         : This package provides a fast full-text search plugin for
             : PostgreSQL. It is based on Groonga.
```

この方法ですと、アップデートがあっても自動インストールできないですよね。

**Comment by kou** [comment]
それはそもそもRHEL6用にビルドされたものなのでちゃんと動くかどうか自体疑わしいです。

**Comment by usaken** [comment]
承知しました。親切に教えてくださり、ありがとうございました。
クライアントと相談してみます。
