### ISSUE TITLE
PGroongaを使用した更新性能についての質問

### ISSUE THREAD

**Issue by BiscuitsColonel** [pgroonga/pgroonga#162]
お世話になっております。
質問が3点御座います。

1. PGroongaのWALファイルの容量に因る、更新処理の劣化について
　PGroongaを使用した時の更新処理について質問があります。
　PGroongaのWALファイルの容量が1GB以上溜まった状態で更新処理を行なった場合、
　更新処理に遅延などの性能劣化が見られることはあるのでしょうか。
　また性能劣化がある場合、どのような要因が考えられるでしょうか。

2. PGroongaインデックスクラッシュ時の動作に関して
　PGroongaインデックスが何らかの要因によりクラッシュしている状態で更新処理が実行
　された場合はどのような動作が実行されるのでしょうか。(正常に実行はされる、エラーが発生する、実行されるが不正な結果となる、など)
　また、正常に実行される場合でも更新処理が長くなるなどの性能劣化はあるのでしょうか

3. PREPAERD文を作成した際のPGroongaインデックスの動きに関して
　PGroongaインデックスを設定しているテーブルに対して通常の処理時間が数msで完了する
　UPDATE文を prepared→executeとした際に、 preparedの処理で数十秒の実行時間が
　発生しました。
　このpreparedの処理時間はPGroongaインデックスがPREPARED文作成時に何らかの処理を
　行っているからでしょうか。

以上3点、よろしく御願い致します。
質問の内容に関しまして、ご不明な点やより詳細な情報が必要という場合はお手数ですが
ご連絡いただければと思います。

**Comment by kou** [comment]
1. PostgreSQLは1GBごとにファイルを分けるのでそれのせいかもしれません。 https://www.postgresql.jp/document/12/html/storage-file-layout.html
2. 更新ロックを解放する前にクラッシュした場合は再度ロックを獲得しようとして長時間ロック待ちになります。ロックが残留していない場合はなにも壊れていない可能性があります。
3. PREPAREDのときにPGroongaになにかの処理がリクエストされているかは実験しないとわからないです。

**Comment by BiscuitsColonel** [comment]
ご回答いただきありがとう御座います。

最初の質問に関しまして、PostgreSQLは1GBごとにファイルを分けるという機能について理解することができました。
実際に確認したところ、PGroongaWALファイルが『.1、.2』というように複数に分割
されていました。
上記の内容を踏まえて1点確認したいことがございます。
このようにPGroongaWALファイルが増えていった場合に更新処理の性能に影響を
与えるようなことはないのでしょうか。

**Comment by kou** [comment]
うーん、実験しないとわからないです。
ストレージの性能にも関わってきそうな気はします。

**Comment by BiscuitsColonel** [comment]
ご回答のほど、有難うございます。
何度もすみません。
念のため、追加で確認させてください。
PostgreSQL ではファイルが肥大化（分割）に伴い、（テーブル内のデータ件数にかかわらず）シーケンシャルスキャンの性能が劣化していきます。
PGroongaの更新やWAL適用処理でも、同じ挙動となるかどうかは検証してみないと分からないという認識でよろしいでしょうか。
例えば、PGroongaWALファイルのサイズが10MBの場合と1GB以上の場合では、pgroonga_wal_applyやpgroonga_wal_vacuumの実行速度は前者（10MB）の方が速い、かどうかは検証してみないと分からないという認識で問題ないでしょうか。

ご確認させていただきたいことは、PGroongaWALファイルの適用時に
「先頭からPGroongaWALファイルをシーケンシャルに読み込む」のか、それとも、
「最後に適用されたPGroongaWALの位置からPGroongaWALファイルを読み込む」のか、どちらの仕組みになっているのかということになります。

**Comment by kou** [comment]
PGroongaのWALの適用は「最後に適用されたPGroongaWALの位置からPGroongaWALファイルを読み込む」です。

`pgroonga_wal_truncate`は適用済みの位置に関わらずすべてのファイルクリアーします。

**Comment by BiscuitsColonel** [comment]
お忙しい中ありがとうございました。
PGroongaを使用した更新性能について理解ができたのでクローズさせていただきます。
