### ISSUE TITLE
similar search available only in index scan

### ISSUE THREAD

**Issue by oyhan** [pgroonga/pgroonga#163]
Hi 
I'm using pgroonga and PostgreSQL 12.5 
I have a table with 2 Indexed column names "Title" and "Description"
They are both indexed with pgroonga
but when I ran this query :
`SELECT * FROM "Reviews" WHERE "Title"  &@* 'بو';`
the debugger says :
```text
ERROR:  pgroonga: similar search available only in index scan
SQL state: 0A000
```

And when add the EXPLAIN keyword :

```text
Seq Scan on ""Reviews""  (cost=10000000000.00..10000000001.76 rows=1 width=188)
  Filter: (""Title"" &@* 'بو'::text)
JIT:
  Functions: 4
  Options: Inlining true, Optimization true, Expressions true, Deforming true
```

Unfortunately PostgreSql uses "Seq Scan to run the query even when I execute 
`SET enable_seqscan = OFF;
` 

For other column ("Description") it will be OK only when I run SET enable_seqscan = OFF;

Im new in PostgreSQL and pgroonga 
Thanks for your tips

**Comment by kou** [comment]
Could you show the table schema of `Reviews`?

**Comment by kou** [comment]
I think that `Title` is `varchar` not `text`.

**Comment by oyhan** [comment]
> Could you show the table schema of `Reviews`?

Hello
Here you are :
![Screenshot 2020-12-14 114645](https://user-images.githubusercontent.com/23168036/102056790-249c1e80-3e02-11eb-8284-189a539d3838.png)

**Comment by oyhan** [comment]
> I think that `Title` is `varchar` not `text`.

No I've checked this either

**Comment by kou** [comment]
> ```text
>     ("Title" COLLATE pg_catalog."default" pgroonga_varchar_full_text_search_ops_v2)
> ```

Why did you specify `pgroonga_varchar_full_text_search_ops_v2` for `text` column?
You should use the default operator class for `Reviews.Title` to use similar search.

**Comment by oyhan** [comment]
> > ```
> >     ("Title" COLLATE pg_catalog."default" pgroonga_varchar_full_text_search_ops_v2)
> > ```
> 
> Why did you specify `pgroonga_varchar_full_text_search_ops_v2` for `text` column?
> You should use the default operator class for `Reviews.Title` to use similar search.

I didn't do that. The model builder did it. Anyway, I've removed the and re-reacted the index from the beginning.
You can follow another[ issue](https://github.com/JoyMoe/PGroonga.EntityFrameworkCore/issues/4) I have created for my problem which was directly related to the library I'm using.
It seems PostgreSQL prefers sequential scan despite the Pgroonga indexed column!And I should turn of the `enable_seqscan` to make it work. The weird thing is it won't work either with `enable_seqscan=off` and EXPLAIN shows it's using sequential scan again.
The problem still exists

**Comment by kou** [comment]
Could you show the current `Reviews` definition?

**Comment by oyhan** [comment]
> Could you show the current `Reviews` definition?


`CREATE TABLE public."Reviews"
(
    "Id" uuid NOT NULL,
    "LastModifiedDate" timestamp without time zone NOT NULL,
    "CreatedDate" timestamp without time zone NOT NULL,
    "Rate" integer NOT NULL,
    "Title" text COLLATE pg_catalog."default",
    "PlaceId" uuid NOT NULL,
    "DateVisited" timestamp without time zone NOT NULL,
    "PlaceName" text COLLATE pg_catalog."default",
    "UserId" text COLLATE pg_catalog."default",
    "Description" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Reviews" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Reviews_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES public."AspNetUsers" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT,
    CONSTRAINT "FK_Reviews_Places_PlaceId" FOREIGN KEY ("PlaceId")
        REFERENCES public."Places" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE public."Reviews"
    OWNER to postgres;
-- Index: IX_REVIEWS_TITLE

-- DROP INDEX public."IX_REVIEWS_TITLE";

CREATE INDEX "IX_REVIEWS_TITLE"
    ON public."Reviews" USING pgroonga
    ("Title" COLLATE pg_catalog."default")
    TABLESPACE pg_default;
-- Index: IX_Reviews_Description

-- DROP INDEX public."IX_Reviews_Description";

CREATE INDEX "IX_Reviews_Description"
    ON public."Reviews" USING pgroonga
    ("Description" COLLATE pg_catalog."default")
    TABLESPACE pg_default;
-- Index: IX_Reviews_PlaceId

-- DROP INDEX public."IX_Reviews_PlaceId";

CREATE INDEX "IX_Reviews_PlaceId"
    ON public."Reviews" USING btree
    ("PlaceId" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: IX_Reviews_UserId

-- DROP INDEX public."IX_Reviews_UserId";

CREATE INDEX "IX_Reviews_UserId"
    ON public."Reviews" USING btree
    ("UserId" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;`

**Comment by kou** [comment]
Could you provide `pg_dump` output that reproduces your case?

**Comment by oyhan** [comment]
> Could you provide `pg_dump` output that reproduces your case?

Can you guide me on how to do that. As I said I'm new to pg

**Comment by kou** [comment]
```bash
pg_dump ${DB_NAME} | gzip > dump.sql.gz
```

**Comment by oyhan** [comment]
[mahoor_dump.zip](https://github.com/pgroonga/pgroonga/files/5694491/mahoor_dump.zip)
Look is it OK

**Comment by kou** [comment]
Did you really use `pg_dump ${DB_NAME}`? Did you specify some options to `pg_dump`?

**Comment by oyhan** [comment]
I used pgadmin 4 to make it.Cause Im using docker . Let me make another

**Comment by oyhan** [comment]
[dump.sql.gz](https://github.com/pgroonga/pgroonga/files/5694636/dump.sql.gz)
This is exactly what you want

**Comment by kou** [comment]
Umm... It's not gziped raw SQL... It uses the same format as https://github.com/pgroonga/pgroonga/issues/163#issuecomment-745146753 ...

Both of them don't include table definitions. They only have data.

**Comment by oyhan** [comment]
[dump2.sql.gz](https://github.com/pgroonga/pgroonga/files/5694823/dump2.sql.gz)
Forgive me my friend!
Check this one.I think it's ok now :(

**Comment by kou** [comment]
Thanks. Finally, I can reproduce your case on local.

`explain select * from public."Reviews" where "Title" &@* 'بو';` uses sequential scan by default but it uses index scan with `set enable_seqscan = no;`. Is this same as your status?

`Reviews` only have two records. If you add more records, PostgreSQL will use index scan without `set enable_seqscan = no`.

Or you can increase sequential scan cost by the following SQL:

```sql
ALTER FUNCTION pgroonga_similar_text(text, text) COST 1000000;
```

If you increase sequential scan cost, PostgreSQL will use index scan without `set enable_seqscan = no` even when you only have two records.

**Comment by oyhan** [comment]
> `explain select * from public."Reviews" where "Title" &@* 'بو';` uses sequential scan by default but it uses index scan with `set enable_seqscan = no;`. Is this same as your status?

Yeah partially. Sometimes even with   `set enable_seqscan = no;` has no benefit.
> 
> `Reviews` only have two records. If you add more records, PostgreSQL will use index scan without `set enable_seqscan = no`.
> 
My first guess was this but I tested with another table with only one record and pg was using index scan on that table! So I ignored it.
The only difference was that I was creating the test table with a very simple structure (an id and a text column) this was confusing.
> Or you can increase sequential scan cost by the following SQL:
> 
> ```sql
> ALTER FUNCTION pgroonga_similar_text(text, text) COST 1000000;
> ```
> 
> If you increase sequential scan cost, PostgreSQL will use index scan without `set enable_seqscan = no` even when you only have two records.

Thank you very much I'm eagerly going to examine your prescription 👍

**Comment by oyhan** [comment]
Thanks, @kou for your time. It's Ok now. But one more question. Is it possible that increasing in sequential scan cost have side effects on performance or other things I don't know?

**Comment by kou** [comment]
Nothing.
You can safely do it because similar search doesn't work with sequential scan.
