### ISSUE TITLE
「pgroonga_vacuum」のエラーについて

### ISSUE THREAD

**Issue by BiscuitsColonel** [pgroonga/pgroonga#168]
お世話になっております。
「pgroonga_wal_truncate」についての修正の件、ありがとうございました。
お手数でなければどのような原因だったのかを簡単に教えていただけると嬉しいです。

PGroongaはPostgreSQLの拡張の中でも最も早い全文検索モジュールですので、現在もテストを続けております。
その中で再度、PGroongaにおけるエラーメッセージを確認したため、ご質問させていただきます。

「pgroonga_vacuum」を実行したところ、下記のエラーが発生いたしました。

ERROR: pgroonga: failed to remove: : [column][remove][index] hook has a dangling reference: <Sources17848366.freeword_text> -> <>
CONTEXT: SQL statement "SELECT pgroonga_vacuum()"

「HOOKの参照が残っている」というエラーメッセージのようですが、この状態から「pgroonga_vacuum」を成功させるにはどのような対応が必要か、どういった原因なのかを教えていただけますか。

ストリーミング環境のスレーブでのみ発生いたしました。
詳しくどういった状況で、どのような手順を行った時に起きた現象なのか情報が必要な場合は、お申し付けくださいませ。

以上、よろしくお願いいたします。

**Comment by kou** [comment]
処理の間ずっとPostgreSQLのバッファーというデータに対するロックを獲得していてPostgreSQLのロック数の上限に達したことが原因でした。WAL量が少ない場合は発生しません（上限に達しません）が、多い場合は発生します。随時ロックを開放するようにして修正しました。

そのエラーはDBが壊れているとき（あるいはGroongaがバグっているとき）に出るのですが、そのスレーブはクラッシュしたことがありますか？
また、再現性はありますか？再現性があるなら再現手順を共有してもらえますか？

なお、この状況からの復旧方法は`*.pgrn`ファイルの削除→`REINDEX`です。
参考：https://pgroonga.github.io/ja/reference/functions/pgroonga-database-remove.html

**Comment by BiscuitsColonel** [comment]
早速のご回答ありがとうございます。

>処理の間ずっとPostgreSQLのバッファーというデータに対するロックを獲得していてPostgreSQLのロック数の上限に達したことが原因でした。WAL量が少ない場合は発生しません（上限に達しません）が、多い場合は発生します。随時ロックを開放するようにして修正しました。

とても勉強になりました！ありがとうございます。

>そのエラーはDBが壊れているとき（あるいはGroongaがバグっているとき）に出るのですが、そのスレーブはクラッシュしたことがありますか？

おそらくクラッシュしていないとは思いますが、ログを見て確認いたします。

>また、再現性はありますか？再現性があるなら再現手順を共有してもらえますか？

再現性は今のところないように思えます。スレーブを3台にしてテストを行なっているのですが、同様の手順を行なっても他2サーバではこの現象は発生しておりません。

1 点追加で確認させてください。
今回は「Sources17848366」が原因となっていることがエラーメッセージから読み取れます。
SELECT pgroonga_command('table_list');で取得した結果から「Sources17848366」に対応するpgrnファイルを特定し、そのpgrnファイルを削除したのち、REINDEX INDEX target_index; することで、現象が解決するのでしょうか。
それとも全てのpgrnファイルを削除したのち、全てのPGroongaインデックスに対してREINDEXが必要でしょうか。

**Comment by kou** [comment]
うーん、こんどはその対応する`pgrn`ファイルがないというエラーになる気がします。

どうしても`pgrn*`を削除したくないのであれば`SELECT pgroonga_command('object_remove', ARRAY['name', 'pgrn.XXX', 'force', yes'])`みたいな感じで削除できるとは思いますが、ゴミが残るかもしれません。

参考： https://groonga.org/ja/docs/reference/commands/object_remove.html

**Comment by BiscuitsColonel** [comment]
ご回答ありがとうございます。
こちらの方で復旧手順について色々試してみよう思います。
pgrn*をすべて消す（pgroonga_database_removeを使う）方向で、一旦は考えるようにいたします。
