### ISSUE TITLE
PostgreSQL上のAuto Vacuum処理でのpgroonga_vacuum()関数の動作について

### ISSUE THREAD

**Issue by BiscuitsColonel** [pgroonga/pgroonga#177]
お世話になっております。

PostgreSQLによるAuto Vacuum時にもpgroonga_vacuum()は実行されますでしょうか？
その場合は、Auto Vacuumのどのタイミングでpgroonga_vacuum()が行われますか？
また、Auto Vacuumが途中でキャンセルされた場合はpgroonga_vacuum()はどうなるのでしょうか？

以上、よろしくお願いいたします。

**Comment by komainu8** [comment]
PostgreSQLのvacuum、autovacuum時は、 `pgroonga_vacuum()` が実行されるわけではなく、別の関数を通ります。

`pgroonga_vacuum()`が実行された場合は、 https://github.com/pgroonga/pgroonga/blob/master/src/pgrn-vacuum.c#L11 が実行されますが、 PostgreSQLのvacuum、autovacuum時は https://github.com/pgroonga/pgroonga/blob/master/src/pgroonga.c#L6950 が実行されます。

`PGrnRemoveUnusedTables()`で不要なテーブルを削除しているのは同じですが、 https://github.com/pgroonga/pgroonga/blob/master/src/pgroonga.c#L6950 の場合は、PostgreSQLに統計情報を返す点が異なります。

Auto Vacuumが途中でキャンセルされた場合は、実行前の状態にロールバックされます。
PostgreSQLは、`BEGIN`で明示的にトランザクションブロックを作らない場合は、各SQL文ごとに固有のトランザクションを持ち、SQL文が完了すると、自動で変更がコミットされるため、SQLの実行中に中断された場合は、トランザクション開始前の状態(つまりコマンド実行前の状態)にもどります。

https://www.postgresql.jp/document/12/html/sql-begin.html

**Comment by BiscuitsColonel** [comment]
詳細にありがとうございます。
とてもよく理解ができました！
