### ISSUE TITLE
Build for Debian bullseye?

### ISSUE THREAD

**Issue by timabbott** [pgroonga/pgroonga#180]
Hi!  Would it be possible to start building Pgroonga for Debian Bullseye?  Bullseye is mostly frozen at this point (https://release.debian.org/bullseye/freeze_policy.html), and we're working on adding Zulip support for it, and it'd be nice to use official packages rather than building from source.

**Comment by kou** [comment]
OK.
We'll do.

**Comment by kou** [comment]
Done. Could you try https://pgroonga.github.io/install/debian.html#install-on-bullseye ?

**Comment by timabbott** [comment]
Thanks @kou!  Will do.

**Comment by ligmitz** [comment]
Thanks @kou. This seems to work well.

**Comment by kou** [comment]
That's good to hear.

**Comment by ligmitz** [comment]
@kou We are facing an issue regarding the installation of `postgresql-13-pgdg-groonga` on the `Debian bullseye` (can be seen [here](https://github.com/zulip/zulip/pull/17951/checks?check_run_id=2335602682)). It seems like the the package has a build for the `arm64` architecture but not for others. Is it possible to get the build for other architectures as well soon ?

**Comment by kou** [comment]
Oh, sorry. I've uploaded. Could you try again?

**Comment by ligmitz** [comment]
Thanks for the quick response. Actually this shoots another error:
```bash
The following packages have unmet dependencies:
 postgresql-13-pgdg-pgroonga : Depends: libgroonga0 (>= 11.0.1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
Is this related and whats a potential solution ? I tried installing `libgroonga=11.0.1` but it gives package not found error.

**Comment by kou** [comment]
Sorry... I'm uploading libgroonga0-11.0.0...

**Comment by kou** [comment]
Done.

**Comment by ligmitz** [comment]
Thanks, its working now.
