### ISSUE TITLE
No way to change normalizer without setting in index

### ISSUE THREAD

**Issue by kjifs** [pgroonga/pgroonga#182]
I'm trying to use pgroonga, but have noticed some strange behaviour. The `&@~` operator returns different results based on whether or not I have an index on the column, and it seems to be because with an index it uses the tokenizer `TokenBigram` and normalizer `NormalizerAuto`, and without an index it uses the same tokenizer but doesn't use a normalizer. Is there a way to make queries on non-indexed columns use `NormalizerAuto`?

Example showing that the behaviour is different:
```
search=# select * from test;
 txt
------
 One
 None
(2 rows)
search=# select * from test where txt &@~ 'One';
 txt
------
 One
 None
(2 rows)
search=# create index on test using pgroonga(txt);
CREATE INDEX
search=# select * from test where txt &@~ 'One';
 txt
-----
 One
(1 row)
```

The behaviour I want is the second one, where the normalizer is being used so this acts as full text search rather than substring search, but for various reasons I can't have an index present on certain columns that I want to use this operator on.

**Comment by kou** [comment]
You can create a dummy index.

**Comment by kjifs** [comment]
So the answer then is that an index of some sort is required, then, and we cannot specify a tokenizer/normalizer without one. Thanks.
