### ISSUE TITLE
Build postgresql-11-pgdg-pgroonga package?

### ISSUE THREAD

**Issue by timabbott** [pgroonga/pgroonga#184]
Hi!  Would it be possible to provide a ``postgresql-11-pgdg-pgroonga package for Ubuntu Bionic?  I notice builds for 10, 12, and 13 for the PGDG packages, and it'd be useful for Zulip to have a package for Postgres 11 as well.

We can potentially work around it by using a newer Postgres version, but if it's easy, it'd certainly help to have a Postgres 11 build.

```
# apt search pgroonga
Sorting... Done
Full Text Search... Done
postgresql-10-pgdg-pgroonga/bionic 2.3.0-1 amd64
  Fast full-text search plugin for PostgreSQL based on Groonga

postgresql-10-pgroonga/bionic 2.3.0-1.ubuntu18.04.1 amd64
  Fast full-text search plugin for PostgreSQL based on Groonga

postgresql-12-pgdg-pgroonga/bionic 2.3.0-1 amd64
  Fast full-text search plugin for PostgreSQL based on Groonga

postgresql-13-pgdg-pgroonga/bionic 2.3.0-1 amd64
  Fast full-text search plugin for PostgreSQL based on Groonga

```

The background is that we're hoping to make it possible to use PGroonga in Zulip Cloud in the somewhat near future.

**Comment by kou** [comment]
OK. We'll do.

**Comment by kou** [comment]
Done!

**Comment by timabbott** [comment]
Awesome, thanks so much!

**Comment by alexmv** [comment]
Thanks for the quick turn-around on the Bionic package!  Can we also get this built for Focal?

**Comment by kou** [comment]
OK. We'' do.

**Comment by kou** [comment]
Done!

**Comment by alexmv** [comment]
Thank you!
