### ISSUE TITLE
Red Hat Enterprise Linux 8 

### ISSUE THREAD

**Issue by akimotokatsuhiro** [pgroonga/pgroonga#189]
Red Hat Enterprise Linux 8 にインストールする場合でインターネットに接続できない状態の場合の
インストール手順を教えてください。

**Comment by kou** [comment]
その環境にインターネットからダウンロードしたファイルはコピーできますか？

**Comment by akimotokatsuhiro** [comment]
返事ありがとうございます。
直接インターネットに接続が出来ません。
PostgreSQとPGroongaもモジュールのダウンロードが必要です。
やりたい方法はISOファイルをマウントしてPgroongaモジュールのインストールです。

**Comment by komainu8** [comment]
承知しました。
必要なもの一式をダウンロードするスクリプトを用意しますので、それを使って必要なものをダウンロードしてCD-Rに焼いて該当のマシンへインストールしてみてください。

スクリプトは明日くらいには用意できると思います。

**Comment by akimotokatsuhiro** [comment]
komainu8さん、ありがとうございます。
明日お待ちしております。

**Comment by akimotokatsuhiro** [comment]
PGroongaのインストール情報にて実施しましたありがとうございます。
PGroongaのパラメータシートはどこかに記載されておりますでしょうか？

**Comment by akimotokatsuhiro** [comment]
本当にありがとうございました。

**Comment by akimotokatsuhiro** [comment]
今更ですが、以下の3点のインストールが上手く行きません。
依存性の欠如が出てしまいます。うまくかわせる方法はありませんか？

arrow-libs-5.0.0-1.el8.x86_64.rpm
groonga-libs-11.0.7-1.el8.x86_64.rpm
postgresql14-pgdg-pgroonga-2.3.2-1.el8.x86_64.rpm
＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
-rw------- 1 root root 4571868 11月  5 19:30 arrow-libs-5.0.0-1.el8.x86_64.rpm
-rw------- 1 root root 2483116 10月  8 10:05 groonga-libs-11.0.7-1.el8.x86_64.rpm
-rw------- 1 root root  546976 10月  8 10:05 postgresql14-pgdg-pgroonga-2.3.2-1.el8.x86_64.rpm
[root@build1009353 groonga]# rpm -Uvh ./*.rpm
警告: ./arrow-libs-5.0.0-1.el8.x86_64.rpm: ヘッダー V4 RSA/SHA256 Signature、鍵 ID 34839225: NOKEY
エラー: 依存性の欠如:
        libzstd は arrow-libs-5.0.0-1.el8.x86_64 に必要とされています
        libzstd.so.1()(64bit) は arrow-libs-5.0.0-1.el8.x86_64 に必要とされています
        libzstd は groonga-libs-11.0.7-1.el8.x86_64 に必要とされています
        libzstd.so.1()(64bit) は groonga-libs-11.0.7-1.el8.x86_64 に必要とされています
        postgresql14-server は postgresql14-pgdg-pgroonga-2.3.2-1.el8.x86_64 に必要とされています

**Comment by akimotokatsuhiro** [comment]
因みにEDBpostgresql13を使いたい場合は14は入れなくても大丈夫でしょうか？

**Comment by akimotokatsuhiro** [comment]
何度もすいませんインストールは上手う出来ました。が、EDBpostgresql13を使いたい場合は14は入れなくても大丈夫でしょうか？

**Comment by komainu8** [comment]
EDB Postgres Advanced Serverのバージョンが13なら、PostgreSQL 14は必要ないです。
EDB Postgres Advanced Server 13は、PostgreSQL 13を使うためです。

**Comment by akimotokatsuhiro** [comment]
その場合インストールは以下の4つだと思いますが
13用の「postgresql14-pgdg-pgroonga-2.3.2-1.el8.x86_64.rpm」RPMは有りますか

postgresql14-14.0-1PGDG.rhel8.x86_64.rpm
postgresql14-libs-14.0-1PGDG.rhel8.x86_64.rpm
postgresql14-server-14.0-1PGDG.rhel8.x86_64.rpm

**Comment by komainu8** [comment]
EDB Postgres Advanced Server 13は既にインストール済みですか？
もしそうなら、既にPostgreSQL 13は動作しているので、 postgresql13-pgdg-pgroonga-2.3.2-1.el8.x86_64.rpm だけインストールで良いと思います。(EDB Postgres Advanced Server 13は手元に無いので、試せてはいないですが。)

> 13用の「postgresql14-pgdg-pgroonga-2.3.2-1.el8.x86_64.rpm」RPMは有りますか
はい。あります。「postgresql13-pgdg-pgroonga-2.3.2-1.el8.x86_64.rpm」です。

**Comment by akimotokatsuhiro** [comment]
libc.so.6(GLIBC_2.34)(64bit)はlib64zstd1_1.5.0-3.x86_64の依存
が出ましたので他に必要なRPMがないかお教えください。

**Comment by komainu8** [comment]
PostgreSQL13はEDB13が入っているならあるはずですが、おそらくパッケージの名前が postgressql13-server ではないため、PGroongaインストール時に検出できないのではないかと推測していますが、PGroongaを始め、その他の外部拡張をEDB13で使う方法については、EDBのサポートにお尋ねいただくのが、速く、正確だと思います。

こちらではEDB13が手元にないので、インストールを試すことができないのと、EDB13の開発元ではないので、仕組みをいろいろ調べながらの回答になってしまいます。
そのため、EDBのサポートへご連絡頂いたほうが、速く、正確な回答が得られると思います。

**Comment by akimotokatsuhiro** [comment]
EDBへのサポートに関しては理解いたしました。
こちらとしては一旦、Pgroonga アンインストールしたいのでがアンインストール方法を
教えて頂けないでしょうか。

**Comment by kou** [comment]
インストールしたRPMをすべて削除してください。

**Comment by akimotokatsuhiro** [comment]
しつこくてすいません。
アンインストール後に何をもってアンインストール完了とするか？ですが
RPMをアンインストールしただけでEDB13が使えるようになりますか？

**Comment by kou** [comment]
もともと使えてPGroonga関連のRPMをインストールしたことによって使えなくなったのならPGroonga関連のRPMをアンインストールすれば使えるようになると思います。
もともと使えていなかったらPGroonga関連のRPMをアンインストールしても使えないままだと思います。

**Comment by akimotokatsuhiro** [comment]
https://pgroonga.github.io/ja/install/source.html#non-windows
上記に書かれている「Groongaの開発用パッケージ」とは何を指しているのでしょうか
お教えください。
rpm の場合はファイル名をお教えください。

**Comment by kou** [comment]
そのページに書いている`groonga-devel-XXX.rpm`です。

**Comment by akimotokatsuhiro** [comment]
はい、ありがとうございます。groonga-devel-11.0.9-1.el8.x86_64.rpmですね
インストール時に「依存性の欠如」が大量に
出るのですが何か固まってるRPMは無いのでしょうか？

**Comment by kou** [comment]
ありません。
依存関係も含めて簡単にインストールできるようにYumリポジトリーを提供しています。
インターネットに接続できない環境ではYumリポジトリーを使えませんが、そのような環境の場合は各ユーザーでがんばってください。
Groongaプロジェクト・PGroongaプロジェクトとしてはそのようなケースはサポートしません。

このケースについてこれ以上のサポートが必要な場合は有償のサポートサービスのご利用をご検討ください。
https://www.clear-code.com/services/groonga.html
