### ISSUE TITLE
Questions about cleaning pgroonga wal 

### ISSUE THREAD

**Issue by zyp-rgb** [pgroonga/pgroonga#199]
https://pgroonga.github.io/reference/functions/pgroonga-wal-truncate.html  

One of the suggestions in the doc says 
`You recreate PGroonga indexes periodically. PGroonga's WAL will be deleted at the next VACUUM.`

Which one does `recreate` means, `delete and create` or `reindex`? 

THANKS

**Comment by kou** [comment]
Both of them are OK.

**Comment by kou** [comment]
The latest PGroonga has one more option:

* https://pgroonga.github.io/reference/modules/pgroonga-wal-applier.html and https://pgroonga.github.io/reference/parameters/max-wal-size.html

**Comment by zyp-rgb** [comment]
> The latest PGroonga has one more option:
> 
>     * https://pgroonga.github.io/reference/modules/pgroonga-wal-applier.html and https://pgroonga.github.io/reference/parameters/max-wal-size.html

thanks a lot; I will close the issue
