### ISSUE TITLE
set table space GLOBALLY when we create pgroonga index

### ISSUE THREAD

**Issue by zyp-rgb** [pgroonga/pgroonga#206]
we can set index space one by one. Is there a way to set table space globally for pgroonga index? This would be very helpful for maintenance

**Comment by kou** [comment]
Can you use the default table space feature https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-DEFAULT-TABLESPACE for it?

**Comment by DeoLeung** [comment]
I think the idea is we could completely separate pgroonga related stuff(indexes) to another disk with ease.

default table space seems to put everything besides pgroonga there.
manually setting table space for every pgroonga index definitely works, however it will be best if we could configure it once and forget :) (hence no need for every app developer to remember adding this)

**Comment by kou** [comment]
Could you propose this to PostgreSQL https://lists.postgresql.org/ not PGroonga if you aren't satisfied with the current PostgreSQL features? This is out of scope of PGroonga.
