### ISSUE TITLE
pgroonga operator similar to plainto_tsquery

### ISSUE THREAD

**Issue by younes-alouani** [pgroonga/pgroonga#211]
Hello dear community, 

I have a table of records in Chinese. My users often use a sentence of 2 to 3 words for their search. 

For example: "深冻"

Does pgroonga have a similar operator to plainto_tsquery in postgresql? 

Where I could do a search like this: 

`SELECT * FROM records WHERE name plainto_tsquery '深冻';`

It looks like the statement bellow gives results : 
`SELECT * FROM records WHERE &@~  '深冻';`

While in the documentation, it's written that it works for one keyword only. 

Thanks for your help.

**Comment by kou** [comment]
> `SELECT * FROM records WHERE &@~ '深冻';`

This must work. Is there any problem with this?

> While in the documentation, it's written that it works for one keyword only.

Could you show the URL you referred? `&@~` works for multiple keywords not one keyword. `&@` is for one keyword.

**Comment by kou** [comment]
No response.
