### ISSUE TITLE
PPA for Ubuntu 22.04?

### ISSUE THREAD

**Issue by ReimuHakurei** [pgroonga/pgroonga#212]
The latest LTS version of Ubuntu, Ubuntu 22.04, was released on 21 April.

Are there plans to update the Groonga PPA with packages for the new version?

Thanks.

**Comment by kou** [comment]
Done.

BTW, we have the "Users" page in our official Web site: https://pgroonga.github.io/users/
If you're a PGroonga user, please consider sending your use case to us. :-)
https://pgroonga.github.io/users/#send-us-your-service-name
