### ISSUE TITLE
Support text[] for highlight

### ISSUE THREAD

**Issue by kenhys** [pgroonga/pgroonga#219]
# Problem

pgroonga_highlight_html only supports `text`.
https://pgroonga.github.io/reference/functions/pgroonga-highlight-html.html

# Actual

If it was applied to `text[]`, it fails (as you know, it was documented already)

```
ERROR: function pgroonga_highlight_html(text[], text[]) does not exist
```

# Expected

It may be useful if the highlight function is available for `text[]`.

Use case:

If the memo table notes column as `text[]`, search notes with `&@~` is ok because `&@~` supports `text[]`,
but if you want to highlight matched results,  pgroonga_highlight_html can't be used.

Thus, the following query work in the future.

```
SELECT pgroonga_highlight_html(notes, ARRAY['debian']) FROM memo WHERE notes &@~ 'debian';
```

**Comment by kou** [comment]
Implemented.
