### ISSUE TITLE
Latest pgroonga release doesn't install on trusty

### ISSUE THREAD

**Issue by timabbott** [pgroonga/pgroonga#22]
When trying to `create extension pgroonga` on Ubuntu Trusty using the official PPA, I get this error:

```
ERROR:  could not load library "/usr/lib/postgresql/9.3/lib/pgroonga.so": /usr/lib/postgresql/9.3/lib/pgroonga.so: undefined symbol: PGrnJSONBLookupPathsTable
ERROR:  schema "pgroonga" does not exist
```

@kou this is breaking the Zulip CI -- is this something you can do a release to fix in the next day?  Otherwise we'll probably have to remove pgroonga support from Zulip.

(As a sidenote, I encourage you folks to setup CI installing your packages on the various Ubuntu releases you support to avoid regressions like this)

**Comment by kou** [comment]
Oh... Sorry. I've released a bug fix version for Ubuntu Trusty. https://launchpad.net/~groonga/+archive/ubuntu/ppa/+build/10716297
It'll be available in an hour. Could you try it?

> (As a sidenote, I encourage you folks to setup CI installing your packages on the various Ubuntu releases you support to avoid regressions like this)

I've added CI target for PostgreSQL 9.3: https://travis-ci.org/pgroonga/pgroonga/jobs/158031221

**Comment by timabbott** [comment]
Yep, I can test that when the build finishes.  Thanks @kou!

**Comment by kou** [comment]
Now, the package is available. I've confirmed that `CREATE EXTENSION pgroonga` doesn't raise any error on Ubuntu Trusty.

Sorry for your inconvenience and thanks for your report!

**Comment by timabbott** [comment]
Yep, confirmed working on my end.  Thanks @kou!
