### ISSUE TITLE
Ubuntu 22.04向けのpgdgパッケージの提供

### ISSUE THREAD

**Issue by sousuke0422** [pgroonga/pgroonga#228]
現在、Ubuntu 22.04向けには`groonga-apt-source`のみが提供されており、`postgresql-13-pgdg-pgroonga`といったパッケージは提供されていないため、自分でビルドするか、リスクを承知の上で旧バージョン向けUbuntuのものを使用する必要があり、簡単に導入することができません。

**Comment by komainu8** [comment]
@sousuke0422 こちらPGroonga 2.4.0からUbuntu 22.04向けのpgdgパッケージを提供しましたので、お試しいただければと思います！
