### ISSUE TITLE
how define a nested-index on PGroonga?

### ISSUE THREAD

**Issue by ajaxsys** [pgroonga/pgroonga#26]
Hi, i see groonga support nested different table column to one index:

see:
http://groonga.org/docs/tutorial/match_columns.html#nested-index-search
http://groonga.org/ja/docs/tutorial/match_columns.html#nested-index-search

but , how can i defined an index like this in PGroonga?

I tried the way like this but not working:

`CREATE INDEX pgroonga_nested_index ON table1, table2 USING pgroonga (table1.col, table2.col);`

Thanks for any advises.

**Comment by kou** [comment]
You can't use nested index on PGroonga because of PostgreSQL (SQL) restriction.

**Comment by kou** [comment]
Use `JOIN`. It's SQL way.
