### ISSUE TITLE
ci packages: use the latest released archive

### ISSUE THREAD

**Issue by HashidaTKS** [pgroonga/pgroonga#262]
`linux` job uses not the latest released archive but the latest Groonga repository.

https://github.com/pgroonga/pgroonga/blob/master/.github/workflows/package.yml#L88

I will fix it in another PR.

_Originally posted by @HashidaTKS in https://github.com/pgroonga/pgroonga/pull/260#discussion_r1029001407_

**Comment by kou** [comment]
It seems that it's just used for `packages/pgroonga-package-task.rb`. So we can use the Groonga repository.
