### ISSUE TITLE
pgroonga 2.4.1 ci with vacuum fix, still fails with 58000: pgroonga: failed to create column: <index>: system error[80]: The file exists.: CreateFile(<base/17727/pgrn.00004F3.c>, <O_RDWR|O_CREAT|O_EXCL>) failed

### ISSUE THREAD

**Issue by rwasef1830** [pgroonga/pgroonga#269]
Hello,
The fix for vacuum seems incomplete or caused another regression. I tested with CI of commit 60b820908b6413a8cb761a6ef64b349d8d12e50c. My application does all commits as 2 phase commits, so there's always a prepared transaction saved. maybe now due to this groonga is not deleting old files at all, leading to this error.

I will work on steps to reproduce issue.

**Comment by rwasef1830** [comment]
More information (will keep updating this message as more info is gathered).

- The error happened on CREATE INDEX statement.

**Comment by kou** [comment]
Could you share your `pgroonga.log`?

**Comment by rwasef1830** [comment]
Certainly I apologize for not sharing it from the start!

[pgroonga.zip](https://github.com/pgroonga/pgroonga/files/10099785/pgroonga.zip)

**Comment by kou** [comment]
It seems that `2022-11-28 01:46:53.990000|n|38572: DDL:1250:table_create JSONValues3781049_0`'s metadata was broken. It's a hash table but it's recognized as an index column on remove invoked by manual `VACUUM` at 2022-11-28 01:47:21. (Did you run `VACUUM` manually?)

Could you reproduce this with `pgroonga.log_level = debug`?
 https://pgroonga.github.io/reference/parameters/log-level.html
 
 It also shows IO related operations.

**Comment by rwasef1830** [comment]
@kou I encountered the error while development of a bulk data import script. I import a large amount of data and drop and create tables all in multiple prepared transactions and finally do a commit prepared in the end.

The error happened during development, when I stop the import script midway (leaving some prepared statements not committed), then I restart the application, which does a rollback of all prepared in the beginning and ran the script again. That's how I saw the error.

I set my pgroonga to dump level, and I'm trying to reproduce the issue, also with a repro script.

**Comment by rwasef1830** [comment]
> It seems that 2022-11-28 01:46:53.990000|n|38572: DDL:1250:table_create JSONValues3781049_0's metadata was broken. It's a hash table but it's recognized as an index column on remove invoked by manual VACUUM at 2022-11-28 01:47:21. (Did you run VACUUM manually?)

How does pgroonga generate the target file name ? And what are the situations that cause the creation of a new file ? Maybe there's a filename collision of some kind and it's generating the same file name for 2 objects ?

**Comment by rwasef1830** [comment]
@kou There seems to be random metadata corruption issue, maybe data racing or memory corruption issue. I started to repeat the same steps that led to the error I reported multiple times quickly, insert, then cancel midway, then delete, then insert quickly in succession, and I got a new error in VACUUM ANALYZE:

pgroonga: failed to remove: <JSONValues3814338_0>: column has unsupported hooks, col=JSONValues3814338_0

This time I have pgroonga dump log, please find it, I hope this helps to identify:
[pgroonga.zip](https://github.com/pgroonga/pgroonga/files/10105611/pgroonga.zip)

**Comment by kou** [comment]
Could you create a way to reproduce this problem like https://github.com/pgroonga/pgroonga/issues/252#issuecomment-1317012771 ?

It seems that this is difficult to find a root cause of this problem without reproducing this problem on local.

> How does pgroonga generate the target file name ?

Groonga assigns a new unique ID for each object and uses it for the target file name such as `pgrn.${ID}`.
Unique IDs may be recycled when an unique ID is released (an object is removed).

> And what are the situations that cause the creation of a new file ? 

A new object is created.

**Comment by rwasef1830** [comment]
@kou I'm trying but not able to make the issue appear with repro script yet, even when repeating similar actions as the script. I will continue trying. It's not 100% repro, it seems it's timing related.

Have you checked the log ? It's showing full cycle from start to error, and multiple attempts of create/drop/insert with dump level. Any thoughts on it ?

**Comment by kou** [comment]
> Have you checked the log ?

Could you provide a PostgreSQL log too? I want to know what/when SQLs are executed with `pgroonga.log`.

> What is the circumstances that lead to ID reuse, is there a way to force ID re-use or guarantee ID reuse ?

It's deterministic. If we do the same operation with the same order, the same re-use cycle is happen.

**Comment by rwasef1830** [comment]
Ok I will enable full sql logging and try to re-create the issue again.

**Comment by rwasef1830** [comment]
Ok I backtracked in my application log file, and traced the exact sequence of operations that led to appearance of the exact error message I reported in this bug title. The sequence is from last to first:

error message:
pgroonga: failed to create column: <index>: system error[80]: The file exists.: CreateFile(<base/17727/pgrn.00004F3.c>, <O_RDWR|O_CREAT|O_EXCL>) failed

error <- insert <- blank delete <- proper delete <- proper insert of 1000 products (does nothing due to id match of previous insert) <- proper insert of 1000 products <- insert interrupted at inserting vendors <- insert interrupted at inserting vendors <- blank delete <- full delete <- insert interrupted at inserting vendors <- full delete <- full insert 1000 products

Sadly, the generated log files are 1.15 GB because they include 1000 products (random data) as well as file uploads.

I am trying to do it again, but with disabling of file uploads and with small amount of products to make the log files in a reasonable size.

**Comment by rwasef1830** [comment]
@kou sadly, the log is too complicated and i was not able to make into an easily executable single sql file because it contains multiple connections and complicated interactions.

However, here is pgroonga.log debug level, postgresql statement level logs in stderr and also json format and also DDL. I hope it can help you:

[repro-small.zip](https://github.com/pgroonga/pgroonga/files/10114143/repro-small.zip)

**Comment by rwasef1830** [comment]
@kou somehow i succeeded in making a situation that just by reindex database, pgroonga state is already corrupted and gives error on vacuum. I can send you full DB dump and pgroonga log in dump mode, but the files are big, can you give an email address so i can send with wetransfer ?

**Comment by kou** [comment]
Great!
Could you use `kou@clear-code.com`?

**Comment by rwasef1830** [comment]
Done just sent it.

**Comment by kou** [comment]
Received. Thanks.

But I couldn't reproduce this problem (on my Linux environment)...
If this is happen with only `REINDEX` and `VACUUM`, is it not related to 2 phase commits?

**Comment by rwasef1830** [comment]
It entered into this phase, after I got error in my normal cycles of insert/drop/vacuum of bulk data with 2 phase commit (example of this in the repro-small.zip file above). After it entered into this phase, it is stuck, REINDEX DATABASE does not cure it, it still gives error.

**Comment by rwasef1830** [comment]
Is there a way I can send you the binary metadata files of pgroonga directly ? will this be useful for you (to open inspect by groonga directly). How can I find them ?

**Comment by kou** [comment]
You can just share `pgrn*` files in data directory.

**Comment by rwasef1830** [comment]
@kou I have emailed with link to download 7-zip containing pgrn*.* binary files of affected database. Maybe you can transplant into your imported db or inspect directly. I hope this helps.

**Comment by kou** [comment]
Thanks. Downloading...

**Comment by rwasef1830** [comment]
is there any update on this ?

**Comment by kou** [comment]
Ah, sorry. I tried but I didn't have enough disk space. So I stopped it.
I'll try again after I allocate extra disk space.

**Comment by kou** [comment]
Could you also share the `pgroonga.log` of these `pgrn*`?

**Comment by rwasef1830** [comment]
I think the repro-small file above is the log of this binary file, sadly, due to deadline, i was not able to wait for this issue and i was forced to switch from pgroonga back to pg_trgm and tsvector. I will try to find time to clone the project in its old state and repro the issue again, and collect logs and pgroonga.log again if the currently available is not sufficient.

I'm sorry.

**Comment by kou** [comment]
Ah, OK. I use the log.

**Comment by kou** [comment]
I got it. This is not related to two-phase commit. This is a problem of `VACUUM` in concurrent connections.

1. Connection1: `CREATE INDEX A`
2. Connection1: Groonga object A` (ID: 1000) is created
3. Connection1: `DROP INDEX A`
4. Connection1: (Groonga object A` (ID: 1000) isn't removed yet.)
5. Connection2: `VACUUM`
6. Connection2: Remove Groonga object A` (ID: 1000)
7. Connection2: `CREATE INDEX B`
8. Connection2: Groonga object B` (ID: 1000, reused) is created
9. Connection2: `DROP INDEX B`
10. Connection1: `VACUUM`
11. Connection1: Groonga object ID: 1000 is removed but its Groonga object A` not Groonga object B` because Groonga object A` is still open in connection1. This is the problem.
