### ISSUE TITLE
pgroonga indexes on ssd

### ISSUE THREAD

**Issue by pavelpopovgmail** [pgroonga/pgroonga#27]
I encountered a bug in my system with pgroonga indexes on SSD:
When i make update of data on one table, all the indexes in the tablespace, placed in that SSD are being corrupted. I try to use "io_flush" when updating the table and the indexes of the table are ok, but the indexes of the other tables on the same drive(TABLESPACE) stay corrupted. If i change the place of indexes on the SAS drive, all is ok.

My system is ubuntu with version:
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial

PostgreSQL version is 9.5.

**Comment by kou** [comment]
We need more information to solve this problem.

1. How did you decide that the indexes are corrupted?
2. Please show your `CREATE TABLE` and `CREATE INDEX`?
3. How to reproduce the problem?

**Comment by pavelpopovgmail** [comment]
Thank you for the quick response.

1. ERROR:  pgroonga: object isn't found: <Sources39061972>. When i do
REINDEX TABLE, the indexes work fine

2. CREATE TABLE lists.all (
      id        SERIAL NOT NULL,
      lst       varchar(10) NOT NULL,
      data      jsonb NOT NULL,
      fts       text NOT NULL,
    CONSTRAINT pk_lists_all PRIMARY KEY (id)) TABLESPACE disk4;--SAS
    --
    CREATE UNIQUE INDEX idx_lists_all_unique ON lists.all (lst,
(data->>'manager_idtype'), (data->>'manager_id'), (data->>'reg_dt'),
(data->>'state_dt')) TABLESPACE disk4;
    CREATE INDEX idx_lists_all_lst ON lists.all (lst) TABLESPACE disk4;
    CREATE INDEX idx_lists_all_fts ON lists.all USING pgroonga (fts)
TABLESPACE disk5;-- SSD
    CREATE INDEX idx_lists_all_activity ON lists.all ((data->>'activity'))
TABLESPACE disk4;
    CREATE INDEX idx_lists_all_typ ON lists.all ((data->>'typ')) TABLESPACE
disk4;
    CREATE INDEX idx_lists_all_branch_kid2008 ON lists.all
((data->>'branch_kid2008')) TABLESPACE disk4;

-----------------------
   CREATE TABLE idx.persons (
      id        SERIAL NOT NULL,
      ident     varchar(1001) NULL,
      identtype varchar(37) NULL,
      country   varchar(1001) NULL,
      lccountry varchar(1001) NULL,
      name      text NULL,
      lcname    text NULL,
      sortname  text NULL,
      person_id varchar(1001) NULL,
      content   text NULL,
      addr      text NULL,
      ep        text NULL,
      contacts  text NULL,
   CONSTRAINT pk_idx_persons PRIMARY KEY (id)) TABLESPACE disk4;

I have tuo types of indexes on that table:

CREATE INDEX idx_groonga_persons_ident ON idx.persons USING pgroonga (ident
pgroonga.varchar_full_text_search_ops) TABLESPACE disk5;

CREATE INDEX idx_groonga_persons_lcname ON idx.persons USING pgroonga
(lcname) TABLESPACE disk5;

Tablespace disk5 is placed on SSD and disk4 on SAS.

I do update of data on table "lists.all" and execute next query:
SELECT * FROM idx.persons WHERE lcname @@ lower('Александър боянов
константинов') order by sortname offset 0 limit 10
Right after that  it works, but after few seconds report  ERROR:  pgroonga:
object isn't found: <Sources39061972>

Data in tables are in cyrillic(utf-8).

3. I can to backup only these tables, but data in "idx.persons" is very
large.

Thanks again.

**Comment by kou** [comment]
Could you also show your `CREATE TABLESPACE`s?

**Comment by pavelpopovgmail** [comment]
CREATE TABLESPACE disk4 LOCATION '/mnt/disk4/pg';
CREATE TABLESPACE disk5 LOCATION '/mnt/disk5/pg';

And mount lines from fstab:
UUID=b6f4313d-a2e7-49ef-9e1a-fab338945228       /mnt/disk4      ext2
 relatime        0       1
UUID=447b0927-4035-4b47-a9a2-ff85c166e8ae      /mnt/disk5      ext4
 relatime        0       1

For SSD(disk5) i tried to change option to noatime and also tried sync and
discard.

This is info about the SSD drive:

=== START OF INFORMATION SECTION ===
Device Model:     TS240GSSD220S
Serial Number:    D067952518
Firmware Version: P0520AA
User Capacity:    240,057,409,536 bytes [240 GB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    Solid State Device
Device is:        Not in smartctl database [for details use: -P showall]
ATA Version is:   ACS-2 (minor revision not indicated)
SATA Version is:  SATA 3.1, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Fri Oct 28 08:12:51 2016 EEST
SMART support is: Available - device has SMART capability.
SMART support is: Enabled


I also tried on other SSD and the problem is the same:

=== START OF INFORMATION SECTION ===
Model Family:     Samsung based SSDs
Device Model:     Samsung SSD 850 EVO 120GB
Serial Number:    S21UNXAGA60950W
LU WWN Device Id: 5 002538 d40699691
Firmware Version: EMT02B6Q
User Capacity:    120,034,123,776 bytes [120 GB]
Sector Size:      512 bytes logical/physical
Rotation Rate:    Solid State Device
Device is:        In smartctl database [for details use: -P show]
ATA Version is:   ACS-2, ATA8-ACS T13/1699-D revision 4c
SATA Version is:  SATA 3.1, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Fri Oct 28 08:15:31 2016 EEST
SMART support is: Available - device has SMART capability.
SMART support is: Enabled


If i change indexes tablespace to disk4(SAS) all is ok.

**Comment by kou** [comment]
Thanks. I've fixed it.

It's caused by `CREATE INDEX ... USING pgroonga TABLESPACE xxx;`. If you drop `TABLESPACE xxx`, the problem isn't occurred.

FYI: PGroonga doesn't support tablespace yet. So `TABLESPACE xxx` is meaningless for now.

**Comment by pavelpopovgmail** [comment]
Thank you.
But the strange is, that when the tablespace is disk 4(SAS drive), the
problem disappear. I want to use SSD for fulltext indexes. Do you think,
that if i use SET default_tablespace=disk5(ssd), indexes will be working?

Otherwise I liked your search engine and i will try to use it in production.
Thank you again and good luck!

P.S.
When will I can install pgroonga for Postgresql-9.6 on my ubuntu 16.04?

**Comment by kou** [comment]
> But the strange is, that when the tablespace is disk 4(SAS drive), the problem disappear.

I think that `VACUUM` isn't executed in the case. You can reproduce it by calling `VACUUM` explicitly.

> Do you think, that if i use `SET default_tablespace=disk5(ssd)`, indexes will be working?

It doesn't work.

> Otherwise I liked your search engine and i will try to use it in production.

Thanks! If you use PGroonga in production, please send your case to [our users page](http://pgroonga.github.io/users/).

> When will I can install pgroonga for Postgresql-9.6 on my ubuntu 16.04?

We provide deb packages for PostgreSQL 9.6 on Ubuntu 16.04 when Ubuntu 16.04 ships PostgreSQL 9.6. (But Ubuntu 16.04 will not ship PostgreSQL 9.6...)

**Comment by kou** [comment]
Table space is supported at master.

**Comment by kou** [comment]
BTW,

```sql
SELECT * FROM idx.persons WHERE lcname @@ lower('...');
``

never use index defined as

```sql
CREATE INDEX idx_groonga_persons_lcname ON idx.persons USING pgroonga (lcname)`;
```

You need to define index with `lower(lcname)`:

```sql
CREATE INDEX idx_groonga_persons_lcname ON idx.persons USING pgroonga (lower(lcname))`;
```

**Comment by pavelpopovgmail** [comment]
The table field "lcname" is lowercased name. I use that table only for full
text indexing, not for real data. The database is more complicated.


What means "Table space is supported at master"?

**Comment by kou** [comment]
> What means "Table space is supported at master"?

The created index by `CREATE INDEX ... USING pgroonga ... TABLESPACE disk5;` is put to `disk5` location from the next release.

**Comment by pavelpopovgmail** [comment]
Ok, thanks!
