### ISSUE TITLE
PGroonga 2.4.3

### ISSUE THREAD

**Issue by HashidaTKS** [pgroonga/pgroonga#276]
- [x] NEWS
  - [x] Update news
  - [x] Translate news
- [ ] Prepare announcement text
  - [x] Blog https://github.com/groonga/groonga.org
    - [x] English
    - [x] Japanese
  - [ ] Announce
    - [ ] [GitHub Dicussions](https://github.com/pgroonga/pgroonga/discussions/categories/releases) (Japanese)
    - [ ] [GitHub Dicussions](https://github.com/pgroonga/pgroonga/discussions/categories/releases) (English)
    - [x] Twitter (Japanese/English)
    - [ ] Facebook (Japanese/English)
- [x] Check CI https://github.com/pgroonga/pgroonga/actions
- [x] Check Ubuntu build https://launchpad.net/~groonga/+archive/ubuntu/nightly/+packages
- [x] Tagging
- [x] Upload source archives (.tar.gz、.zip)
- [x] Upload packages
  - [x] Debian
  - [x] Ubuntu (launchpad)
  - [x] CentOS
  - [x] Windows
- [x] Upload documentation
- [x] Blog
  - [x] English
  - [x] Japanese
- [x] Announce
  - [x] [GitHub Dicussions](https://github.com/pgroonga/pgroonga/discussions/categories/releases) (Japanese)
  - [x] [GitHub Dicussions](https://github.com/pgroonga/pgroonga/discussions/categories/releases) (English)
  - [x] Twitter (Japanese/English)
  - [x] Facebook (Japanese/English)
  - [ ] PostgreSQL Announce (pgsql-announce@lists.postgresql.org)
- [x] Bump version for next release

**Comment by komainu8** [comment]
Announce for Twitter

---

PGroonga 2.4.3リリース! (2023-01-06) https://groonga.org/ja/blog/2023/01/06/pgroonga-2.4.3.html 今回のリリースでは、pgroonga_highlight_html() 関数のハイライト対象にtext[]型のカラムを指定できるようにしました！

PGroonga 2.4.3 has been released! (2023-01-06) https://groonga.org/en/blog/2023/01/06/pgroonga-2.4.3.html In this release, we can specify a column of text[] in the pgroonga_highlight_html()  function!

**Comment by komainu8** [comment]
パッケージのChnage logを更新。
CIの結果待ち。

**Comment by komainu8** [comment]
Ubuntu向けパッケージのビルド確認中。
https://launchpad.net/~groonga/+archive/ubuntu/nightly/+packages

**Comment by komainu8** [comment]
GitHub ActionsのUbuntuのテストが失敗しているが、これはまだGroongaのUbuntuパッケージが提供できる状態にないため。
時間をおいて再実行すれば直る。

**Comment by komainu8** [comment]
Ubuntu向けパッケージのビルドはパスした。

**Comment by komainu8** [comment]
CIをパスしたのでタグを打つ。

**Comment by komainu8** [comment]
タグを打った。
ソースアーカイブ、各パッケージの生成完了待ち。

**Comment by komainu8** [comment]
パッケージの署名、アップロードは完了。
アナウンスは明日実施。

**Comment by komainu8** [comment]
Docker image も更新済み。
