### ISSUE TITLE
[Feature request]: rocky 8 用のインストールパッケージ

### ISSUE THREAD

**Issue by xkwkmstr** [pgroonga/pgroonga#277]
### What is your problem?

OS rocky 8 用のインストールパッケージが欲しいです。
よろしくお願いします。

**Comment by kou** [comment]
AlmaLinux要パッケージを使えるはずです！

https://pgroonga.github.io/ja/install/almalinux.html

**Comment by xkwkmstr** [comment]
ありがとうございます。
