### ISSUE TITLE
pgroonga object isn't found

### ISSUE THREAD

**Issue by yongxianggao-chanjet** [pgroonga/pgroonga#29]
On MacBook, I see follow error since pgroonga-1.1.8 when I make a mvn build of a module called "common-test"

```text
ERROR:  pgroonga: object isn't found: <Sources366583664>
CONTEXT:  automatic analyze of table "common-test.csp_appdata.customer"
```

An interesting fact is that, this error shows up about 1 minute after the mvn build finishes.

**Comment by kou** [comment]
Could you show table and index definitions for `common-test.csp_appdata.customer`?
And could you show your PostgreSQL version?

**Comment by yongxianggao-chanjet** [comment]
postgreSQL version is 9.5.4_1
groonga version 6.1.1

table and index definition of common-test.csp_appdata.customer is as follows(from pgAdmin III):

-- Table: csp_appdata.customer

-- DROP TABLE csp_appdata.customer;

CREATE TABLE csp_appdata.customer
(
  id bigserial NOT NULL,
  address0 text,
  age0 bigint,
  banniversary0 csp_anniversary,
  category0 csp_multienum,
  city0 csp_dynenum,
  citycategory0 csp_cascadeenum,
  customerid0 text,
  customerinfo0 jsonb,
  dob0 date,
  geo0 geography(Point,4326),
  mvt0 timestamp(3) without time zone,
  multienum0 csp_multienum,
  name0 text,
  phoneoptout0 boolean,
  state0 csp_dynenum,
  statecity0 csp_cascadeenum,
  testkey0 text[],
  wanniversary0 csp_anniversary,
  wechatid0 character varying,
  weiboid0 character varying,
  audio0 csp_audioinfo,
  createdby bigint,
  email0 character varying,
  facebookid0 character varying,
  googleplusid0 character varying,
  image0 csp_imageinfo,
  lastmodifiedby bigint,
  linkedinid0 character varying,
  mobilephone0 character varying,
  ownerdepartment bigint,
  owner bigint,
  phone0 character varying,
  qqid0 character varying,
  revenue0 numeric,
  salestax0 numeric(11,4),
  twitterid0 character varying,
  uuid0 uuid,
  uri0 character varying,
  video0 csp_videoinfo,
  webpage0 text,
  yammerid0 character varying,
  createdbyentityid text NOT NULL,
  createddate timestamp(3) without time zone,
  customattributes jsonb,
  isdeleted boolean,
  isseeddata boolean,
  lastmodifieddate timestamp(3) without time zone,
  mobilelocalid bigint,
  permanentkey text[],
  version bigint,
  virtualschemaid bigint,
  CONSTRAINT customer_id_pkey PRIMARY KEY (id),
  CONSTRAINT customer_createdby_fkey FOREIGN KEY (createdby)
      REFERENCES csp_appdata."user" (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT customer_lastmodifiedby_fkey FOREIGN KEY (lastmodifiedby)
      REFERENCES csp_appdata."user" (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT customer_owner_fkey FOREIGN KEY (owner)
      REFERENCES csp_appdata."user" (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT customer_ownerdepartment_fkey FOREIGN KEY (ownerdepartment)
      REFERENCES csp_appdata.department (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT customer_customerid0_u UNIQUE (customerid0)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE csp_appdata.customer
  OWNER TO chanjetdev;

-- Index: csp_appdata.customer_address0_g

-- DROP INDEX csp_appdata.customer_address0_g;

CREATE INDEX customer_address0_g
  ON csp_appdata.customer
  USING pgroonga
  (address0 COLLATE pg_catalog."default" text_regexp_ops);

-- Index: csp_appdata.customer_address0_i

-- DROP INDEX csp_appdata.customer_address0_i;

CREATE INDEX customer_address0_i
  ON csp_appdata.customer
  USING pgroonga
  (id, address0 COLLATE pg_catalog."default");

-- Index: csp_appdata.customer_category0_i

-- DROP INDEX csp_appdata.customer_category0_i;

CREATE INDEX customer_category0_i
  ON csp_appdata.customer
  USING btree
  (category0);

-- Index: csp_appdata.customer_city0_i

-- DROP INDEX csp_appdata.customer_city0_i;

CREATE INDEX customer_city0_i
  ON csp_appdata.customer
  USING btree
  (city0);

-- Index: csp_appdata.customer_citycategory0_i

-- DROP INDEX csp_appdata.customer_citycategory0_i;

CREATE INDEX customer_citycategory0_i
  ON csp_appdata.customer
  USING btree
  (citycategory0);

-- Index: csp_appdata.customer_createdby_i

-- DROP INDEX csp_appdata.customer_createdby_i;

CREATE INDEX customer_createdby_i
  ON csp_appdata.customer
  USING btree
  (createdby);

-- Index: csp_appdata.customer_createdbyentityid_i

-- DROP INDEX csp_appdata.customer_createdbyentityid_i;

CREATE INDEX customer_createdbyentityid_i
  ON csp_appdata.customer
  USING btree
  (createdbyentityid COLLATE pg_catalog."default");

-- Index: csp_appdata.customer_custattrs_idx

-- DROP INDEX csp_appdata.customer_custattrs_idx;

CREATE INDEX customer_custattrs_idx
  ON csp_appdata.customer
  USING gin
  (customattributes);

-- Index: csp_appdata.customer_customerid0_f

-- DROP INDEX csp_appdata.customer_customerid0_f;

CREATE INDEX customer_customerid0_f
  ON csp_appdata.customer
  USING btree
  (csp_convert_to_pinyin(customerid0) COLLATE pg_catalog."default");

-- Index: csp_appdata.customer_customerid0_i

-- DROP INDEX csp_appdata.customer_customerid0_i;

CREATE INDEX customer_customerid0_i
  ON csp_appdata.customer
  USING btree
  (customerid0 COLLATE pg_catalog."default");

-- Index: csp_appdata.customer_customerinfo0_i

-- DROP INDEX csp_appdata.customer_customerinfo0_i;

CREATE INDEX customer_customerinfo0_i
  ON csp_appdata.customer
  USING gin
  (customerinfo0);

-- Index: csp_appdata.customer_geo0_i

-- DROP INDEX csp_appdata.customer_geo0_i;

CREATE INDEX customer_geo0_i
  ON csp_appdata.customer
  USING gist
  (geo0);

-- Index: csp_appdata.customer_lastmodifiedby_i

-- DROP INDEX csp_appdata.customer_lastmodifiedby_i;

CREATE INDEX customer_lastmodifiedby_i
  ON csp_appdata.customer
  USING btree
  (lastmodifiedby);

-- Index: csp_appdata.customer_mobilelocalid_i

-- DROP INDEX csp_appdata.customer_mobilelocalid_i;

CREATE INDEX customer_mobilelocalid_i
  ON csp_appdata.customer
  USING btree
  (mobilelocalid);

-- Index: csp_appdata.customer_multienum0_i

-- DROP INDEX csp_appdata.customer_multienum0_i;

CREATE INDEX customer_multienum0_i
  ON csp_appdata.customer
  USING btree
  (multienum0);

-- Index: csp_appdata.customer_owner_i

-- DROP INDEX csp_appdata.customer_owner_i;

CREATE INDEX customer_owner_i
  ON csp_appdata.customer
  USING btree
  (owner);

-- Index: csp_appdata.customer_ownerdepartment_i

-- DROP INDEX csp_appdata.customer_ownerdepartment_i;

CREATE INDEX customer_ownerdepartment_i
  ON csp_appdata.customer
  USING btree
  (ownerdepartment);

-- Index: csp_appdata.customer_permkey_idx

-- DROP INDEX csp_appdata.customer_permkey_idx;

CREATE INDEX customer_permkey_idx
  ON csp_appdata.customer
  USING gin
  (permanentkey COLLATE pg_catalog."default");

-- Index: csp_appdata.customer_state0_i

-- DROP INDEX csp_appdata.customer_state0_i;

CREATE INDEX customer_state0_i
  ON csp_appdata.customer
  USING btree
  (state0);

-- Index: csp_appdata.customer_statecity0_i

-- DROP INDEX csp_appdata.customer_statecity0_i;

CREATE INDEX customer_statecity0_i
  ON csp_appdata.customer
  USING btree
  (statecity0);

-- Index: csp_appdata.customer_virtualschemaid_i

-- DROP INDEX csp_appdata.customer_virtualschemaid_i;

CREATE INDEX customer_virtualschemaid_i
  ON csp_appdata.customer
  USING btree
  (virtualschemaid);

-- Index: csp_appdata.customer_webpage0_g

-- DROP INDEX csp_appdata.customer_webpage0_g;

CREATE INDEX customer_webpage0_g
  ON csp_appdata.customer
  USING pgroonga
  (webpage0 COLLATE pg_catalog."default" text_regexp_ops);

-- Index: csp_appdata.customer_webpage0_i

-- DROP INDEX csp_appdata.customer_webpage0_i;

CREATE INDEX customer_webpage0_i
  ON csp_appdata.customer
  USING pgroonga
  (id, webpage0 COLLATE pg_catalog."default");

**Comment by kou** [comment]
Thanks.
I couldn't find any problem in the DDL.

Could you also show pgroonga.log and PostgreSQL log?

**Comment by yongxianggao-chanjet** [comment]
I can NOT reproduce it with latest pgroonga source code, maybe it's fixed already.

**Comment by kou** [comment]
OK. I close this issue.
