### ISSUE TITLE
Add support for using PGroonga installed into another schema 

### ISSUE THREAD

**Issue by kou** [pgroonga/pgroonga#291]
### What is your problem?

Supabase installs PGroonga to `extensions` schema by default.
If PGroonga is installed to `extensions` schema, `SELECT ...` in `public` schema can't use PGroonga.

Can we use PGroonga installed to `extensions` schema with some configurations such as `search_path`? Or is this a restriction of PostgreSQL?

See also: https://gitter.im/groonga/ja?at=63e79c65450b707d6f50cb20

**Comment by dshukertjr** [comment]
Hi @kou ,

Thanks for the amazing work here on pgroonga! I was just wondering if this issue has been fixed. Would we be able to use pgroonga with it being installed on the `extension` schema?

**Comment by kou** [comment]
Yes!

**Comment by dshukertjr** [comment]
That is amazing! Thank you!
