### ISSUE TITLE
`&~`演算子による正規表現の前方一致や後方一致に`NormalizerTable`が反映されない

### ISSUE THREAD

**Issue by askdkc** [pgroonga/pgroonga#293]
### What happend?

タイトルの如く`&~`演算子による正規表現の前方一致や後方一致に`NormalizerTable`によるノーマライズが反映されない

## DB作成
```bash
createdb dougigo
psql dougigo
```

## SQL実行
```sql
CREATE EXTENSION pgroonga;

CREATE TABLE synonyms (
  target text,
  normalized text
);

CREATE INDEX pgroonga_synonyms_index ON synonyms
 USING pgroonga (target pgroonga_text_term_search_ops_v2,
                 normalized);

INSERT INTO synonyms VALUES ('齊', '斉');
INSERT INTO synonyms VALUES ('斎', '斉');
INSERT INTO synonyms VALUES ('齋', '斉');
INSERT INTO synonyms VALUES ('髙', '高');

CREATE TABLE names (
  name text
);
CREATE INDEX pgroonga_names_index
          ON names
       USING pgroonga (name pgroonga_text_regexp_ops_v2)
   WITH (normalizers='
                NormalizerNFKC130,
                NormalizerTable(
                  "normalized", "${table:pgroonga_synonyms_index}.normalized",
                  "target", "target"
                )
             ');

INSERT INTO names
  (name)
  VALUES ('斉藤さん'),('齊藤さん'),('斎藤さん'),('鈴木さん'),('田中さん'),('佐藤さん'),('高橋さん'),('髙橋さん');
```

## 検索を実施
```sql
select * from names where name &~ '\A斉';
--    name   
-- ----------
--  斉藤さん
-- (1 row)

```

### Expected behavior

```sql
select * from names where name &~ '\A斉';
--    name   
-- ----------
--  斉藤さん
--  齊藤さん
--  斎藤さん
-- (3 rows)
```

### Environment

- OS: [macOS 13.2 Ventura]
- OS Version: [macOS 13.2 Ventura]
- PostgreSQL Version: [14.6]
- PGroonga Version: [2.4.4]
- libgroonga Version: [macOSだと↓のコマンドで取れない？]
   - https://pgroonga.github.io/ja/reference/parameters/libgroonga-version.html

### Additional context

`&@~`演算子で前方一致や後方一致検索も動かないですかね？
`LIKE`検索のようにキーワード後方に`%`つけると前方一致、キーワード前方に`%`つけると後方一致みたいな動きが欲しい時があります

**Comment by komainu8** [comment]
`&~`は正規表現のパターンを正規化しないのでそれが原因かと思ったのですが、`select * from names where name &~ '\A斉';`なら正規表現のパターンが正規化されなくても3レコードヒットしそうですね。見てみます。

**Comment by komainu8** [comment]
あと、`libgroonga Version: [macOSだと↓のコマンドで取れない？] `も気になるのでこちらも、手が空いているときで構わないのでご報告いただけると嬉しいです。

**Comment by askdkc** [comment]
@komainu8 さん

https://gist.github.com/askdkc/fe992097b1c80cf1578b489b1f382c35

こちらのやり取りでバグかも？ということでissue建てさせて頂きました🙏

**Comment by komainu8** [comment]
おぉ。なるほど！

**Comment by askdkc** [comment]
> あと、`libgroonga Version: [macOSだと↓のコマンドで取れない？] `も気になるのでこちらも、手が空いているときで構わないのでご報告いただけると嬉しいです。

新規DBで再現させようとしたら上手く行っちゃいました。。。

```bash
createdb test
psql test
``` 

```sql
create extension pgroonga;
-- CREATE EXTENSION

show pgroonga.libgroonga_version;
--  pgroonga.libgroonga_version 
-- -----------------------------
--  12.1.1
-- (1 row)
```

なんだったんだろう🤔

とはいえ、こちらで再度`NormalizerTable`使ってインデックスを作成しても`&~`演算子を用いた同義語検索はうまく動かないですね

バグでしょうか？

**Comment by komainu8** [comment]
＞ 新規DBで再現させようとしたら上手く行っちゃいました。。。

早速ありがとうございます！うーん、なんでしょうね。。。

> とはいえ、こちらで再度NormalizerTable使ってインデックスを作成しても&~演算子を用いた同義語検索はうまく動かないですね
> バグでしょうか？

こちらもありがとうございます！
そうですね。PGroongaの動きがおかしい気がします。

**Comment by kou** [comment]
`pgroonga.libgroonga_version`が出なかったのはPGroongaがまだロードされていなかったからだと思います。
`select pgroonga_command('status')`なんなりしてPGroongaがロードされないと`pgroonga.*`は見えません。

`normalizers`とかオプションを指定すると`pgroonga_text_regexp_ops_v2`を指定していても`TokenRegexp`ではなくて`TokenBigram`が使われていたので`TokenRegexp`を使うようにしておきました。

回避策はこのように`tokenizer='TokenRegexp'`を明示的に指定する、です。

```sql
CREATE INDEX pgroonga_names_index
          ON names
       USING pgroonga (name pgroonga_text_regexp_ops_v2)
   WITH (tokenizer='TokenRegexp',
         normalizers='
                NormalizerNFKC130,
                NormalizerTable(
                  "normalized", "${table:pgroonga_synonyms_index}.normalized",
                  "target", "target"
                )
             ');
```

**Comment by askdkc** [comment]
@kou さん

ありがとうございます〜💕

**Comment by askdkc** [comment]
@kou さん

正規表現かつ`normalizer`を使ったAND検索やOR検索は下記のような感じで問題ないでしょうか？

### AND検索

```sql
-- 「藤」を含むデータかつ末尾が「ん」で終わり、NormalizerTableで同義語も検索
select * from names where name &~ '藤' and name &~ 'ん\z';
   name   
----------
 斉藤さん
 齊藤さん
 斎藤さん
 佐藤さん
(4 rows)
```

### OR検索
```sql
-- 先頭が「高橋さん」 OR 「齋藤」 を含むデータかつNormalizerTableで同義語も検索
select * from names where name &~| array['高橋さん','齋藤'];
--    name   
-- ----------
--  高橋さん
--  髙橋さん
--  斉藤さん
--  齊藤さん
--  斎藤さん
-- (5 rows)
```

> **気になるポイント**
> OR検索の場合、ARRAYを使わないで正規表現を使うとNormalizerTableが反映されない
> ```sql
> select * from names where name &~ '\A斎藤' or name &~ '\A高橋';
> --    name   
> -- ----------
> --  斎藤さん
> --  高橋さん
> -- (2 row)
> ```

**Comment by askdkc** [comment]
@kou さん

ありがとうございます😊

> ANDはname &~ '藤.*ん\z'の方がPostgreSQLレベルでのANDがなくなって速いです。

聞いといて良かった、、、絶対自分じゃ気付かなかった🫠

さすがです！助かります！
