### ISSUE TITLE
When using an index with `queryallowcolumn=true`, the function `pgroonga_query_extract_keywords` do not work as expected.

### ISSUE THREAD

**Issue by yodhcn** [pgroonga/pgroonga#308]
### What happend?

 Can the function `pgroonga_query_extract_keywords` support syntax `colunm:` ?

### How to reproduce it

```SQL
DROP TABLE IF EXISTS memos;
CREATE TABLE memos (
  id integer,
  title text,
  content text,
  PRIMARY KEY (id)
);

CREATE INDEX pgroonga_memo_texts_index
          ON memos
       USING pgroonga ((ARRAY[title, content]), title, content)
        WITH (query_allow_column=true);

INSERT INTO memos VALUES
  (1, 'PGroonga = PostgreSQL + Groonga', 'Very fast full text search extension.'),
  (2, 'PostGIS', 'GIS extension.');

SELECT *, pgroonga_query_extract_keywords('Groonga content:@full') AS keywords
  FROM memos
 WHERE ARRAY[title, content] &@~ 'Groonga content:@full';
 
-- id |             title               |                content                |       keywords
-- ---+---------------------------------+---------------------------------------+-------------------------
--  1 | PGroonga = PostgreSQL + Groonga | Very fast full text search extension. | {content:@full,Groonga} 
-- (1 rows)
```

### Expected behavior

```SQL
SELECT *, pgroonga_query_extract_keywords('Groonga content:@full', pgroonga_memo_texts_index) AS keywords
  FROM memos
 WHERE ARRAY[title, content] &@~ 'Groonga content:@full';
 
-- id |             title               |                content                |       keywords
-- ---+---------------------------------+---------------------------------------+-------------------------
--  1 | PGroonga = PostgreSQL + Groonga | Very fast full text search extension. | {full,Groonga} 
-- (1 rows)
```

### Environment

- OS: [Windows]
- OS Version: [Windows 10]
- PostgreSQL Version: [15.2]
- PGroonga Version: [2.4.7]
- libgroonga Version: [13.0.1]
   - https://pgroonga.github.io/ja/reference/parameters/libgroonga-version.html

**Comment by kou** [comment]
Ah, we need to pass the index name to `pgroonga_query_extract_keywords()` to support this case.

**Comment by yodhcn** [comment]
> Ah, we need to pass the index name to `pgroonga_query_extract_keywords()` to support this case.

Also, is it possible to make `column &@~ (query, weights, index_name)::pgroonga_full_text_search_condition` support the `column:` syntax when computing scores?

Thanks for your contribution to maintaining this repository!

**Comment by kou** [comment]
> Also, is it possible to make `column &@~ (query, weights, index_name)::pgroonga_full_text_search_condition` support the `column:` syntax when computing scores?

Could you open a new issue for it with example?
