### ISSUE TITLE
pgroonga.score is slow

### ISSUE THREAD

**Issue by yongxianggao-chanjet** [pgroonga/pgroonga#31]
Hi

  We try following 2 statements :

      select * from csp_appdata.product product where name0 @@ '沙琪玛';
      select *, pgroonga.score(product) from csp_appdata.product product where name0 @@ '沙琪玛';

  The former takes 152 ms.
  And the latter takes much longer, with pgroonga-1.1.4, it takes around 11-12 seconds, since pgroonga-1.1.5, the speedup is almost 2X, now it takes 5027 ms,  around 33X slower if compared with the former(152 ms).
  
   Any way to improve the speed of pgroonga.score further?

   FYI, There are 49152 matching rows out of 245760 rows, and the values of name0 field are like following:
     ' 香港 蓝欧 蛋酥味沙琪玛 408g 20盒*408g    '
     ' 香港 蓝欧 黑糖味沙琪玛 408g 20盒*408g    '
     ' 香港 蓝欧 芝麻味沙琪玛 408g 20盒*408g    '
     ' 香港 蓝欧 芝麻味沙琪玛 568g 12袋*568g    '
     ' 香港 蓝欧 黑糖味沙琪玛 568g 12袋*568g    '
     ' 香港 蓝欧 蛋酥味沙琪玛 568g 12袋*568g    ' 
     ' 香港 蓝欧 蛋酥味沙琪玛 408g 20盒*408g   '
     ...

   Thanks a  lot.
--Yongxiang

**Comment by kou** [comment]
Could you create sample schema and data set to show the case that can be ran on my environment?
If I can reproduce the case on my environment, I'll look for a bottleneck.

**Comment by yongxianggao-chanjet** [comment]
Just use the same schema as in tutorial:

CREATE TABLE score_memos (
  id integer PRIMARY KEY,
  content text
);

CREATE INDEX pgroonga_score_memos_content_index
          ON score_memos
       USING pgroonga (id, content);

Insert 100k rows:

INSERT INTO score_memos(id, content) select x.id, 'PostgreSQL is a relational database management system.' FROM generate_series(1,100000) AS x(id);

SET enable_seqscan = off;

\timing

Without score function, 100k rows takes 131 ms

select * from score_memos WHERE content %% 'PGroonga' OR content %% 'PostgreSQL';

With score function, it takes 20 seconds

select *, pgroonga.score(score_memos) from score_memos WHERE content %% 'PGroonga' OR content %% 'PostgreSQL';

**Comment by kou** [comment]
Thanks. I could confirm.

I improve performance: 9sec -> 300msec.

You can confirm the improvement by using master.

**Comment by yongxianggao-chanjet** [comment]
Yes, it's WAY faster now. Thanks a lot.

When are you going to release it?

--Yongxiang

**Comment by kou** [comment]
I don't have time to release a new version in this year. It'll be the next year...
