### ISSUE TITLE
Is it possible to make `pgroonga_varchar_array_term_search_ops_v2` support more operators ?

### ISSUE THREAD

**Issue by yodhcn** [pgroonga/pgroonga#317]
### What is your problem?

I have used the [`intarray` extension of PostgreSQL](https://www.postgresql.org/docs/current/intarray.html) which provides many convenience operators for `integer[]`, such as
- `integer[] && integer[] → boolean` Do arrays overlap (have at least one element in common)?
- `integer[] @@ query_int → boolean` Does array satisfy query? (see below)

The `@@`operators tests whether an array satisfies a query, which is expressed as a value of a specialized data type `query_int`. A query consists of integer values that are checked against the elements of the array, possibly combined using the operators `&` (AND), `|` (OR), and `!` (NOT). Parentheses can be used as needed. For example, the query `1&(2|3)` matches arrays that contain 1 and also contain either 2 or 3.

I think it will be convenient if `pgroonga_varchar_array_term_search_ops_v2` supports these 2 operators.

**Comment by kou** [comment]
They must be easy to implement.

Could you explain your use case of them?

**Comment by yodhcn** [comment]
> They must be easy to implement.
> 
> Could you explain your use case of them?

```
CREATE TABLE memos (
  id integer,
  tags varchar[],
  PRIMARY KEY (id)
);
```
I want to implement these two queries:
- `tags` contain either `tag_2` or `tag_3`
- `tags` contain `tag_1` and also contain either `tag_2` or `tag_3`

I know they can be implemented using a combination of the `&>` operator and the `@>` operator. But I hope `varchar[]` has one operator whitch can support complex queries, like the `&@~` operator of `text[]`, in this way, the SQL statement can be simplified.
```SQL
-- Using only the &> operator requires writing a lengthy SQL statement.
WHERE tags &> 'hello'
   OR tags &> '日本'
   OR tags &> 'Groonga';

-- If there is an operator that can simplify the above SQL statement.
WHERE tags && ARRAY['hello', '日本', 'Groonga']::varchar[];

-- If there is an operator that can support complex query
WHERE tags @@ 'hello OR 日本 OR Groonga';
```

Full-text search is similar to my needs, but using a full-text search for the `tags text[]` field may not be a good idea because I want the tags to be precisely matched.
For example, when I want to query a record with the tag `'hello'`, `'hello world'` is not expected in the query result.

```SQL
DROP TABLE IF EXISTS memos;
CREATE TABLE memos (
  id integer,
  tags_varchar_arr varchar[],
  tags_text_arr text[],
  PRIMARY KEY (id)
);

CREATE INDEX pgroonga_memo_tags_index
          ON memos
       USING pgroonga (tags_varchar_arr, tags_text_arr);

INSERT INTO memos VALUES
  (1, ARRAY['hello world', '日本語'], ARRAY['hello world', '日本語']),
  (2, ARRAY['hello', '日本語'], ARRAY['hello', '日本語']),
  (3, ARRAY['Groonga', '日本'], ARRAY['Groonga', '日本']);


SELECT * FROM memos
WHERE tags_varchar_arr &> 'hello'
   OR tags_varchar_arr &> '日本'
   OR tags_varchar_arr &> 'Groonga';
 
-- id |    tags_varchar_arr   |    tags_text_arr     
-- ---+-----------------------+----------------------
--  2 | {hello,日本語}         | {hello,日本語}
--  3 | {Groonga,日本}         | {Groonga,日本}
-- (2 rows)


SELECT * FROM memos
WHERE tags_text_arr &@~ 'hello OR 日本 OR Groonga';

-- id |    tags_varchar_arr   |    tags_text_arr     
-- ---+-----------------------+----------------------
--  1 | {"hello world",日本語} | {"hello world",日本語}
--  2 | {hello,日本語}         | {hello,日本語}
--  3 | {Groonga,日本}         | {Groonga,日本}
-- (3 rows)

-- 'hello world' is not expected in query result.
```
