### ISSUE TITLE
Any way to employ token filters? (as in TokenFilterStem)

### ISSUE THREAD

**Issue by nomoon** [pgroonga/pgroonga#32]
The instructions provide for assigning a different Tokenizer and Normalizer, but don't say whether it is possible to use token filters, as explained @ http://groonga.org/docs/reference/token_filters.html

I notice in my indices, if I search for a plural word (e.g. "bananas"), I won't find any cases of the singular word (e.g. "banana"), though if I only search for singular words, I will find the plurals. I'd very much like to fix this.

**Comment by kou** [comment]
We plan to support token filters but don't implement yet.

**Comment by kou** [comment]
I've implemented.

**Comment by nomoon** [comment]
@kou Wow, that was very fast, thanks! I will attempt to test this soon. Being able to use a stemming filter would result in a large jump in accuracy for alphabetical language searches.

**Comment by nomoon** [comment]
@kou I have tested this on OSX and it appears to work as expected (once groonga is also re-compiled from source to generate the stem filter). Thanks again!

**Comment by kou** [comment]
Thanks for confirming this.
