### ISSUE TITLE
An empty index for a jsonb type exceeds 1GB

### ISSUE THREAD

**Issue by weidqi** [pgroonga/pgroonga#327]
### What happened?

```sql
CREATE TABLE t (id INTEGER, name TEXT, property JSONB)
 PARTITION BY HASH (id);
CREATE INDEX forest_property_FTS ON forest USING PGROONGA (property);
```

index more than 1GB

when execute `VACUUM ANALYZE`,  the database size is increased to 2GB， index size is 0KB

### How to reproduce it

```sql
CREATE TABLE t (id INTEGER, name TEXT, property JSONB)
 PARTITION BY HASH (id);
CREATE INDEX forest_property_FTS ON forest USING PGROONGA (property);
```

### Expected behavior

table is empty

### Environment

- OS: [e.g. Ubuntu]
- OS Version: [e.g. Ubuntu 20.04.2 LTS]
- PostgreSQL Version: [e.g. 15.1]
- PGroonga Version: [e.g. 13.1.0]

   - https://pgroonga.github.io/ja/reference/parameters/libgroonga-version.html

**Comment by kou** [comment]
How did you count database size?
How did you count index size?

> table is empty

What does this mean? `SELECT COUNT(*) FROM t` == 0?

**Comment by weidqi** [comment]
> How did you count database size? How did you count index size?
> 
> > table is empty
> 
> What does this mean? `SELECT COUNT(*) FROM t` == 0?
hi，I use
select pg_size_pretty(pg_database_size('mydb'));
select pg_size_pretty(pg_relation_size('forest_property_FTS '));

**Comment by kou** [comment]
We can't use `pg_relation_size()` for it: #15

> table is empty

What does this mean?

**Comment by weidqi** [comment]
> We can't use `pg_relation_size()` for it: #15
> 
> > table is empty
> 
> What does this mean?

ALl tables are zero record，but select pg_size_pretty(pg_database_size('mydb'))   more than  1GB ....

**Comment by kou** [comment]
Is this reproduced from a newly created empty database?

**Comment by askdkc** [comment]
I don't know if this is helpful or not. But in my environment, this issue is not reproducible. 

## Environment

- OS: [macOS]
- OS Version: [macOS 13.2.1]
- PostgreSQL Version: [14.7]
- PGroonga Version: [3.0.0]
- libgroonga Version: [13.0.1]


## create sample db
```bash
createdb dbsizetest
psql dbsizetest
```

## create table and index
```sql
select pg_size_pretty(pg_database_size('dbsizetest'));
--  pg_size_pretty 
-- ----------------
--  8657 kB
-- (1 row)

create extension pgroonga;
-- CREATE EXTENSION

CREATE TABLE t (id INTEGER, name TEXT, property JSONB)
 PARTITION BY HASH (id);
-- CREATE TABLE

CREATE INDEX forest_property_FTS ON t USING PGROONGA (property);
-- CREATE INDEX

select pg_size_pretty(pg_database_size('dbsizetest'));
--  pg_size_pretty 
-- ----------------
--  51 MB
-- (1 row)

select pg_size_pretty(pg_relation_size('forest_property_FTS '));
--  pg_size_pretty 
-- ----------------
--  0 bytes
-- (1 row)
```

## PostgreSQL base_dir
```bash
du -sh 178424
 47M	178424
```

**Comment by weidqi** [comment]
> Is this reproduced from a newly created empty database?

Yes, I guess it has something to do with my CPU architecture.  128 cores，arm 64

**Comment by weidqi** [comment]
BUT..... Look at mine：

OS: [debian 11]  docker 19.0.3
PostgreSQL Version: [14.7]
PGroonga Version: [2.4.7]


#create database sizetest;
sizetest=# select pg_size_pretty(pg_database_size('sizetest'));
 pg_size_pretty 
----------------
 8553 kB
(1 row)

sizetest=# create extension pgroonga;
CREATE EXTENSION
sizetest=# select pg_size_pretty(pg_database_size('sizetest'));
 pg_size_pretty 
----------------
 51 MB
(1 row)

CREATE TABLE t (id INTEGER, name TEXT, property JSONB)
 PARTITION BY HASH (id);

CREATE INDEX forest_property_FTS ON t USING PGROONGA (property);

sizetest=# select pg_size_pretty(pg_database_size('dbsizetest'));

 pg_size_pretty 
----------------
 51 MB
(1 row)

sizetest=# CREATE TABLE t_0 PARTITION OF t
    FOR VALUES WITH (modulus 32, remainder 0);
CREATE TABLE t_1 PARTITION OF t
    FOR VALUES WITH (modulus 32, remainder 1);
CREATE TABLE t_2 PARTITION OF t
    FOR VALUES WITH (modulus 32, remainder 3);
CREATE TABLE t_3 PARTITION OF t
    FOR VALUES WITH (modulus 32, remainder 4);

sizetest=# select pg_size_pretty(pg_database_size('sizetest'));
 pg_size_pretty 
----------------
 195 MB

**Comment by askdkc** [comment]
@weidqi 

I ran your sql query and I got this (the db name is `'pgsize'` in this example):

```sql
select pg_size_pretty(pg_database_size('pgsize'));
--  pg_size_pretty 
-- ----------------
--  1175 MB
-- (1 row)
```

It seems this happens to us all👀

I ran your sql not using pgroonga and the db size is very low.
```sql
 pg_size_pretty 
----------------
 9545 kB
(1 row)
```

So this must be related to PGroonga I guess🤔

@komainu8 

We need your help on this if this isn't a normal behavior.

**Comment by kou** [comment]
If there are many PGroonga indexes (in this case, many PGroonga indexes are created by many partitions implicitly), it's not strange that DB size increased.
PGroonga (Groonga) pre-allocates files for indexes but they are sparse. So physical storage isn't used.

**Comment by weidqi** [comment]
> @weidqi
> 
> I ran your sql query and I got this (the db name is `'pgsize'` in this example):
> 
> ```sql
> select pg_size_pretty(pg_database_size('pgsize'));
> --  pg_size_pretty 
> -- ----------------
> --  1175 MB
> -- (1 row)
> ```
> 
> It seems this happens to us all👀
> 
> I ran your sql not using pgroonga and the db size is very low.
> 
> ```sql
>  pg_size_pretty 
> ----------------
>  9545 kB
> (1 row)
> ```
> 
> So this must be related to PGroonga I guess🤔
> 
> @komainu8
> 
> We need your help on this if this isn't a normal behavior.

Yes，What should I do for this ,  sir?  tell me :)  @askdkc

**Comment by askdkc** [comment]
@kou san

> If there are many PGroonga indexes (in this case, many PGroonga indexes are created by many partitions implicitly), it's not strange that DB size increased.
> PGroonga (Groonga) pre-allocates files for indexes but they are sparse. So physical storage isn't used.

Does this mean, it shows “1175 MB” but it’s not actually and physically used (yet)?

**Comment by kou** [comment]
Correct.

**Comment by askdkc** [comment]
@weidqi 

It turns out this is just a normal behavior for PGroonga.
Nothing to worry about.

Have a nice weekend😉

**Comment by weidqi** [comment]
ありがとうございました！
