### ISSUE TITLE
Failed to build without `HAVE_MSGPACK`

### ISSUE THREAD

**Issue by obache** [pgroonga/pgroonga#331]
### What happened?

commit 7a354fb02ae912d4ca731fcb4dadedb65d1bfc61 introduce `pgroonga_wal_status()` and it is built unconditionally.
But used features are not available unless `PGRN_SUPPORT_WAL` is defined.

`PGRN_SUPPORT_WAL` is defined if `PGRN_HAVE_MSGPACK` is defined in "pgrn-compatible.h" .

So if `HAVE_MSGPACK` is not defined, many compile errors are rised in "src/pgrn-wal.c".

### How to reproduce it

Just build manually without any flags, for example, type `make` in source tree.

It seems that any packagings and tests define `HAVE_MSGPACK` exactly.

### Expected behavior

Build fine without any additional build flags.

### Environment

- OS: NetBSD
- OS Version: 9.3
- PostgreSQL Version: 13.6
- PGroonga Version: 3.0.1
- libgroonga Version: 12.1.0
   - https://pgroonga.github.io/ja/reference/parameters/libgroonga-version.html

**Comment by kou** [comment]
Good catch!
