### ISSUE TITLE
ERROR:  pgroonga: object isn't found: <Sources17111> after CREATE DATABASE WITH TEMPLATE on PostgreSQL 15

### ISSUE THREAD

**Issue by andersk** [pgroonga/pgroonga#335]
### What happened?

The script below works on PostgreSQL 14, but fails on PostgreSQL 15 with

```
psql:test.sql:13: ERROR:  pgroonga: object isn't found: <Sources17111>
```

### How to reproduce it

```sql
DROP DATABASE IF EXISTS mydb;
CREATE DATABASE mydb;

\connect mydb
CREATE EXTENSION pgroonga;
CREATE TABLE mytable (mycol text);
CREATE INDEX myindex ON mytable USING pgroonga (mycol);

DROP DATABASE IF EXISTS myclone;
CREATE DATABASE myclone WITH TEMPLATE mydb;

\connect myclone
INSERT INTO mytable (mycol) VALUES ('Hello');
```

### Expected behavior

The row should be inserted successfully.

### Environment

- OS: Ubuntu
- OS Version: Ubuntu 22.04
- PostgreSQL Version: 15.3
- PGroonga Version: 3.0.2
- libgroonga Version: 13.0.1

**Comment by kou** [comment]
This is not a PGroonga problem.

PostgreSQL 15 or later has `STRATEGY` option for `CREATE DATABASE`.
https://www.postgresql.org/docs/current/sql-createdatabase.html

Its value is `WAL_LOG` by default. If you want to use `WAL_LOG`, you need to enable PGroonga's WAL.
See also: https://pgroonga.github.io/reference/parameters/enable-wal.html

Or you can use `FILE_COPY`: `CREATE DATABASE myclone WITH TEMPLATE mydb STRATEGY FILE_COPY;`
It copies `pgrn*` files like PostgreSQL 14 or earlier.

**Comment by andersk** [comment]
Thanks for the quick reply. This isn’t something I would have expected to need to look for.

When does `pgroonga.enable_wal` need to be in effect, if provided as a session variable? Experimenting with this test case shows that it needs to be in effect both for the `CREATE INDEX` and for the first `INSERT` within the copy. Is that suffiient in general?

Could PGroonga be improved to detect that `enable_wal` is necessary, at least on that first `INSERT` if the index was already created with `enable_wal`?

**Comment by kou** [comment]
In general, using `pgroonga.enable_wal` as a session variable isn't recommended. It's only for advanced users. Normal users should set `pgroonga.enable_wal` in `postgresql.conf` and not change by `SET`. If `pgroonga.enable_wal` is changed in a session, it may generate inconsistent PGroonga WAL (it's not same as the PostgreSQL's WAL).

`pgroonga.enable_wal` is only needed for `CREATE DATASET WITH TEMPLATE STRATEGY WAL_LOG` and streaming replication.
`CREATE INDEX`/`INSERT`/`UPDATE`/`VACUUM` will generate PGroonga WAL when `pgroonga.enable_wal` is `on`. So enabling `pgroonga.enable_wal` only for `CREATE INDEX` and the first `INSERT` is not sufficient.

> Could PGroonga be improved to detect that `enable_wal` is necessary, at least on that first `INSERT` if the index was already created with `enable_wal`?

If we do it, PGroonga may generate PGroonga WAL even when `pgroonga.enable_wal` is `off`. So it's not acceptable.

We may be able to enable `pgroonga.enable_wal` by default or deprecate `pgroonga.enable_wal` when we add support for Custom WAL Resource Managers https://www.postgresql.org/docs/current/custom-rmgr.html that is available since PostgreSQL 15. We can integrate with PostgreSQL's WAL system by the feature.

BTW, why do you want to use  `CREATE DATASET WITH TEMPLATE STRATEGY WAL_LOG`?

**Comment by andersk** [comment]
> If we do it, PGroonga may generate PGroonga WAL even when `pgroonga.enable_wal` is `off`. So it's not acceptable.

It seems to me that it’d be friendlier to do what the user clearly needs even if they forgot to explicitly request it each time, than to rigidly adhere to this principle and risk corrupting the WAL that was requested before.

But if for some reason `enable_wal = off` needs to be a mode that corrupts the WAL, could we have an `enable_wall = "auto"` that doesn’t, and make that the default?

> BTW, why do you want to use `CREATE DATASET WITH TEMPLATE STRATEGY WAL_LOG`?

The Django parallel test runner [clones](https://github.com/django/django/blob/4.2.1/django/test/utils.py#L230) the test database per-process [using `CREATE DATABASE … WITH TEMPLATE`](https://github.com/django/django/blob/4.2.1/django/db/backends/postgresql/creation.py#L18); the strategy is not configurable (without patching Django) and inherits the PostgreSQL default.

It would be more convenient to set a session variable when setting up PGroonga than to build a system for our development environment that automatically installs and edits a custom PostgreSQL configuration file and restarts PostgreSQL as necessary. But needing to reset the session variable for every connection isn’t so convenient.

**Comment by kou** [comment]
> But if for some reason `enable_wal = off` needs to be a mode that corrupts the WAL, could we have an `enable_wal = "auto"` that doesn’t, and make that the default?

I don't think that it's a good API... If we introduce `auto`, we can't use a "boolean" option and most users will be confused. What "auto" mean will be different for each user.



> The Django parallel test runner [clones](https://github.com/django/django/blob/4.2.1/django/test/utils.py#L230) the test database per-process [using `CREATE DATABASE … WITH TEMPLATE`](https://github.com/django/django/blob/4.2.1/django/db/backends/postgresql/creation.py#L18); the strategy is not configurable (without patching Django) and inherits the PostgreSQL default.

Could you open an issue for Django for this?

> It would be more convenient to set a session variable when setting up PGroonga than to build a system for our development environment that automatically installs and edits a custom PostgreSQL configuration file and restarts PostgreSQL as necessary. But needing to reset the session variable for every connection isn’t so convenient.

How about using `ALTER SYSTEM` for your use case?
https://www.postgresql.org/docs/current/sql-altersystem.html

Or `PSQLRC` may be usable to set `pgroonga.enable_wal` for all user sessions: https://www.postgresql.org/docs/current/app-psql.html

**Comment by andersk** [comment]
> I don't think that it's a good API...

Me neither. I still think `off` should be reinterpreted in a way that doesn’t corrupt anything!

But thanks for the other ideas, I’ll look into those.
