### ISSUE TITLE
Request：Windows 64bit + PostgreSQL 9.6.2-3

### ISSUE THREAD

**Issue by greentea2017** [pgroonga/pgroonga#35]
Hello.

I was wondering if you could provide us.
Windows 64bit + PostgreSQL 9.6.2-3

**Comment by kou** [comment]
I've uploaded packages for it: http://pgroonga.github.io/install/windows.html

**Comment by greentea2017** [comment]
Thank you so much.
I appreciate your prompt response.

**Comment by kou** [comment]
If your application (service, product and so on) is public, please send us its information to spread PGroonga!
See also: http://pgroonga.github.io/users/
