### ISSUE TITLE
HomebrewでPGroonga 3.1.0のビルドがコケる

### ISSUE THREAD

**Issue by askdkc** [pgroonga/pgroonga#356]
### What happened?

PGroonga 3.1.0のHomebrewでのビルドプロセスでgroonga.hが無いというエラーが出てビルドがコケる

https://github.com/Homebrew/homebrew-core/actions/runs/5548298916/jobs/10131179173?pr=136538#step:3:56

### How to reproduce it

homebrewのPRのCIエラーログ参照

### Expected behavior

ビルドがうまく通ってBrewでリリースされること

### Environment

- OS: [GitHub CI]
- OS Version: [macOS 11-arm64 build]
- PostgreSQL Version: [14.8]
- PGroonga Version: [3.1.0]
- libgroonga Version: [unknown: groonga.h not found build error]
   - https://pgroonga.github.io/ja/reference/parameters/libgroonga-version.html

**Comment by kou** [comment]
続きは https://github.com/Homebrew/homebrew-core/pull/136538 でやりましょう！
