### ISSUE TITLE
libgroonga0 broken dependency on libarrow1200 on Debian 12

### ISSUE THREAD

**Issue by andersk** [pgroonga/pgroonga#357]
### What happened?

The `libgroonga0` binary package for Debian 12 has a broken dependency on the `libarrow1200` package, which is present in the packages.groonga.org repository for Debian 11 but not for Debian 12.

### How to reproduce it

```console
$ docker run --rm -it debian:12
root@189e968b1f0f:/# apt update
root@189e968b1f0f:/# apt install -y wget
root@189e968b1f0f:/# wget https://packages.groonga.org/debian/groonga-apt-source-latest-bookworm.deb
root@189e968b1f0f:/# apt install -y ./groonga-apt-source-latest-bookworm.deb
root@189e968b1f0f:/# apt update
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian bookworm-updates InRelease
Hit:3 http://deb.debian.org/debian-security bookworm-security InRelease
Get:4 https://packages.groonga.org/debian bookworm InRelease [9543 B]
Get:5 https://packages.groonga.org/debian bookworm/main Sources [2348 B]
Get:6 https://packages.groonga.org/debian bookworm/main amd64 Packages [6056 B]
Fetched 17.9 kB in 1s (18.4 kB/s)
Reading package lists...
Building dependency tree...
Reading state information...
All packages are up to date.
root@189e968b1f0f:/# apt install libgroonga0
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgroonga0 : Depends: libarrow1200 (>= 12.0.1) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

### Expected behavior

`libgroonga0` should install successfully.

### Environment

- OS: Debian
- OS Version: Debian 12
- libgroonga Version: 13.0.2

**Comment by askdkc** [comment]
@andersk 

Debian 12 bookworm support will be released by the end of this month, I guess.

**Comment by kou** [comment]
We also need to enable Apache Arrow's official APT repository for Debian 12: https://groonga.org/docs/install/debian.html#bookworm

```console
$ sudo apt update
$ sudo apt install -y -V ca-certificates lsb-release wget
 $ wget https://apache.jfrog.io/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
$ sudo apt install -y -V ./apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
```

packages.groonga.org mirrors Apache Arrow packages for Debian < 12 to keep backward compatibility. (It's for avoiding the "unmet dependencies" error by `sudo apt update`.)
But we don't need to keep backward compatibility for Debian 12 because Debian 12 is a new version.
So packages.groonga.org doesn't mirror Apache Arrow packages for Debian 12.

 We'll release PGroonga packages for Debian 12 soon.

**Comment by askdkc** [comment]
Groonga now supports Debian 12.
It's getting ready.

https://github.com/groonga/groonga/pull/1580

**Comment by askdkc** [comment]
Debian 12 Support Released

https://github.com/pgroonga/pgroonga/discussions/359

**Comment by kou** [comment]
Done: https://pgroonga.github.io/install/debian.html#install-on-bookworm

**Comment by askdkc** [comment]
It's not even Friday yet! Yay!
