### ISSUE TITLE
docker build error

### ISSUE THREAD

**Issue by jadestoner** [pgroonga/pgroonga#363]
### What happened?

![image](https://github.com/pgroonga/pgroonga/assets/22416350/be356779-a49e-447e-af96-1b89240ec85f)
Docker build error

![image](https://github.com/pgroonga/pgroonga/assets/22416350/8bcf81aa-2801-4d77-b63d-de4426a25429)

Dockerfile 
`RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ bullseye-pgdg main" \
    && tee /etc/apt/sources.list.d/pgdg.list \
    && apt update \
    && apt install -y -V postgresql-14-pgdg-pgroonga`

### How to reproduce it

When docker build , the error will occur.

### Expected behavior

Wish it success

### Environment

- OS: [e.g. Ubuntu]
- OS Version: [e.g. Ubuntu 20.04.2 LTS]
- PostgreSQL Version: [e.g. 15.1]
- PGroonga Version: [e.g. 12.1.0]
- libgroonga Version: [e.g.  8.0.1]
   - https://pgroonga.github.io/ja/reference/parameters/libgroonga-version.html

**Comment by kou** [comment]
You need to add Apache Arrow's APT repository and Groonga's APT repository too.

See also: https://pgroonga.github.io/install/debian.html

**Comment by jadestoner** [comment]
`#26 4.053  postgresql-14-pgdg-pgroonga : Depends: postgresql-14 but it is not installable
`
Is there a method that doesn't require ’postgresql-14 ‘？What I used is ’postgresql-repmgr-14‘，not official pg
