### ISSUE TITLE
Search for whole words only

### ISSUE THREAD

**Issue by ArturFormella** [pgroonga/pgroonga#37]
Hello!
Is it possible to search for the whole word only? Is there any suitable operator or tokenizer?

The following query helps to check it (no FALSE in IS_OK column)
```
drop table if exists memos;
CREATE TABLE memos (id integer,  content text);

INSERT INTO memos VALUES (1, 'PostgreSQL is a relational database management system.');
INSERT INTO memos VALUES (2, 'Groonga is a fast full text search engine that supports all languages.');
INSERT INTO memos VALUES (3, 'PGroonga is a PostgreSQL extension that uses Groonga as index.');
INSERT INTO memos VALUES (4, 'There is groonga command 3.6V');

drop index if exists pgroonga_content_index;
CREATE INDEX pgroonga_content_index ON memos USING pgroonga (content pgroonga.text_full_text_search_ops_v2) WITH (tokenizer='TokenDelimit');

SET enable_seqscan = off;

SELECT '@@' as oper, true as "is_ok", 'relational| fast', * FROM memos WHERE content @@ 'relational | fast'
union all
SELECT '@@' as oper, false, 'databK & fast', * FROM memos WHERE content @@ 'databK & fast'
union all
SELECT '@@' as oper, true, 'database & fast', * FROM memos WHERE content @@ 'database & fast'
union all
SELECT '@@' as oper, true, 'database', * FROM memos WHERE content @@ 'database'
union all
SELECT '@@' as oper, false, 'databa', * FROM memos WHERE content @@ 'databa'
union all
SELECT '@@' as oper, false, 'databa_', * FROM memos WHERE content @@ 'databa '
union all
SELECT '@@' as oper, false, '_databa', * FROM memos WHERE content @@ ' databa'
union all
SELECT '@@' as oper, true,'_engine_', * FROM memos WHERE content @@ ' engine '
union all
SELECT '@@' as oper, true, '3.6V engine1', * FROM memos WHERE content @@ '3.6V or engine'
union all
SELECT '&@' as oper, true, '3.6V engine', * FROM memos WHERE content &@> ARRAY['3.6V', 'engine']
union all
SELECT '&@' as oper, false, '_3.6_ _engine_', * FROM memos WHERE content &@> ARRAY[' 3.6 ', ' engin ']
union all
SELECT '&@' as oper, false, '3.6 engine', * FROM memos WHERE content &@> ARRAY['3.6', 'engin']
union all
SELECT '&@' as oper, false, '3.6', * FROM memos WHERE content &@> ARRAY['"fast"']
union all
SELECT '&@' as oper, false, '36', * FROM memos WHERE content &@> ARRAY['36']
union all
SELECT '&@' as oper, false, 'extens', * FROM memos WHERE content &@> ARRAY['extens']
union all
SELECT '&@' as oper, false, '_extension_', * FROM memos WHERE content &@> ARRAY[' extension ']
union all
SELECT '&@' as oper, false, 'extens_', * FROM memos WHERE content &@> ARRAY['extens ']
union all
SELECT '&`' as oper, false, 'groong', * FROM memos WHERE content &` 'content @ "groong"'::text
union all
SELECT '&`' as oper, false, 'roonga', * FROM memos WHERE content &` 'content @ "roonga"'::text
union all
SELECT '&`' as oper, false, 'roonga_', * FROM memos WHERE content &` 'content @ "roonga "'::text
union all
SELECT '&`' as oper, false, '_roonga', * FROM memos WHERE content &` 'content @ " roonga "'::text
```
![groonga](https://cloud.githubusercontent.com/assets/11973278/26118547/9ee4de24-3a6a-11e7-8986-c314b3d951ef.png)

Than you!

**Comment by kou** [comment]
> Is it possible to search for the whole word only?

Yes. But the released PGroonga lacks configuration feature. I've implemented it at master.

> Is there any suitable operator or tokenizer?

`&@` and `&@>` are the suitable operators.

`TokenDelimit` is the suitable tokenizer if your "word" is separated by a space.

----

PGroonga (Groonga) searches loosely (e.g. by prefix search) automatically when no records are matched. It's useful for many use cases. So it's enabled by default.

In the case, "engine" is matched against "engin" is occurred by the feature.

I've added a new variable `pgroonga.match_escalation_threshold` that controls the feature. If you set -1 to the variable, you can disable the feature:

```sql
SET pgroonga.match_escalation_threshold = -1;
```

With the configuration, you can get what you expected.

**Comment by ArturFormella** [comment]
Hello!
Thank you for your quick reply. 
The new var is a global one and affects on other features on whole cluster.
For example LIKE and %% stop working:

```
SET pgroonga.match_escalation_threshold = -1;
SELECT 'like' as oper, true,'%ngin%', * FROM custom_query.memos WHERE content like  '%ngin%'
union all
SELECT '%%' as oper, true,'ngin', * FROM custom_query.memos WHERE content %% 'ngin'
```
Is it possible to have both features available?

For example %% and pgroonga's LIKE as a drop-in replacement of Postgresql's LIKE, and other operators (i.e. &@,@@) controlled by the new variable.

Other idea (index-level setting):
CREATE INDEX gi ON memos USING pgroonga (content pgroonga.text_full_text_search_ops_v2)
 WITH (tokenizer='TokenDelimit', match_escalation_threshold = -1)

Another idea (query level setting): The best place for the new feature would be in new operator class to control loosely search at query-level. For example :

> "&?" -  full text search with query +loosely search
> "&?=" - full text search with query +strict match (replacement of PostgreSQL @@ operator)
> "&@" -  full text search by one keyword +loosely search
> "&@=" -  full text search by one keyword +strict match
> "%%" - drop-in replacement of PostgreSQL's LIKE

e.t.c.
I think 'loosely search' actually should be controlled at query time.

The last idea would solve all problems but looks like a lots of work. What do you think? :)

**Comment by kou** [comment]
You can't implement both word exact match ("engine" is matched but "ngine" isn't matched) and partial match (both "engine" and "ngine" are matched) with only one tokenizer. You need to use another tokenizer for each case.

You need to use `TokenDelimit` for word exact match.

You need to use `TokenBigramSplitSymbolAlphaDigit` for partial match.

It means that you need 2 indexes for the same column. But PostgreSQL doesn't provide a feature that specifying which index should be used. So we need to use a trick to use the specified index:

```sql
DROP INDEX IF EXISTS index_for_exact_match;
CREATE INDEX index_for_exact_match ON memos
  USING pgroonga (content pgroonga.text_full_text_search_ops_v2)
  WITH (tokenizer='TokenDelimit');

CREATE OR REPLACE FUNCTION partial_match_text(arg text)
  RETURNS text
  AS $$ BEGIN RETURN arg; END; $$
  LANGUAGE plpgsql
  IMMUTABLE
  STRICT;

DROP INDEX IF EXISTS index_for_partial_match;
CREATE INDEX index_for_partial_match ON memos
  USING pgroonga (partial_match_text(content) pgroonga.text_full_text_search_ops_v2)
  WITH (tokenizer='TokenBigramSplitSymbolAlphaDigit);

-- exact match
SELECT '@@' as oper, true, 'database', * FROM memos WHERE content @@ 'database';

-- partial match
SELECT 'like' as oper, true,'%ngin%', * FROM memos WHERE partial_match_text(content) like '%ngin%';
```
