### ISSUE TITLE
Error "function pgroonga_wal_apply() does not exist" when using pgroonga_standby_maintainer module with CREATE EXTENSION pgroonga with schema specified

### ISSUE THREAD

**Issue by kurita0** [pgroonga/pgroonga#373]
### What happened?

スキーマを指定(WITH SCHEMA)してCREATE EXTENSION pgroongaしたデータベースで
ストリーミングレプリケーションを設定、pgroonga_standby_maintainerモジュールを使用すると以下エラーが発生します。

```
ERROR:  function pgroonga_wal_apply() does not exist at character 8
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
QUERY:  select pgroonga_wal_apply()
LOG:  background worker "pgroonga: standby-maintainer: maintain: pgroonga_test(3062236)" (PID 95033) exited with exit code 1
```

### How to reproduce it

```
CREATE SCHEMA test;
CREATE TABLE test.memos (
  id integer,
  content text
);
CREATE EXTENSION IF NOT EXISTS pgroonga WITH SCHEMA test;
CREATE INDEX pgroonga_content_index ON test.memos USING pgroonga (content);
```

https://pgroonga.github.io/ja/reference/streaming-replication.html
に従ってトリーミングレプリケーション設定をする。

### Expected behavior

エラーなしでpgroonga_standby_maintainerが動作する。

### Environment

- OS: FreeBSD
- PostgreSQL Version: 11.21
- PGroonga Version: 2.4.7
- libgroonga Version: 13.0.7

### Additional context

暫定対応でpublicスキーマに手動でshare/extension/pgroonga--2.4.7.sqlと同じ内容でCREATE FUNCTION pgroonga_wal_apply()とpgroonga_vacuum()をして関数作成、エラー回避してます。

**Comment by askdkc** [comment]
public以外のschemaのサポートはPGroonga 3.0.0以上からだから、まずはPGroongaを3系にアップデートしてみては？

https://github.com/pgroonga/pgroonga/releases/tag/3.0.0

> Improvements

> [GH-291][gh-291]: Stopped defining v1 compatible operators to the public schema. Now, you can install PGroonga to non-public schema (Supabase uses extensions schema by default) and work without any tricky SQL.

> This is a backward incompatible change but most users will not be affected because PGroonga 2.0.0 was released 6 years ago. Most users must not use v1 compatible operators.

**Comment by kurita0** [comment]
非サポートの古いバージョンでの報告すみませんでした。
`CREATE EXTENSION IF NOT EXISTS pgroonga WITH SCHEMA test;`
でtestスキーマ内ではpgroonga使えるようにみえてたのですが、非サポートだとpgroonga_standby_maintainer以外にも問題あったと思われます。
アップデート、確認のための別環境用意するのが先になりそうなのでクローズします。

上記の変更、CREATE EXTENSIONしたスキーマ(extensions)と異なるスキーマ(public)からの利用の問題とよみ違えてました。
