### ISSUE TITLE
Wrong URL  on Footer

### ISSUE THREAD

**Issue by hiroyuki-sato** [pgroonga/pgroonga#4]
誤字や誤訳、未訳を見つけたらお気軽にプルリクエストを送ってください！
https://pgroonga.github.io/ja/install/os-x.html

Wrong
  https://github.com/pgroonga/pgroonga.github.io/blob/master/ja/ja/install/os-x.md

Correct
  https://github.com/pgroonga/pgroonga.github.io/blob/master/ja/install/os-x.md

ja/ja -> ja

**Comment by kou** [comment]
ありがとうございます！
修正しました。
