### ISSUE TITLE
Support search queries with or without diacritics

### ISSUE THREAD

**Issue by jolleekin** [pgroonga/pgroonga#418]
### What is your problem?

Some languages have diacritics. For example,
- Vietnamese: con đường ngoằn nghoèo
- Swedish: besöker djurparken så ofta

With the diacritics removed, the texts become
- Vietnamese: con duong ngoan nghoeo
- Swedish: besoker djurparken sa ofta

### Current behavior: search queries must contain diacritics
```sql
 select 'con đường ngoằn nghoèo' &@~ 'ngoằn nghoèo'; -- true
 select 'con đường ngoằn nghoèo' &@~ 'ngoan nghoeo'; -- false
 select 'besöker djurparken så ofta' &@~ 'besöker';  -- true
 select 'besöker djurparken så ofta' &@~ 'besoker';  -- false
```

### Proposed behavior: search queries may or may not contain diacritics.
This behavior may be enabled by an option in the `create index` statement.
```sql
 select 'con đường ngoằn nghoèo' &@~ 'ngoằn nghoèo'; -- true
 select 'con đường ngoằn nghoèo' &@~ 'ngoan nghoeo'; -- true
 select 'besöker djurparken så ofta' &@~ 'besöker';  -- true
 select 'besöker djurparken så ofta' &@~ 'besoker';  -- true
```

**Comment by kou** [comment]
We don't have a feature for this for now but we can add a new normalization option such as `remove_diacritical_mark` for this case.
FYI: We already have many normalization options: https://groonga.org/docs/reference/normalizers/normalizer_nfkc150.html

We can use a new normalization option from PGroonga after we add it in Groonga,

**Comment by jolleekin** [comment]
Let me provide the context to make it clearer.

I have a multilingual app that supports English, Vietnamese, Chinese, and more in the future. For Vietnamese (or any other language that has diacritics), users should be able to search using queries with or without diacritics. If they want precise results, they should use queries with diacritics. If they want to type fast or if their keyboards don't support diacritics, they can enter queries without diacritics.

To support this use case, the text search engine needs to map an input token `s` to two tokens `t1` and `t2`
- `t1 = s`
- `t2 = removeDiacritics(s)`

Input | TS Vector
--- | ---
con đường ngoằn nghoèo | con:1 // t1 == t2<br><br>__duong:2__<br>đường:2<br><br>__ngoan:3__<br>ngoằn:3<br><br>__nghoeo:4__<br>nghoèo:4
besöker djurparken så ofta | __besoker:1__<br>besöker:1<br><br>djurparken:2<br><br>__sa:3__<br>så:3<br><br>ofta:4

Notice the addition of the bold tokens. Now users can search by `ngoằn nghoèo` or `ngoan nghoeo` or `ngoằn nghoeo` or `ngoan nghoèo` and get the same results.

**Comment by kou** [comment]
You can use `CREATE INDEX ... WITH(normalizers='NormalizerNFKC150("unify_latin_alphabet_with", true)')` with Groonga 14.0.7 for this.
See also how to use `WITH`: https://pgroonga.github.io/reference/create-index-using-pgroonga.html#custom-normalizer
