### ISSUE TITLE
Installation issue with Linux mint 18 

### ISSUE THREAD

**Issue by Sage91** [pgroonga/pgroonga#42]
I was trying to install `pgroonga-1.2.0` form source. However according to instruction, I installed `groonga` and `libgroonga-dev` packages too. But unfortunately getting  error:

> In file included from src/pgroonga.c:5:0:
> src/pgrn-command-escape-value.h:3:21: fatal error: groonga.h: No such file or directory
> compilation terminated.
> <builtin>: recipe for target 'src/pgroonga.o' failed
> make[1]: *** [src/pgroonga.o] Error 1

I have passed PG_CONFIG with the `make` command and also confirmed `pkg-config --list-all` includes `groonga`. 

THanks in advance.

**Comment by kou** [comment]
Please show your command line to run `make`.

**Comment by kou** [comment]
What is your platform?

**Comment by Sage91** [comment]
My platform is Linux mint 18 Cinnamon 64 bit. here is the command i used:

`make HAVE_MSGPACK=1 PG_CONFIG=/opt/PostgreSQL/9.6/bin/pg_config`

**Comment by Sage91** [comment]
Solved it. Sorry to bother you. Had to install `msgpack-c`  with C and cmake installation.
