### ISSUE TITLE
postgresql-16-pgdg-pgroonga not available for debian-bullseye

### ISSUE THREAD

**Issue by trisongz** [pgroonga/pgroonga#420]
Hi,

After trying to install `postgres-16-pgdg-pgroonga` in a docker container following the [instructions](https://pgroonga.github.io/install/debian.html) and the [Dockerfile](https://github.com/pgroonga/docker/blob/main/debian/16/Dockerfile) using `postgres:16.2-bullseye`, I kept running into `Unable to locate package postgresql-16-pgdg-pgroonga`. 

However, after some digging I realized that `debian-bullseye` [link](https://packages.groonga.org/debian/pool/bullseye/main/p/) does not contain the files for `postgresql-16-pgdg-pgroonga`, whereas `debian-bookworm` [link](https://packages.groonga.org/debian/pool/bookworm/main/p/) does within the apt repo. So after switching to `postgres:16.2-bookworm`, it worked without further issues.

Not sure if this is intended since the instructions explicitly show support for `postgres-16-pgdg-pgroonga` using debian bullseye, but wanted to point this out.

**Comment by kou** [comment]
Oh, the instructions are wrong. I've fixed it.
