### ISSUE TITLE
The "&?" operator cannot work on Laravel (PHP)

### ISSUE THREAD

**Issue by piroor** [pgroonga/pgroonga#45]
OK cases:

```
\App\Post::whereRaw('body @@ ?', $query);
\App\Post::whereRaw('body @@ :query', ['query'=>$query]);
\App\Post::whereRaw('body @@ \'Groonga OR PGroonga\'');
```

NG case:

```
\App\Post::whereRaw('body &? ?', $query);
\App\Post::whereRaw('body &? :query', ['query'=>$query]);
\App\Post::whereRaw('body &? \'Groonga OR PGroonga\'');
\App\Post::whereRaw('body &?? ?', $query);
\App\Post::whereRaw('body &\? ?', $query);
\App\Post::whereRaw('body &\\? ?', $query);
\App\Post::whereRaw('body &\\\? ?', $query);
\App\Post::whereRaw('body &\\\\? ?', $query);
```

Error message example, for `\App\Post::whereRaw('body &? :query', ['query'=>$query]);` case:

```
SQLSTATE[HY093]: Invalid parameter number: mixed named and positional parameters (SQL: select * from "posts" where body &与えられたクエリ文字列 :query order by "id" desc)
```

Basically PDO (PHP Data Object) cannot treat `?` as non-placeholder character.
(See also: https://stackoverflow.com/questions/16311939/how-to-prevent-pdo-from-interpreting-a-question-mark-as-a-placeholder and https://github.com/php/php-src/blob/master/ext/pdo/pdo_sql_parser.c#L54 )
Larabel is built on the PDO so it is impossible to use `&?` operator on Larabel.

We need alternative operator `&@@` or something without the character `?`.

**Comment by piroor** [comment]
See also:

PHP :: Request #71885 :: PostgreSQL has questin mark operator. This collide with PDO placeholder
https://bugs.php.net/bug.php?id=71885

**Comment by kou** [comment]
We've deprecated `&?`, `&~?` and `&?|` and introduced `&@~`, `&@*` and `&@~|`.
