### ISSUE TITLE
Reintroduce `@@` operator as tsearch-compatible

### ISSUE THREAD

**Issue by piroor** [pgroonga/pgroonga#46]
See also: https://github.com/zulip/zulip/issues/5603

tsearch's `@@` is case insensitive, but PGroonga's `@@` is case sensitive. And, now `@@` is deprecated in PGroonga and announced to migrate to new `&?` operator.

For application developers familiar to PostgreSQL, tsearch compatible operator seems useful and it will reduce barriers to start using of PGroonga.

**Comment by kou** [comment]
textsearch's `@@` is case sensitive.

textsearch's query syntax and PGroonga's query syntax is different. How to create textsearch index and PGroonga index are different. So reintroducing `@@` doesn't help existing textsearch users.

**Comment by piroor** [comment]
I meant that `@@` with query converter (translator, from textsearch's syntax to Groonga's syntax) will help users of textsearch.

**Comment by kou** [comment]
We can't do it because `@@` is provided by textsearch.

**Comment by piroor** [comment]
どうも意図が通じていないようなので日本語で失礼します……
textsearchと同じ文法のクエリを受け付けて、それに相当するGroonga用のクエリを組み立ててGroongaに渡す、という仕組みをPGroongaのレイヤで行ってはどうかという趣旨のissueのつもりでした。
素のGroongaを使うのにはハードルが高いがPGroongaやMroongaのような形態であれば使いやすい、というのの類型で、Groongaのクエリ構文を新たに覚えるのは辛いがtextsearchの構文だったら分かるという人だったりtextsearch前提で書かれたソフトウェアだったりの、PGroongaへの移行コストをクエリの文法という面から軽減する案です。
完全に1対1対応できない部分については諦めるとしても、OR検索のようなよく使われそうな機能だけでも互換性があれば有用なのでは？と思ったので。

ただ、この案は、クエリの変換に要する工数が充分に小さく、textsearchの知名度・シェアが高い、という条件が揃っている場合にのみ有効なので、textsearch自体あまり使われていないとか、クエリの変換はそもそもできない（パラダイムが違いすぎる）とか、簡単に変換できる物程度だと実用的でないとかいう状況であれば、かかるコストのわりに得られるメリットが小さくペイしないので、やらないという判断は妥当だと思っております。

**Comment by kou** [comment]
いや、だから、`@@`はPGroongaが定義しているものじゃなくてtextsearchが定義しているものだからPGroongaでそういう処理は実現できないんですって。

**Comment by piroor** [comment]
従来の「@@演算子を使ってクエリ構文で検索」もPGroongaではなくtextsearchが検索を実行しているのでしょうか？

**Comment by kou** [comment]
シーケンシャルサーチのときはそうです。

**Comment by kou** [comment]
> ただ、この案は、クエリの変換に要する工数が充分に小さく、textsearchの知名度・シェアが高い、という条件が揃っている場合にのみ有効なので、textsearch自体あまり使われていないとか、クエリの変換はそもそもできない（パラダイムが違いすぎる）とか、簡単に変換できる物程度だと実用的でないとかいう状況であれば、かかるコストのわりに得られるメリットが小さくペイしないので、やらないという判断は妥当だと思っております。

技術的にムリっていうのもそうなんですけど、そもそも、これの妥当性の判断を丸投げ（の上で技術的にできるの？という話をするん）、じゃなくて、妥当だと思うっていう理由があった上での提案の方が建設的じゃないかと思いました。

**Comment by piroor** [comment]
すみません、自分は現状を「`@@`演算子で検索すると、PGroongaがクエリ構文を受け取って検索を行う」「なので、PGroonga使用時には`@@`演算子ではPGroongaの構文しか使えない。textsearchの構文の検索クエリを渡しても期待通りの結果は得られない。」という事だと認識していたのですが、先の説明を見て「`@@`は（シーケンシャルサーチの時は）textsearchが処理する。」「なので`@@`演算子ではPGroongaの構文しか使えない。」と受け取ったため混乱しています。
根本的なところで最初の理解（PGroonga使用時に@@演算子を使うと起こる事）が間違っていたようです。

> そもそも、これの妥当性の判断を丸投げ

その辺りの判断材料はプロジェクトオーナー側が自分よりも詳しいはずと見込んでいたことと、「PostgreSQL indexed search」で検索するとtextsearchの情報が最上位に出てきたため、特に議論の余地なく妥当なのだろうけれども、もしかしたら実はそうでないという情報を既にプロジェクトオーナー側で掴んでいるのだろうか？と思ったため、このような書き方をしていました。すみません。

いずれにせよ、自分の提案の前提にあった理解自体が間違っていたということは確かなようなので、この提案は妥当でなかった、ということは認識できました。closeの判断に異論はありません。

**Comment by kou** [comment]
> その辺りの判断材料はプロジェクトオーナー側が自分よりも詳しいはずと見込んでいたことと、「PostgreSQL indexed search」で検索するとtextsearchの情報が最上位に出てきたため、特に議論の余地なく妥当なのだろう

それは言ってもらわないとわからないですよ。。。

**Comment by kou** [comment]
PGroongaに限ったことではないと思いますが、判断材料は、「一般的に便利そうだと思う（主語が大きい。自分は該当ケースではない。）」よりも「（自分も該当ケースな）具体的なユースケース」の方が有用です。前者は「え、それ本当なの？」から始めないといけませんが、後者は事実なのでそれベースに検討できるからです。
