### ISSUE TITLE
 ERROR:  ライブラリ"/usr/lib/postgresql/15/lib/pgroonga.so"をロードできませんでした: libarrow.so.1600: 共有オブジェクトファイルを開けません

### ISSUE THREAD

**Issue by delhicurry** [pgroonga/pgroonga#463]
### What happened?

`CREATE EXTENSION IF NOT EXISTS pgroonga;`
上記コマンド実行時に、
「 ERROR:  ライブラリ"/usr/lib/postgresql/15/lib/pgroonga.so"をロードできませんでした: libarrow.so.1600: 共有オブジェクトファイルを開けません」
メッセージが出力され、pgroonga拡張機能を追加できません。

### How to reproduce it

「Environment」記載の環境で、
以下のセットアップの状況で再現します。
「PGROONGA_VERSION」は、任意の値（「3.1.5-1」やそれ以外）で再現します。

```
  apt update && \
  apt install -y -V wget && \
  wget https://apache.jfrog.io/artifactory/arrow/debian/apache-arrow-apt-source-latest-bookworm.deb && \
  apt install -y -V ./apache-arrow-apt-source-latest-bookworm.deb && \
  rm apache-arrow-apt-source-latest-bookworm.deb && \
  wget https://packages.groonga.org/debian/groonga-apt-source-latest-bookworm.deb && \
  apt install -y -V ./groonga-apt-source-latest-bookworm.deb && \
  rm groonga-apt-source-latest-bookworm.deb && \
  apt update && \
  apt install -y -V \
    postgresql-15-pgdg-pgroonga=${PGROONGA_VERSION} \
    groonga-token-filter-stem \
    groonga-tokenizer-mecab && \
  apt clean && \
  rm -rf /var/lib/apt/lists/*
```

### Expected behavior

エラーが発生せず、正常にpgroonga拡張機能が追加されること。

### Environment

- OS: Debian
- OS Version: 12.1
- PostgreSQL Version: 15.X
- PGroonga: postgresql-15-pgdg-pgroonga

### Additional context

「libarrow.so.1500」では発生しないエラーであるため、
「libarrow.so.1600」の問題の可能性があります。

**Comment by kou** [comment]
いやぁ、そうなんですよ。

原因は https://github.com/apache/arrow/issues/41679 なんですが、とりあえず`apt install`に`libarrow1600=16.0.0-1`を追加して明示的に少し古い`libarrow1600`をインストールするようにして回避してもらえますか？

**Comment by kou** [comment]
Groongaのパッケージを`libarrow1600=16.1.0-1`用にリビルドすることでも回避できるので、もう少ししたらGroongaの新しいバージョンがリリースされて回避される予定でもあります。

**Comment by kou** [comment]
Groongaの新しいバージョンがリリースされたので回避されるようになったはずです。
（ただし、`libarrow1600=16.0.0-1`とは使えなくなる。）

**Comment by delhicurry** [comment]
回避されるようになっていました。
確認したバージョンは、下記になります。

> # apt show postgresql-15-pgdg-pgroonga
> Package: postgresql-15-pgdg-pgroonga
> Version: 3.2.0-1
> Status: install ok installed
> Priority: optional
> Section: database
> Maintainer: PGroonga Project <packages@groonga.org>
> Installed-Size: 2,380 kB
> Depends: libc6 (>= 2.33), libgroonga0 (>= 14.0.2), libmsgpackc2 (>= 2.1.0), postgresql-15

**Comment by kou** [comment]
よかったです！
