### ISSUE TITLE
pgroonga.score() always returns 0 if primary key type is text

### ISSUE THREAD

**Issue by magai** [pgroonga/pgroonga#49]
CentOS 6
PostgreSQL 9.3.17
PGroonga 1.2.3
Groonga 1.3.0-1
groonga-devel, groonga-libs 7.0.4-1.el6

上記の環境で、PRIMARY KEYがTEXTのみのとき、pgroonga.score()が常に0を返します。
簡単に試した限りでは、検索結果そのものには影響がないようでした。

**Comment by magai** [comment]
再現クエリです。
https://github.com/pgroonga/pgroonga/blob/04cf77108cf5ad91c41700e1ffef28c63edd9e9b/sql/full-text-search/text/single/score/and.sql
の型を変えただけです。

```sql
CREATE TABLE memos (
  id TEXT PRIMARY KEY,
  content text
);

INSERT INTO memos VALUES (1, 'PostgreSQL is a RDBMS.');
INSERT INTO memos VALUES (2, 'Groonga is fast full text search engine.');
INSERT INTO memos VALUES (3, 'PGroonga is a PostgreSQL extension that uses Groonga.');

CREATE INDEX grnindex ON memos USING pgroonga (id, content);

SET enable_seqscan = off;
SET enable_indexscan = on;
SET enable_bitmapscan = off;

SELECT id, content, pgroonga.score(memos)
  FROM memos
 WHERE content %% 'PGroonga' AND content %% 'Groonga';

DROP TABLE memos;
```

**Comment by kou** [comment]
ありがとうございます！

```sql
CREATE INDEX grnindex ON memos USING pgroonga (id pgroonga.text_term_search_ops_v2, content);
```

というように`text`なプライマリーキーには`pgroonga.text_term_search_ops_v2`を指定してください。

**Comment by magai** [comment]
`pgroonga.text_term_search_ops_v2`の指定でTEXTなPRIMARY KEYでもスコア出ること確認できました。ありがとうございました。
