### ISSUE TITLE
ci package: migrate test environment from Docker to Incus base

### ISSUE THREAD

**Issue by otegami** [pgroonga/pgroonga#507]
### What is your problem?

We need to test new features involving `systemd`.
Our current `Docker` based environment can't handle these tests.
Switching to `Incus` will allow us to create a virtual environment that supports systemd-related testing.

TODO
For only AlmaLinux8/9 at first
- [ ] Pending: Update base runner image to Ubuntu 24.04
  - ~~Because installing libc-bin failed, it will be fixed on upstream.~~
- [x] Install Incus
- [ ] Prepare container
- [ ] Execute test on Incus VM

If we needed, we will use Incus for the other OSs
- [ ] Reflect the other OSs
- [ ] Remove Docker-base tests

**Comment by otegami** [comment]
>  Install Incus

こちらの対応を進めていく。

**Comment by otegami** [comment]
Ubuntu noble から Incus をそのまま使えるので、Runner image を更新して問題なさそうだったら PR にする。
- https://packages.ubuntu.com/search?searchon=sourcenames&keywords=incus

**Comment by otegami** [comment]
GtiHub Actions Runner に Ubuntu 24.04 を指定した見たが、下記のエラーで一部の CI が落ちている。
手元で試してみて再現しそうだったら upstream に報告する。
```
175.0 Segmentation fault (core dumped)
175.0 dpkg: error processing package libc-bin (--configure):
175.0  installed libc-bin package post-installation script subprocess returned error exit status 139
175.0 Processing triggers for ca-certificates (20230311ubuntu0.22.04.1) ...
175.1 Updating certificates in /etc/ssl/certs...
187.4 0 added, 0 removed; done.
187.4 Running hooks in /etc/ca-certificates/update.d...
187.4 done.
```
ref: https://github.com/otegami/pgroonga/actions/runs/9740902554/job/26879034230

**Comment by otegami** [comment]
おそらく起因となっている現状が既に報告として上がっている
- https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/2055837

**Comment by kou** [comment]
なぜそれが関係していると判断したかも書いておいたほうがいいんじゃないかな。

**Comment by otegami** [comment]
ちゃんと分かっていないくて調べています。

**Comment by otegami** [comment]
ちょっと状況を整理する

**Comment by otegami** [comment]
問題が起こっている環境としては下記のような状況
- OS: Ubuntu 24.04(GitHub Actions Runner Image)
- Docker v xxx
- Docker image arm64

**Comment by kou** [comment]
QEMUも関係しているかも。

**Comment by otegami** [comment]
> QEMUも関係しているかも。

かなり前のなんですが似たような下記の Issue も上がっていそうです。
- https://github.com/docker/buildx/issues/314

**Comment by otegami** [comment]
手元で確認用の環境を作ろうとしていたのですが、少し時間がかかりそうなので、
先に `ubuntu-latest` をベースにしてテストが実行できるところまで目指そうと思います。

**Comment by otegami** [comment]
>  Install Incus

**Comment by otegami** [comment]
> Prepare container
