### ISSUE TITLE
Different results of `&@` with index or without

### ISSUE THREAD

**Issue by LylovaS** [pgroonga/pgroonga#524]
### What happened?

I created a table with two identical text columns. Than I created an index for one of the columns. 
After that search for each of the columns returns a different result.

### How to reproduce it

Table creation:
```SQL
DROP TABLE IF EXISTS memos;

CREATE TABLE memos (
  id integer,
  content1 text,
  content2 text
);

CREATE EXTENSION IF NOT EXISTS pgroonga;
CREATE INDEX content2_index ON memos USING pgroonga (content2);

INSERT INTO memos VALUES (1, 'abracadabra', 'abracadabra');

SET enable_seqscan = off;
```

Query
```SQL
SELECT * FROM memos WHERE content1 &@ 'b';
```
returns 1 row.

Query
```SQL
SELECT * FROM memos WHERE content2 &@ 'b';
```
returns 0 row.

### Expected behavior

The same results are returned when searching by index and without.

### Environment

- OS: Ubuntu
- OS Version: Ubuntu 24.04 LTS
- PostgreSQL Version: 16.3
- PGroonga Version: 3.2.2
- libgroonga Version: 14.0.5

**Comment by otegami** [comment]
Thank you for using PGroonga!

In this case, you can get the same result using the `TokenNgram` tokenizer like the following.
ref: https://groonga.org/docs/reference/tokenizers/token_ngram.html#tokenngram

The reason you got the different result is that the default index uses `TokenBigram` and `NormalizerAuto`, and `TokenBigram` tokenizes the text using spaces in this combination.
ref: https://pgroonga.github.io/reference/create-index-using-pgroonga.html#customization

```sql
CREATE INDEX content2_index
          ON memos
       USING pgroonga (content2)
        WITH (tokenizer='TokenNgram("unify_alphabet", false)');

INSERT INTO memos VALUES (1, 'abracadabra', 'abracadabra');

SET enable_seqscan = off;

SELECT * FROM memos WHERE content1 &@ 'b';
SELECT * FROM memos WHERE content2 &@ 'b';
```

---

The following is my suggestion.
If you want to ensure consistent behavior between index usage and sequential search, we recommend using `pgroonga_condition`.
By using `pgroonga_condition`, you can maintain consistent search results even when falling back to sequential search, as it utilizes the tokenizer information specified in the index.

If you could provide more details about your specific search targets and queries, we might be able to offer more tailored suggestions.

```sql
CREATE TABLE memos (
  id integer,
  phone_number text
);

CREATE EXTENSION IF NOT EXISTS pgroonga;

CREATE INDEX pgroonga_phone_number_index
          ON memos
       USING pgroonga (phone_number)
        WITH (tokenizer='TokenNgram("loose_symbol", true)');

INSERT INTO memos VALUES (1, '090-1234-4567');

SET enable_seqscan = off;

SELECT * FROM memos WHERE phone_number &@ '09012344567';

SET enable_seqscan = on;
SET enable_indexscan = off;
SET enable_bitmapscan = off;

-- # There is no result because we couldn't use the index with tokenizer.
SELECT * FROM memos WHERE phone_number &@ '09012344567';
-- # There is a result because we could use the information about the toknizwer without index.
SELECT * FROM memos WHERE phone_number &@ pgroonga_condition('09012344567', index_name => 'pgroonga_phone_number_index');
```
