### ISSUE TITLE
pgroonga returns wrong result on value = any(empty array)

### ISSUE THREAD

**Issue by tedypranolo** [pgroonga/pgroonga#53]
The pgroonga index was created by including the table primary key. If we query rows where id= any(array)  and  the array is empty, it will return all rows instead of 0 row.
There are two problems with this.

- For some reason postgres choose to use the pgroonga index over the PK index. Even if the select clause only includes the pk column
-  The `any` comparison is wrong if the array is empty

If the array is not empty or the pgroonga index is dropped, the query returns 0 row as expected.

```
CREATE TABLE score_memos
(
  id INTEGER NOT NULL,
  text     TEXT,

  CONSTRAINT pk_score_memos
  PRIMARY KEY (id)
);


CREATE INDEX pgroonga_score_memos_content_index
  ON score_memos USING pgroonga(id, TEXT);


INSERT INTO score_memos (id,text) VALUES (1, 'PostgreSQL is a relational database management system.');
INSERT INTO score_memos (id,text) VALUES (2,  'PGroonga is a PostgreSQL extension that uses Groonga as index.');

SELECT id
FROM score_memos
WHERE id = ANY (ARRAY [] :: INT []);
```
Explain analyse:
```
Index Only Scan using pgroonga_score_memos_content_index on score_memos  (cost=0.00..4.01 rows=1 width=36) (actual time=0.277..0.280 rows=2 loops=1)
  Index Cond: (id = ANY ('{}'::integer[]))
  Heap Fetches: 2
Planning time: 0.086 ms
Execution time: 0.402 ms

```

**Comment by kou** [comment]
I've implemented at master.
