### ISSUE TITLE
Rotate pgroonga.log with `--log-rotate-threshold-size` of Groonga

### ISSUE THREAD

**Issue by abetomo** [pgroonga/pgroonga#532]
### What is your problem?

I would like to rotate pgroonga.log with Groonga's `--log-rotate-threshold-size`.
The idea is to set it with a parameter like `pgroonga.log_rotate_threshold_size`.

**Comment by ghevge** [comment]
Thanks for looking into this feature! Will it be made available in the next release ?

**Comment by abetomo** [comment]
Yes, it will be available in the next release.
