### ISSUE TITLE
ERROR: pgroonga: object isn't found: Where: parallel worker with deprecated @@ operator

### ISSUE THREAD

**Issue by tedypranolo** [pgroonga/pgroonga#59]
The error :[42602] ERROR: pgroonga: object isn't found: <Sources244980> Where: parallel worker

I'm now using 2.0.3 and the &@ operator. This issue may be irrelevant since @@ is deprecated, but I'm reporting just in case the underlying problem also affects the &@. The issue is hard to reproduce, so far I only found 1 specific query that cause the error.

```
SELECT *
FROM jmdict.entrytext et
WHERE
  et.searchtext @@ 'どう'
OFFSET 100000
LIMIT 20;
```
This only affects どう (I haven't found other example or any pattern), but only when the offset is beyond available data. I tried to create another table with different partial data of the original table, I wasn't able to reproduce the error with any @@ query.

**Comment by kou** [comment]
Can you show `EXPLAIN ANALYZE VERBOSE SELECT ...THIS QUERY...`?

**Comment by tedypranolo** [comment]
I tried to get EXPLAIN ANALYZE VERBOSE for the @@ query, but if the query is not working, the explain analyze also throws the same error.
After some more testing.
**Without offset/limit, error, can't get query plan**
```
SELECT *
FROM jmdict.entrytext et
WHERE
  et.searchtext @@ 'どう'
```
**With offset/limit but beyond available data, error, can't get plan**
```
 SELECT *
FROM jmdict.entrytext et
WHERE
  et.searchtext @@ 'どう'
offset 100000
limit 10;
```
**With offset/limit but within available data, working**
```
SELECT *
FROM jmdict.entrytext et
WHERE
  et.searchtext @@ 'どう'
OFFSET 10
LIMIT 20;
```
Plan
```
QUERY PLAN
Limit  (cost=112.29..224.12 rows=10 width=52) (actual time=6.183..6.191 rows=10 loops=1)
"  Output: entryid, num, conjupostagid, conjustem, haskanji, orghaskanji, orgnum, searchtext, text"
  ->  Bitmap Heap Scan on jmdict.entrytext et  (cost=0.46..20520.93 rows=1835 width=52) (actual time=6.171..6.189 rows=20 loops=1)
"        Output: entryid, num, conjupostagid, conjustem, haskanji, orghaskanji, orgnum, searchtext, text"
        Recheck Cond: (et.searchtext @@ 'どう'::text)
        Heap Blocks: exact=17
        ->  Bitmap Index Scan on ix_entrytext_searchtext_pgroonga  (cost=0.00..0.00 rows=11233 width=0) (actual time=5.480..5.480 rows=11231 loops=1)
              Index Cond: (et.searchtext @@ 'どう'::text)
Planning time: 0.407 ms
Execution time: 6.917 ms
```

**Comment by tedypranolo** [comment]
I just remembered while I can't run the EXPLAIN ANALYSE, I can still use EXPLAIN. Hopefully this will be useful
```
QUERY PLAN
Limit  (cost=20000.76..20011.12 rows=1 width=52)
"  Output: entryid, num, conjupostagid, conjustem, haskanji, orghaskanji, orgnum, searchtext, text"
  ->  Gather  (cost=1000.46..20000.76 rows=1835 width=52)
"        Output: entryid, num, conjupostagid, conjustem, haskanji, orghaskanji, orgnum, searchtext, text"
        Workers Planned: 2
        ->  Parallel Bitmap Heap Scan on jmdict.entrytext et  (cost=0.46..18817.26 rows=765 width=52)
"              Output: entryid, num, conjupostagid, conjustem, haskanji, orghaskanji, orgnum, searchtext, text"
              Recheck Cond: (et.searchtext @@ 'どう'::text)
              ->  Bitmap Index Scan on ix_entrytext_searchtext_pgroonga  (cost=0.00..0.00 rows=11233 width=0)
                    Index Cond: (et.searchtext @@ 'どう'::text)

```

**Comment by tedypranolo** [comment]
I managed to isolate the table, but I wasn't able to isolate the offending row. When I tried to delete some of the rows, the problem was not reproducible. Here's about 1.8 million rows that exhibits the issue.
[ejisho_debug_entrytext.zip](https://github.com/pgroonga/pgroonga/files/1801308/ejisho_debug_entrytext.zip)
Hopefully that will help.

**Comment by kou** [comment]
Thanks.
I've fixed it at master

**Comment by tedypranolo** [comment]
Awesome. Thank you.
