### ISSUE TITLE
regexp-v2/regexp-condition-v2: add tests for cases we specify NULL into pattern

### ISSUE THREAD

**Issue by komainu8** [pgroonga/pgroonga#591]
### What is your problem?

PGroonga is occurred error when we specify NULL into pattern.
However, PGroonga has not tests for confirming this error.

We should add tests for this case.

```sql
CREATE TABLE memos (
  content text[]
);

INSERT INTO memos
     VALUES (ARRAY['PostgreSQL is a RDBMS',
                   'Groonga is fast full text search engine',
                   'PGroonga is a PostgreSQL extension that uses Groonga']);

INSERT INTO memos
     VALUES (ARRAY['MySQL is a RDBMS',
                   'Mroonga is a MySQL storage engine that uses Groonga']);

CREATE INDEX pgrn_content_index
    ON memos
 USING pgroonga (content pgroonga_text_array_regexp_ops_v2);

SET enable_seqscan = off;
SET enable_indexscan = on;
SET enable_bitmapscan = off;

SELECT *
  FROM memos
 WHERE content &~ pgroonga_condition(NULL,
                                     index_name => 'pgrn_content_index');
ERROR:  pgroonga: [build-condition][regexp-condition] query must not NULL

DROP TABLE memos;
```

---

We will support the following operators.

### &~(targets text[], pattern text)

- [x] #594

### &~(targets text[], condition pgroonga_condition)

- [x] `indexscan`/`bitmapscan` #592
- [x] `secscan` #593

### &~(targets text, pattern text)

- [x]  #595

### &~(targets varchar, pattern text)

- [x] #596

**Comment by kou** [comment]
`STRICT`を指定しているのでそうなります。
https://www.postgresql.org/docs/current/sql-createfunction.html

**Comment by kou** [comment]
あぁ、`regexp-condition-v2`も同じ挙動にするべき？

**Comment by komainu8** [comment]
> `STRICT`を指定しているのでそうなります。 https://www.postgresql.org/docs/current/sql-createfunction.html

おぉ。そのようなパラメーターがあったとは。。。ありがとうございます。

**Comment by komainu8** [comment]
> あぁ、`regexp-condition-v2`も同じ挙動にするべき？

そうですね。そんな気がします。別途対応しようかと思います。

**Comment by komainu8** [comment]
`STRICT`を指定しているので、

```
--         QUERY PLAN        
-- --------------------------
--  Result
--    One-Time Filter: false
-- (2 rows)
```

となって、何もレコードを返さない挙動で正しいから、これを確認するテストをつくる。

**Comment by komainu8** [comment]
対応済みのためCloseします。
