### ISSUE TITLE
Scoring exact matches

### ISSUE THREAD

**Issue by tedypranolo** [pgroonga/pgroonga#62]
Right now it seems that scoring is based how many times the keyword is found. I'm using pgroonga to match a column containing a single word/sentence instead of a whole document. So the keyword is almost never repeated within the column. It would be more useful if I can score exact matches differently from partial matches. Is that possible?
Example:
textcolumn &@ 'eat'

'eat' | score= 0
'To eat a banana'  | score = 1
'What did you eat' | score = 1

**Comment by kou** [comment]
Umm. You can't do this with the current PGroonga.

**Comment by tedypranolo** [comment]
I see. I was hoping it's possible to order the results by exact matches first.
Thank you.

**Comment by kou** [comment]
You may implement it by using regular expression index: https://pgroonga.github.io/reference/operators/regular-expression-v2.html

```sql
select pgroonga_score(tableoid, ctid) as score
  from table
 where textcolumn &@ 'eat' OR
       textcolumn &~ '\Aeat\z'
 order by score desc;
```
