### ISSUE TITLE
Internal subtransations not supported in Postgres-XL

### ISSUE THREAD

**Issue by CGSgeosite** [pgroonga/pgroonga#63]
# create extension pgroonga;
ERROR: Internal subtransations not supported in Postgres-XL
CONTEXT: PL/pgSQL function inline_code_block line 2 during statement block ectry

**Comment by kou** [comment]
Please report it to PostgreSQL-XL.

**Comment by CGSgeosite** [comment]
thank U
pgroonga is very very ... great

**Comment by kou** [comment]
Thanks.
