### ISSUE TITLE
PostgreSQL 10 for Debian repository

### ISSUE THREAD

**Issue by ikamil** [pgroonga/pgroonga#65]
Debian 9 Stretch
We have PostgreSQL 10 released, 11 is coming soon.
BUT!
Found only 9.6 PostgreSQL:

root@web-lvk:/home/kam# apt-cache search pgroonga
postgresql-9.6-pgroonga-dbgsym - Debug symbols for postgresql-9.6-pgroonga
postgresql-9.6-pgroonga - Fast full-text search plugin for PostgreSQL based on Groonga

How to install PostgreSQL 10 PGRoonga for Debian 9?

THanks.

**Comment by kou** [comment]
You can install PGroonga for PostgreSQL 10 by building from source: https://pgroonga.github.io/install/source.html

We will provide packages for Debian + PostgreSQL 10 when Debian 10 is released. Because Debian 10 will ship PostgreSQL 10.

Or you can use Ubuntu 18.04 to install PGroonga for PostgreSQL 10 by package.

**Comment by ikamil** [comment]
Is it possible to include into your repository apt from PostgreSQL, which ships from PG itself:

     deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main
     wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

As of, production PG is installed not directly from Debian default repo, but from PG repo.
So, you could just implicit that to your repo, and let users to user PG10 as well.

Can you please take a look on that?

**Comment by kou** [comment]
Done: https://pgroonga.github.io/install/debian.html#install-on-stretch

**Comment by ikamil** [comment]
Great, significant update, thanks

**Comment by weldomha** [comment]
same problem with pg11 and the upcomming pg12

**Comment by kou** [comment]
Please don't reuse closed issue.
