### ISSUE TITLE
Missing Docker image for PGroonga at Docker Hub

### ISSUE THREAD

**Issue by piroor** [pgroonga/pgroonga#66]
There is the groonga account at Docker Hub https://hub.docker.com/r/groonga/ but there is no image of PGroonga.

Moreover, usage of the Docker image should be described at: https://pgroonga.github.io/ja/install/ 

See also: https://github.com/clear-code/statistics/issues/139

**Comment by ZenLiuCN** [comment]
create a repo for this [pgroonga with postgres on docker alpine](https://github.com/ZenLiuCN/pgroonga-dockerl)

**Comment by kenhys** [comment]
@ZenLiuCN Good job!

Do you have curiocity about maintaining pgroonga docker image?
If you have, how about maintaining on repository under pgroonga?
(I mean https://github.com/pgroonga/docker. It is not created yet but If you want to maintain it, I'll create it and grant permission to you.)

In Groonga's case, we have already https://github.com/groonga/docker/ repository and maitained by community (https://hub.docker.com/r/groonga/groonga/). It seems better to do like that.

**Comment by kenhys** [comment]
@ZenLiuCN Thanks!
No problem, it is good enougth to do as you can. Contributing for community is great thing and wellcome.

Now https://github.com/pgroonga/docker is ready and invited you as a collabolator.
Could you check invite mail, please?

**Comment by kenhys** [comment]
@ZenLiuCN 
It seems that you are added as repository's collaborator, it is not unexpected.
So, invited as team collaborator again. Maybe invite email is sent to you.  Could you confirm again, please?

**Comment by kenhys** [comment]
@ZenLiuCN 
Hi, now PGroonga organization is ready on Docker Hub, so we want to invite you.
Do you have already account on Docker Hub? If so, could you tell us your account name, please?
We will add you to PGroonga team on Docker Hub.

**Comment by kenhys** [comment]
Hi, @ZenLiuCN , I've add above account to pgroonga team!

**Comment by ZenLiuCN** [comment]
I think this tissue could be closed.
now we got a  seems *useable* docker images on docker hub [groonga/pgroonga](https://hub.docker.com/r/groonga/pgroonga)

**Comment by ZenLiuCN** [comment]
@kenhys I just closed *autobuild* on Docker hub, if any updates will need to build by hand
