### ISSUE TITLE
Windows installation on Postgres 10.4

### ISSUE THREAD

**Issue by PlkMarudny** [pgroonga/pgroonga#67]
Hi, I am having trouble installing pgroonga: the installation docs just says to copy some files into some locations. Postgres 10.4 defaults to C:\Postgres10 as an installation directory, so the PATH is set to: **C:\PostgreSQL10\pg10\bin** .I tried to manually copy extracted pgroonga files into directories, but no success. Trying to issue a command:

`CREATE EXTENSION pgroonga`

produces an error: 

`ERROR:  could not access file "$libdir/pgroonga": No such file or directory`

Issuing **pg_config** shows that $LIBDIR is located:

`LIBDIR = C:/POSTGR~2/pg10/lib`

There are files **pgroonga.dll**, **pgroonga.lib**, **pgroonga_check.dll**, **pgroonga_check.lib** in this directory along with a **groonga** dir, but building the extension fails. This is all happening on Windows 64, Server 2012. How can I install **pgroonga** correctly?

**Comment by kou** [comment]
Can you show file tree after you install PGroonga?

**Comment by PlkMarudny** [comment]
Hi, I have found the solution. In fact, files from the \lib directory of the zip file should be placed not in the **$LIBDIR**, but in the **$PGKLIBDIR**, that are not the same on my installation:

`LIBDIR = C:/POSTGR~2/pg10/lib`
`PKGLIBDIR = C:/POSTGR~2/pg10/lib/POSTGR~1`

So simply unzipping the files does not always work.

**Comment by kou** [comment]
Zip archive https://www.enterprisedb.com/download-postgresql-binaries version uses `lib/`.
So I think that installer version users should move PGroonga related files by yourself.

**Comment by PlkMarudny** [comment]
Guess this should be mentioned in the installation manual

**Comment by kou** [comment]
It's a good idea.
Do you want to create a pull request for https://github.com/pgroonga/pgroonga.github.io ?

**Comment by PlkMarudny** [comment]
I will

**Comment by CGSgeosite** [comment]
@postgresql 11

**Comment by kou** [comment]
@CGSgeosite You should not reuse existing issue. You should create a new issue for new topic.
