### ISSUE TITLE
Tutorial example "Score" not workong

### ISSUE THREAD

**Issue by Pentusha** [pgroonga/pgroonga#75]
Hello again :smile: I'm trying to execute tutorial examples and this code:

```sql
CREATE TABLE score_memos (
  id integer PRIMARY KEY,
  content text
);

CREATE INDEX pgroonga_score_memos_content_index
          ON score_memos
       USING pgroonga (content);

INSERT INTO score_memos VALUES (1, 'PostgreSQL is a relational database management system.');
INSERT INTO score_memos VALUES (2, 'Groonga is a fast full text search engine that supports all languages.');
INSERT INTO score_memos VALUES (3, 'PGroonga is a PostgreSQL extension that uses Groonga as index.');
INSERT INTO score_memos VALUES (4, 'There is groonga command.');

SELECT *, pgroonga_score(tableoid, ctid) AS score
  FROM score_memos
 WHERE content &@ 'PGroonga' OR content &@ 'PostgreSQL'
 ORDER BY pgroonga_score(score_memos) DESC;
```
gives me this output:
```csv
"id";"content";"score"
1;"PostgreSQL is a relational database management system.";1
3;"PGroonga is a PostgreSQL extension that uses Groonga as index.";2
```
| id | content                                                        | score | 
|----|----------------------------------------------------------------|-------| 
| 1  | PostgreSQL is a relational database management system.         | 1     | 
| 3  | PGroonga is a PostgreSQL extension that uses Groonga as index. | 2     | 

As you can see it is not descent order.
``pgroonga_score(score_memos)`` always returns 0, so should I order by `pgroonga_score(tableoid, ctid)`?

**Comment by kou** [comment]
Ah, it's a document bug.
`pgroonga_score(score_memos)` should be `pgroonga_score(tableoid, ctid)`.
Can you send a pull request?

If we want to use `pgroonga_score(score_memos)`, we need to add the primary key to indexed columns:

```sql
CREATE INDEX pgroonga_score_memos_content_index
          ON score_memos
       USING pgroonga (id, content);
```
