### ISSUE TITLE
Non-administrator can't execute create index ...(column pgroonga.text_regexp_ops)

### ISSUE THREAD

**Issue by hiroyuki-sato** [pgroonga/pgroonga#8]
https://github.com/pgroonga/pgroonga/blob/master/sql/regexp/text/regexp/partial/indexscan.sql

It is possible to execute ``create index .. using pgroonga(... pgroonga.text_regexp_ops)`` command by non-administrator user?

```
CREATE INDEX grnindex ON memos USING pgroonga (content pgroonga.text_regexp_ops);
ERROR:  permission denied for schema pgroonga
```

User can't execute ``create index`` command after grant command.

```
grant ALL on ALL TABLES IN SCHEMA pgroonga to user;
```

```
grant ALL on SCHEMA pgronga to user;
ERROR:  schema "pgronga" does not exist
```

Thanks.

**Comment by kou** [comment]
> ```sql
> grant ALL on SCHEMA pgronga to user;
> ```

Is `pgronga` typo?

**Comment by hiroyuki-sato** [comment]
Sorry that was typo.

I retried. but I got same error. 

```
grant ALL on SCHEMA pgroonga to user;
ERROR:  schema "pgroonga" does not exist
STATEMENT:  grant ALL on SCHEMA pgroonga to hsato;
ERROR:  schema "pgroonga" does not exist
``

**Comment by hiroyuki-sato** [comment]
Probably I missed execute create extension on specific database.
I succeed to grant schema on Linux/OSX platform.

```
create extension pgroonga;
CREATE EXTENSION
pgroonga_test=# \dn
   List of schemas
   Name   |  Owner   
----------+----------
 pgroonga | postgres
 public   | postgres
(2 rows)

pgroonga_test=# grant ALL on SCHEMA pgroonga to user;
GRANT
```
