### ISSUE TITLE
crash groonga/pgroonga and PostgreSQL go to recovery mode

### ISSUE THREAD

**Issue by dodaisuke** [pgroonga/pgroonga#80]
groongaがクラッシュし、そのタイミングでPostgreSQLがリカバリモードになる、という現象です。
今のところ、どのようなタイミング、どのようなクエリで同じ現象が発生するのか、分かっておりません。
再現性等が判明しましたら、追記させていただきます。

■利用している環境
- CentOS6 64bit
- PostgreSQL 9.5.6
 - groonga 8.0.5
- pgroonga 2.1.1

■インデックス定義
```
CREATE TABLE product_0 (
    id integer,
    … ※snip
) INHERITS (product);
CREATE INDEX product_full_text_search_part_00_idx01
    ON product_0 USING pgroonga
    (id, name, …); ※snip

CREATE TABLE product_1 (
    id integer,
    … ※snip
) INHERITS (product);
CREATE INDEX product_full_text_search_part_01_idx01
    ON product_1 USING pgroonga
    (id, name, …);  ※snip
```
pgroonga.log, postgresql-XXX.log は添付いたします。
[logs.zip](https://github.com/pgroonga/pgroonga/files/2330875/logs.zip)

どうぞよろしくお願いいたします。

**Comment by dodaisuke** [comment]
追記いたします。
```
select pgroonga_query_expand('synonyms', 'term', 'synonyms', 'ウォータープルーフ')
[2018-08-29 17:03:36] [42602] ERROR: pgroonga: object isn't found: <Sources3358266277>
```
上記のように、特定の関数が見つけられない、といった状態になってしまったようです。
※この際pgroonga.logには何も出力されておりませんでした。

現在pgroongaを再インストールし直して（上記の状況を解消させて）再度検証しております。

**Comment by kou** [comment]
クラッシュ時のバックトレースにもう少し情報が増えるかもしれないので``postgresql95-pgroonga-debuginfo`もインストールしておいてもらえますか？

**Comment by dodaisuke** [comment]
了解しました！
インストール後、同現象が発生しましたらまたログファイル添付させていただきます。

**Comment by kou** [comment]
ちなみに再インストールとはどのような作業をしましたか？

**Comment by dodaisuke** [comment]
> 再インストールとはどのような作業をしましたか？

以下のSQLを実行いたしました。
```
DROP EXTENSION pgroonga CASCADE;
DELETE FROM pg_catalog.pg_am WHERE amname = 'pgroonga';
CREATE EXTENSION pgroonga;
```

そして失礼しました、もう1点お伝えする情報が漏れておりました。
何度かクラッシュすることが分かったあと、8/21にサーバのメモリを大幅に増設しました。
※16GB → 48GB
メモリ不足によるもの？と思われるログが散見されたためです。
このとき合わせてディスクも増設しています。
※容量の大きなディスクをマウント、DBのデータ領域を丸ごとコピー、といった作業です。

そのためこちらの問題は解消したかな？と思われましたが、再度クラッシュが発生してしまった、という状況になります。
なおovercommit-memoryに関しては、検証中のサーバにはswapを設けておりませんので2の設定のまま、としてあります。

> プロセス終了時の終了処理中にクラッシュしている

そうなのですね、深夜帯ですので、人為的な操作はなくアプリケーションのバッチ処理が実行されている時間帯なのですが、、、
debuginfoをインストールしてありますので、再現するようであればもう少し詳細情報が分かるかもしれません。
`2018-08-03T00:13:33`の時点でどのようなクエリが実行されていたのか、ということは現象発見時点でログが流れてしまっており分からないのですが、`/var/log/messages`にはpostgresプロセスがコアダンプした、という情報が残っていました。
※その後すぐabrtdに消されてしまったようですが。。

ひとまず再現を待って、より調査を進めたいと思います。

**Comment by kou** [comment]
念のため、PGroonga関連ファイルをキレイにしてみてもらってもいいですか？過去のクラッシュの影響が残っていると次に再現したときに調査しにくくなるためです。手順は以下の通りです。データの再投入などは必要ありません。

1. PostgreSQLを停止
2. `DB_DIR/pgrn*`を全部削除（`rm`）
3. PostgreSQLを起動
4. `REINDEX`でPGroongaのインデックスをすべて再生成

**Comment by dodaisuke** [comment]
了解しました、いただいた手順でPostgreSQLを再起動しインデックス再作成しておきました。

**Comment by kou** [comment]
ありがとうございます！

**Comment by dodaisuke** [comment]
2日間ほど経過しましたが、本日再度クラッシュしていましたので共有いたします。
何度かクラッシュしておりますが、最初のクラッシュは`2018-08-31 03:57:19`かと思います。
この際走っていたクエリはやはりインデックス対象テーブルをDELETE/INSERTする関数です。
※クエリ実行前にロック取得待ち、ロック取得という流れがあるようです。

[logs.zip](https://github.com/pgroonga/pgroonga/files/2339401/logs.zip)

どうぞよろしくお願いします。

**Comment by dodaisuke** [comment]
ご連絡ありがとうございます。

> PGroongaのmasterをデバッグビルドしてログレベルをdebugにして再度再現

はい、こちら可能です！

現在は、postgresが同じようなタイミングでコアダンプしているのですが、abrtdがデフォルトでダンプファイルを消してしまっていたので、消さないように設定して再現を待っているところです。
※コアダンプの解析で何が分かるか、分かりませんが。。

なお、並行して別サーバの準備ができましたので（環境はほぼ同じです）、こちらでpostgres9.5の枝番をアップグレードさせて、同じ現象が発生するか検証しようとしています。

**Comment by kou** [comment]
ありがとうございます！

では、以下でお願いします。試していないのでエラーになったら教えてください。

```console
% sudo yum install -y git groonga-devel msgpack-devel postgresq95-devel
% git clone https://github.com/pgroonga/pgroonga.git
% cd pgroonga
% cat <<PKG_CONFIG > msgpack.pc
Name: MessagePack
Description: Binary-based efficient object serialization library
Version: 0.5.7
Libs: -L/usr/lib64 -lmsgpackc
Cflags: -I/usr/include
PKG_CONFIG
% PKG_CONFIG_PATH=$PWD make HAVE_MSGPACK=1 DEBUG=1
% sudo make install
```

これでインストールできます。

インストール後、`psql`でつないで`ALTER EXTENSION pgroonga UPDATE;`を実行してください。

参考： https://pgroonga.github.io/ja/upgrade/#compatible-case

あと、`postgresql.conf`に`pgroonga.log_level = debug`と書いてログレベルを上げてください。

参考： https://pgroonga.github.io/ja/reference/parameters/log-level.html

その後、 https://github.com/pgroonga/pgroonga/issues/80#issuecomment-417184069 と同じようにキレイにして再現を待ってください。

**Comment by dodaisuke** [comment]
ご連絡ありがとうございます。make時に以下のエラーで止まってしまいました。
```
$ PKG_CONFIG_PATH=$PWD make HAVE_MSGPACK=1 DEBUG=1
make -f pgroonga.mk all
make[1]: Entering directory `/root/tmp/pgroonga'
make[1]: *** No rule to make target `vendor/xxHash/xxhash.h', needed by `src/pgroonga.o'.  Stop.
make[1]: Leaving directory `/root/tmp/pgroonga'
make: *** [all] Error 2
```
パスが見つからない？系でしょうか、一応、以下の場所でコマンド実行しています。
```
$ ls
appveyor.yml  CMakeLists.txt  COPYING  data  examples  expected  Gemfile  Makefile  makefiles  msgpack.pc  packages  pgroonga-check.mk  pgroonga.control  pgroonga.mk  Rakefile  README.md  sql  src  test  test.sql  vendor
```
よろしくお願いいたします。

**Comment by dodaisuke** [comment]
```
$ ls -al vendor/xxHash/
合計 8
drwxr-xr-x 2 postgres postgres 4096  9月  4 14:43 2018 .
drwxr-xr-x 3 postgres postgres 4096  9月  4 14:43 2018 ..
```
このような状況で、cloneしたファイル？が存在しないでしょうか・・？
```
$ git branch -a
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/master
```
一応、cloneした状態は上記の通りです。。

**Comment by kou** [comment]
あぁ、すみません。

`pgroonga/`ディレクトリーで`git submodule update --init`を実行してください。

**Comment by dodaisuke** [comment]
なるほどです！ありがとうございます。

**Comment by dodaisuke** [comment]
```
$ PKG_CONFIG_PATH=$PWD make HAVE_MSGPACK=1 DEBUG=1
make -f pgroonga.mk all
make[1]: ディレクトリ `/var/lib/pgsql/tmp/pgroonga' に入ります
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -DLINUX_OOM_ADJ=0 -Ivendor/xxHash -DPGRN_HAVE_MSGPACK -DPGRN_VERSION="\"2.1.2\"" -O0 -g3 -DPGROONGA_DEBUG=1 -fpic -I/usr/include/groonga   -I. -I./ -I/usr/pgsql-9.5/include/server -I/usr/pgsql-9.5/include/internal -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o src/pgroonga.o src/pgroonga.c
src/pgroonga.c: In function ‘PGrnGetType’:
src/pgroonga.c:625: 警告: implicit declaration of function ‘TupleDescAttr’
src/pgroonga.c:625: 警告: assignment makes pointer from integer without a cast
src/pgroonga.c: In function ‘PGrnCreateCheckType’:
src/pgroonga.c:972: 警告: assignment makes pointer from integer without a cast
src/pgroonga.c: In function ‘PGrnCreate’:
src/pgroonga.c:1009: 警告: assignment makes pointer from integer without a cast
src/pgroonga.c: In function ‘PGrnSetSources’:
src/pgroonga.c:1044: 警告: initialization makes pointer from integer without a cast
src/pgroonga.c: In function ‘pgroonga_score_row’:
src/pgroonga.c:1365: error: invalid type argument of ‘->’ (have ‘int’)
src/pgroonga.c: In function ‘PGrnNeedMaxRecordSizeUpdate’:
src/pgroonga.c:3685: 警告: assignment makes pointer from integer without a cast
src/pgroonga.c: In function ‘PGrnInsert’:
src/pgroonga.c:3768: error: invalid type argument of ‘->’ (have ‘int’)
src/pgroonga.c:3846: 警告: initialization makes pointer from integer without a cast
src/pgroonga.c: In function ‘PGrnPrimaryKeyColumnsInit’:
src/pgroonga.c:4012: error: invalid type argument of ‘->’ (have ‘int’)
src/pgroonga.c:4016: error: invalid type argument of ‘->’ (have ‘int’)
src/pgroonga.c: In function ‘PGrnSearchBuildCondition’:
src/pgroonga.c:4996: 警告: assignment makes pointer from integer without a cast
src/pgroonga.c: In function ‘PGrnSort’:
src/pgroonga.c:5380: 警告: assignment makes pointer from integer without a cast
src/pgroonga.c: In function ‘PGrnFillBorder’:
src/pgroonga.c:5500: 警告: assignment makes pointer from integer without a cast
src/pgroonga.c: In function ‘PGrnGetTupleFillIndexTuple’:
src/pgroonga.c:5773: 警告: initialization makes pointer from integer without a cast
src/pgroonga.c: In function ‘pgroonga_canreturn_raw’:
src/pgroonga.c:6552: 警告: initialization makes pointer from integer without a cast
make[1]: *** [src/pgroonga.o] エラー 1
make[1]: ディレクトリ `/var/lib/pgsql/tmp/pgroonga' から出ます
make: *** [all] エラー 2
```
上記のようなエラーで止まってしまいました。
gcc, gcc-c++（こちらは必要か分かりませんが）がコンパイル環境としてはインストール済みになっています。
環境的な不足がありそうな気がしますが、不足していそうな点を教えていただけると助かります。

どうぞよろしくお願いします。

**Comment by kou** [comment]
あぁ、PostgreSQLのマイナーバーバージョンが古いからな気がします。
`postgresq95-devel`のバージョンはいくつになっていますか？

**Comment by kou** [comment]
あぁ、古いやつでもビルドできるようにするほうがいいかしら。

**Comment by dodaisuke** [comment]
現状は9.5.6がインストールされています。
並行して9.5.14でも検証していますので、9.5.14での発生も確認しましたら、debugビルドして再現させてみる、というステップにしてみたいと思います。

9.5.14で発生しないようであれば、ひとまずビルド対応等も必要ないかな、と思いますので、少々お待ちいただければと思います。。
※経験上、おそらく明日には9.5.14の方でもクラッシュするかどうか分かるかと思います。

**Comment by kou** [comment]
わかりました。そうしましょう！

**Comment by dodaisuke** [comment]
9.5.14でもクラッシュしましたので、その際のログを添付いたします。
ただ、こちらデバッグモードではないようですので、取り急ぎの共有となります。
これからデバッグビルドを行い、再度ログ取得でき次第また添付いたします。
- PostgreSQL 9.5.14
- groonga 8.0.5
- pgroonga 2.1.2

※PostgreSQLとpgroongaのバージョンが初回に発生したものとは異なります。

**Comment by dodaisuke** [comment]
デバッグ状態でも再現しましたので、ログを添付させていただきます。
[logs.zip](https://github.com/pgroonga/pgroonga/files/2351996/logs.zip)

クラッシュ時刻は`2018-09-05 17:42:03`です。
参考になる情報があれば良いのですが。。どうぞよろしくお願いいたします。

**Comment by kou** [comment]
ありがとうございます。
参考になる情報がありました。

さらにログを追加したので`git pull`と`make`と`make install`と`pgrn`の削除をして再度再現させてもらえませんか？

**Comment by dodaisuke** [comment]
ご対応ありがとうございます！
ビルド＆pgrnをキレイにして、再度クラッシュを再現させてみました。

[logs.zip](https://github.com/pgroonga/pgroonga/files/2355832/logs.zip)

クラッシュ時刻は`15:35:48`です。
ファイルサイズが大きくなりすぎたために分割して時間近辺のログのみを抜粋しております。
必要でしたら、再度収集し直しますので指示いただければと思います。。

よろしくお願いいたします。

**Comment by kou** [comment]
ありがとうございます。
PostgreSQLの問題でした。

とりあえず、masterには回避策を入れておいたので`git pull`して試してみてもらえますか？

あと、PostgreSQL本体にこの問題を報告してもらえませんか？
（報告してくれるなら報告に必要な私が知っている情報を提供します。）

**Comment by dodaisuke** [comment]
ご連絡ありがとうございます、なんと本体側だったのですね。
原因が分かって良かったです・・！
PostgreSQL本体へのレポート、もちろん引き受けます、ご連絡お待ちしております。

回避策の件、これからビルドして検証してみます。
しばらく稼働させながら検証しますので、明日か、週明けにでも経過報告させていただきます。
よろしくお願いいたします。

**Comment by dodaisuke** [comment]
レポート方法まで、ありがとうございます！（お察しの通り、初レポートです。。）
いただいた情報を元にチケット上げてこようと思います。
本体側の修正アイディアまでいただき、助かります。

なお、回避策を入れていただいたソースで、現状クラッシュは発生しておりません。
※ある程度「こんな操作をすると発生する」という操作がありますが、その操作を行っても問題なく動作しております。
（`SELECT FOR UPDATE`的な操作が入る機能です。）

継続稼働させてもう数日様子を見たいと思います。
ご対応ありがとうございました。

**Comment by kou** [comment]
そうですね、本体で修正されるのが一番いいと思います。

（`SELECT FOR UPDATE`でエラーが発生したら再接続するようにするとクラッシュしなくなるかも。。。？）

**Comment by dodaisuke** [comment]
済みません、以下のように「エラーの場合はリソースは自動的に開放されます」といった回答をもらいました。。
https://www.postgresql.org/message-id/877ejsr4mw.fsf%40news-spur.riddles.org.uk

ひとまず、どう対応するかアプリケーション側の何らかの修正でくぐり抜ける方法がないか、検討してみます。。

**Comment by kou** [comment]
あぁ、ResourceOwnerを使えばいいんですか！
使うようにしてみたのでmasterを試してもらえますか？

**Comment by dodaisuke** [comment]
おお、ありがとうございます！
いまビルドしています、数日かかるかもしれませんが、またレポートさせていただきます！

**Comment by dodaisuke** [comment]
残念ながら？クラッシュしてしまいました。。
`2018-09-12 15:35:18`の時刻になります。
前後のデバッグログを添付しますので、ご参考になればと思います。
サイズの都合上より前のログを割愛しておりますので、必要であれば仰っていただければと思います。
[logs.zip](https://github.com/pgroonga/pgroonga/files/2373936/logs.zip)

どうぞよろしくお願いいたします。

**Comment by dodaisuke** [comment]
ありがとうございます、では新たにチケットを起票いたします。
よろしくお願いいたします。
