### ISSUE TITLE
Is there a way to match the whole column using &@~ query syntax?

### ISSUE THREAD

**Issue by tedypranolo** [pgroonga/pgroonga#81]
I'm have a postgres function to search using multi word queries `textcol &@~ groongaQuery` where the parameter is something like `groongaQuery='cat OR person'` . I'm trying to reuse the same function to search for exact whole column match by using a different groongaQuery. 
So if the table contains `cat `and `ninja cat`, I want to match only rows with  `textCol='cat'` but not `textCol='ninja cat'`.
Is this possible? The Groonga documentation says the syntax is `column:value`, but I can't find the Pgroonga equivalent.

**Comment by kou** [comment]
We can enable the feature by adding `GRN_EXPR_ALLOW_COLUMN` into `PGRN_EXPR_QUERY_PARSE_FLAGS` in PGroonga.
But it breaks backward compatibility. For example, we can't search `textCol:cat` itself by `textCol:cat`. We need to use `textCol\:cat`.

We can enable this feature with keeping backward compatibility by adding a new index option. With the new index option, we will be able to write the followings:

```sql
create index pgroonga_index
     on table
 using pgroonga (textCol)
   with (flags = 'ALLOW_LEADING_NOT|QUERY_NO_SYNTAX_ERROR|ALLOW_COLUMN');
```

**Comment by tedypranolo** [comment]
So this features requires a custom build of pgroonga. Is the column search an expensive operation? Is that why it's not included in the default build?

**Comment by kou** [comment]
It's just not implemented yet. :<

**Comment by tedypranolo** [comment]
I see :)  No worries, I will wait for that feature be implemented.
For now I can use `LIKE 'cat'`.
Thank you for all of your hard work on PGroonga. 👍

**Comment by tedypranolo** [comment]
Thanks for the tip.

**Comment by kou** [comment]
I've implemented this. The following should work at master:

```sql
create index pgroonga_index
     on table
 using pgroonga (textCol)
   with (query_allow_column = true);
select * from table textCol &@~ 'textCol:cat';
```
