### ISSUE TITLE
Crash on freeing PGrnScanOpaques

### ISSUE THREAD

**Issue by dodaisuke** [pgroonga/pgroonga#82]
https://github.com/pgroonga/pgroonga/issues/80

こちらから派生した問題となります。
pgroongaの最新のmasterをビルドし、デバッグログを取得しております。

[main-logs.zip](https://github.com/pgroonga/pgroonga/files/2374436/main-logs.zip)

インデックス定義は上記のissueを参照いただければと思います。
環境のみ、更新されていますので下記に改めて記載いたします。

■利用している環境

CentOS6 64bit
PostgreSQL 9.5.14
groonga 8.0.6
pgroonga 2.1.4

※クラッシュが発生しております。。クラッシュ時刻は`2018-09-12 18:11:12`です。
どうぞよろしくお願いいたします。

**Comment by kou** [comment]
直してみたつもりなのでもう一度masterを試してもらえますか？

**Comment by dodaisuke** [comment]
ありがとうございます！
ビルドして、検証しております。
こちらの問題になって、検証し始めてすぐクラッシュしていたのですが今は発生しておりません。。！
もう数日、引き続き様子を見てみようと思います。
ご対応いただきありがとうございます。

**Comment by dodaisuke** [comment]
クラッシュは発生していませんが、memory corruptionが発生してしましました。
再現性等は継続して検証中ですが（一時的にログ出力はデフォルトに戻しています）、まずは共有させていただこうと思いご連絡させていただきました。

[logs.zip](https://github.com/pgroonga/pgroonga/files/2378428/logs.zip)

postgresql-Thu.logの方で`17:09:40`頃？corruptionが発生し、その後`17:10:20`あたりからリカバリモードに移行しています。
よろしくお願いいたします。

**Comment by kou** [comment]
うーん、↓のときにまだ`free`してはいけない領域を`free`しちゃっているみたいです。

```sql
INSERT INTO product_flavor(product_id, flavor_id, editor_id, timestamp)
                    select p.id, row_data.id, 0, now()
                      from product_view_stg p
                     where p.enable = true
                       and p.status = 1
                       and p.genre_id in (select unnest((select get_child_genre_ids(209))))
                       and p.id in (select distinct i.product_id
                                      from item i
                                      join size_card_detail scd on (i.size_card_id = scd.size_card_id)
                                      left join reserve_item ri on (i.id = ri.item_id)
                                     where (i.amount > 0 or ri.status = 'SELLING')
                                       and scd.name = '着丈'
                                       and scd.size_from between 105 and 115)
```

bda78a33cd42a9404ead4b11da6d2a1f42df5d7e で直ると思うんですが、念のため、それの1個前の 67834b41d80073bbe3f1b2ff0a67377fcdbe456d で動かして再現させてログを見せてもらえますか？

`git checkout 67834b41d80073bbe3f1b2ff0a67377fcdbe456d`で特定のリビジョンのソースツリーにできます。終わったら`git checkout master`で最新に戻せます。

**Comment by dodaisuke** [comment]
ご対応ありがとうございます！
[67834b4](
https://github.com/pgroonga/pgroonga/commit/67834b41d80073bbe3f1b2ff0a67377fcdbe456d) にて試しました。
クラッシュ、memory corruption、リカバリモードへの移行は発生しなかったのですが、`failed to open cursor: not supported` というエラーが発生しておりました。
何度か発生していますが、[上記](https://github.com/pgroonga/pgroonga/issues/82#issuecomment-421017806) のクエリをマニュアルで実行した時刻は `11:28:48` です。

[logs.zip](https://github.com/pgroonga/pgroonga/files/2381701/logs.zip)

なお、[bda78a3](https://github.com/pgroonga/pgroonga/commit/bda78a33cd42a9404ead4b11da6d2a1f42df5d7e) で試してみましたが、`failed to open cursor: not supported`のエラーやcorruption等の状況は今のところ発生しておりません。

引き続き最新のmasterで検証していきます。
よろしくお願いいたします。

**Comment by dodaisuke** [comment]
4日ほどアプリケーションを連続稼働させましたが、クラッシュやエラー等、発生しておりませんでした！
ご対応いただきありがとうございました。本件クローズさせていただきますね。

また、今回入れていただいた修正で、本サービスでの稼働も見えました！
組み込ませていただいたら、是非pgroongaの利用をアナウンスさせていただきたいと思います。
どうぞよろしくお願いいたします。

**Comment by kou** [comment]
よかったです。

https://pgroonga.github.io/ja/users/ というページもあるので、もしよろしければこちらにもお願いします！

**Comment by dodaisuke** [comment]
了解です！
ちなみに、今回入れていただいた修正が入ったyumパッケージは近日中にリリースされますでしょうか？
本番稼働しているサービスに組み込む際、どのようにインストールしようかなと考えております。

**Comment by dodaisuke** [comment]
おお、早速リリースありがとうございます！！

**Comment by kou** [comment]
これを使ってください！
