### ISSUE TITLE
PGroonga-2.1.0 later, Replication is not working. (query fails on replica node.)

### ISSUE THREAD

**Issue by tongsama** [pgroonga/pgroonga#84]
# Overview
After streaming replication configuration,
Issuing Update/Delete/Insert queries and modifying pgroonga index on primary-node cause pgroonga index corruption or state of unavailable on replica-node.

PostgreSQL says,

```text
ERROR:  cannot acquire lock mode ShareUpdateExclusiveLock on database objects while recovery is in progress
HINT:  Only RowExclusiveLock or less can be acquired on database objects during recovery.
```

# Environment
PGroonga-2.1.0 or later

# Reproduction
Here's documentation of replication configuration steps.
https://pgroonga.github.io/reference/replication.html

> 1.[normal] Install PostgreSQL on master and slaves
> 2.[special] Install PGroonga on master and slaves
> 3.[normal] Initialize PostgreSQL database on master
> 4.[normal] Add some streaming replication configurations to postgresql.conf and pg_hba.conf on master
> 5.[special] Add some PGroonga related configurations to postgresql.conf on master
> 6.[normal] Insert data on master
> 7.[special] Create a PGroonga index on master
> 8.[special] Flush PGroonga related data on master
> 9.[normal] Run pg_basebackup on slaves
> 10.[normal] Add some streaming replication configurations to postgresql.conf on slaves
> 11.[normal] Start PostgreSQL on slaves

While doing below test after complete above steps, at steps "11.[normal] Start PostgreSQL on slaves" last part test,

On Primary-node
```text
$ psql blog
psql (10.5)
Type "help" for help.

blog=>
INSERT INTO entries VALUES ('PostgreSQL 9.6 and replication', 'PostgreSQL supports generic WAL since 9.6. It is required for replication for PGroonga.');
INSERT 0 1
blog=>
blog=> SELECT * FROM entries;
             title              |                                                    body
--------------------------------+------------------------------------------------------------------------------------------------------------
 PGroonga                       | PGroonga is a PostgreSQL extension for fast full text search that supports all languages. It will help us.
 Groonga                        | Groonga is a full text search engine used by PGroonga. We did not know about it.
 PGroonga and replication       | PGroonga 1.1.6 supports WAL based streaming replication. We should try it!
 PostgreSQL 9.6 and replication | PostgreSQL supports generic WAL since 9.6. It is required for replication for PGroonga.
(4 rows)

blog=>
```

On Replica-node

```text
blog=> SET enable_seqscan TO off;
SET
blog=> SELECT title FROM entries WHERE title %% 'replication';
ERROR:  cannot acquire lock mode ShareUpdateExclusiveLock on database objects while recovery is in progress
HINT:  Only RowExclusiveLock or less can be acquired on database objects during recovery.
blog=>
blog=> SELECT * FROM entries;
ERROR:  cannot acquire lock mode ShareUpdateExclusiveLock on database objects while recovery is in progress
HINT:  Only RowExclusiveLock or less can be acquired on database objects during recovery.
blog=>
blog=> explain SELECT * FROM entries;
ERROR:  cannot acquire lock mode ShareUpdateExclusiveLock on database objects while recovery is in progress
HINT:  Only RowExclusiveLock or less can be acquired on database objects during recovery.
blog=>
```

**Comment by kou** [comment]
Thanks for your report.
I've fixed it.

**Comment by tongsama** [comment]
Now working Thanks a lot !
