### ISSUE TITLE
"ERROR: tuple offset out of range" after autovacuum process

### ISSUE THREAD

**Issue by dodaisuke** [pgroonga/pgroonga#85]
autovacuumが実行された際にインデックスを利用したクエリが実行されると以下のエラーが発生するようになりました。
※なお、1度発生すると継続的にエラーが発生するようになります。
```
ERROR: tuple offset out of range: 2228
```
reindexするとこちらの現象は発生しなくなりますが、同じようにautovacuumのタイミングで再度発生するようになります。
エラーが発生したSQLとexplainの結果は以下の通りです。
```
SELECT id
from product_view_stg  where enable=true
                             and ARRAY [name, seller_comment, material, country, size_on_tag_web_names, genre_names, belong_brand_name_jp, belong_brand_name_en] &@~ pgroonga_query_expand('synonyms', 'term', 'synonyms','ロング')
                             and status = 1
                             and genre_id in ('133')
                             and secret_sale_id <= 0  order by id desc limit 120 offset 0;
```
genre_idの条件を外す、ARRAYに指定するカラムを減らす、といったことをするとエラーが発生しないこともあります。
```
Limit  (cost=5.33..5.33 rows=2 width=4)
  ->  Sort  (cost=5.33..5.33 rows=2 width=4)
        Sort Key: product_view_stg.id DESC
        ->  Append  (cost=0.00..5.32 rows=2 width=4)
              ->  Seq Scan on product_view_stg  (cost=0.00..0.00 rows=1 width=4)
                    Filter: (enable AND (secret_sale_id <= 0) AND (status = 1) AND (genre_id = '133'::smallint) AND (ARRAY[name, seller_comment, material, country, size_on_tag_web_names, genre_names, belong_brand_name_jp, belong_brand_name_en] &@~ pgroonga_query_expand('synonyms'::cstring, 'term'::text, 'synonyms'::text, 'ロング'::text)))
              ->  Bitmap Heap Scan on product_view_stg_part_00  (cost=2.80..5.32 rows=1 width=4)
                    Recheck Cond: ((ARRAY[name, seller_comment, material, country, size_on_tag_web_names, genre_names, belong_brand_name_jp, belong_brand_name_en] &@~ pgroonga_query_expand('synonyms'::cstring, 'term'::text, 'synonyms'::text, 'ロング'::text)) AND (genre_id = '133'::smallint))
                    Filter: (enable AND (secret_sale_id <= 0) AND (status = 1))
                    ->  BitmapAnd  (cost=2.80..2.80 rows=1 width=0)
                          ->  Bitmap Index Scan on product_view_stg_full_text_search_part_00_idx01  (cost=0.00..0.00 rows=72 width=0)
                                Index Cond: (ARRAY[name, seller_comment, material, country, size_on_tag_web_names, genre_names, belong_brand_name_jp, belong_brand_name_en] &@~ pgroonga_query_expand('synonyms'::cstring, 'term'::text, 'synonyms'::text, 'ロング'::text))
                          ->  Bitmap Index Scan on product_view_stg_part_00_idx07  (cost=0.00..2.54 rows=17 width=0)
                                Index Cond: (genre_id = '133'::smallint)
```
よろしくお願いいたします。

**Comment by dodaisuke** [comment]
はい、order by, limit, offset全て外しても、個別に有効にしてもどのパターンでもエラーが発生しました。

**Comment by dodaisuke** [comment]
なお、先ほどのクエリは時間が経つと正常に実行されるようになりました。
しかし、クエリに使うキーワードを変更したら、同じ現象が発生しました。
具体的には発生したエラーが`ロング`は解消し、`Tシャツ`で発生しました。
上記`order by id desc limit 120 offset 0`の確認は後者のTシャツで行っております。

**Comment by kou** [comment]
では、すべて外してさらに`WHERE`の`&@~`条件も1つずつ外して再現するか確認してもらえますか？

**Comment by kou** [comment]
時間が経っている間に該当テーブルは更新しましたか？

**Comment by kou** [comment]
あぁ、すみません、`&@~`「以外」の条件でした。。。
が、`&@~`以外のどの条件を外してもエラーじゃなくなるんですね。

`product_view_stg_part_00_idx07`のインデックス定義を貼ってもらえますか？

あと、`order ...`とかを抜いて再現する状態の`SELECT`の`EXPLAIN`も貼ってもらえますか？

**Comment by kou** [comment]
更新処理が走ってDBの内容が変わったので同じ`SELECT`でも発生しなくなったんだと思います。（PostgreSQL的には`UPDATE`も`DELETE`/`INSERT`もだいたい同じなので今回も違いはなさそうです。）

**Comment by dodaisuke** [comment]
> `&@~`以外のどの条件を外してもエラーじゃなくなる

上記クエリで言うと、genre_idの条件を外すとエラーが発生しなくなります。

> `product_view_stg_part_00_idx07 `のインデックス定義

以下の通りです。
```
CREATE INDEX product_view_stg_part_00_idx07
    ON product_view_stg_part_00 USING btree
    (genre_id)
    TABLESPACE pg_default;
```

`EXPLAIN`の結果は以下となります。
```
Append  (cost=0.00..5.31 rows=2 width=4)
  ->  Seq Scan on product_view_stg  (cost=0.00..0.00 rows=1 width=4)
        Filter: (enable AND (status = 1) AND (genre_id = '133'::smallint) AND (ARRAY[name, seller_comment, material, country, size_on_tag_web_names, genre_names, belong_brand_name_jp, belong_brand_name_en] &@~ pgroonga_query_expand('synonyms'::cstring, 'term'::text, 'synonyms'::text, 'ロング'::text)))
  ->  Bitmap Heap Scan on product_view_stg_part_00  (cost=2.80..5.31 rows=1 width=4)
        Recheck Cond: ((ARRAY[name, seller_comment, material, country, size_on_tag_web_names, genre_names, belong_brand_name_jp, belong_brand_name_en] &@~ pgroonga_query_expand('synonyms'::cstring, 'term'::text, 'synonyms'::text, 'ロング'::text)) AND (genre_id = '133'::smallint))
        Filter: (enable AND (status = 1))
        ->  BitmapAnd  (cost=2.80..2.80 rows=1 width=0)
              ->  Bitmap Index Scan on product_view_stg_full_text_search_part_00_idx01  (cost=0.00..0.00 rows=72 width=0)
                    Index Cond: (ARRAY[name, seller_comment, material, country, size_on_tag_web_names, genre_names, belong_brand_name_jp, belong_brand_name_en] &@~ pgroonga_query_expand('synonyms'::cstring, 'term'::text, 'synonyms'::text, 'ロング'::text))
              ->  Bitmap Index Scan on product_view_stg_part_00_idx07  (cost=0.00..2.54 rows=17 width=0)
                    Index Cond: (genre_id = '133'::smallint)
```

> PostgreSQL的には`UPDATE`も`DELETE`/`INSERT`もだいたい同じなので今回も違いはなさそうです。

なるほどです、、了解しました。

**Comment by dodaisuke** [comment]
`EXPLAIN`の評価に利用したSQLは以下です。
```
SELECT id
from product_view_stg  where
                             ARRAY [name, seller_comment, material, country, size_on_tag_web_names, genre_names, belong_brand_name_jp, belong_brand_name_en]
                                 &@~ pgroonga_query_expand('synonyms', 'term', 'synonyms', 'ロング')
                             and enable=true
                             and status = 1
                             and genre_id in ('133')
```
status条件で利用するパーティションテーブルを制限しているため、条件に加えたままとしています。
（この状態でenable=trueを外すとエラーが発生するため加えたままにしています。）

**Comment by kou** [comment]
>  （この状態でenable=trueを外すとエラーが発生するため加えたままにしています。）

あれ、`EXPLAIN`だけでもエラーになりますか？
`EXPLAIN`なしだとエラーになるけど`EXPLAIN`をつけるとエラーにならないことを期待していました。

**Comment by dodaisuke** [comment]
あ、そうですよね！失礼しました。`enable=true`を除いた`EXPLAIN`は以下の通りです。
```
Append  (cost=0.00..5.31 rows=2 width=4)
  ->  Seq Scan on product_view_stg  (cost=0.00..0.00 rows=1 width=4)
        Filter: ((status = 1) AND (genre_id = '133'::smallint) AND (ARRAY[name, seller_comment, material, country, size_on_tag_web_names, genre_names, belong_brand_name_jp, belong_brand_name_en] &@~ pgroonga_query_expand('synonyms'::cstring, 'term'::text, 'synonyms'::text, 'ロング'::text)))
  ->  Bitmap Heap Scan on product_view_stg_part_00  (cost=2.80..5.31 rows=1 width=4)
        Recheck Cond: ((ARRAY[name, seller_comment, material, country, size_on_tag_web_names, genre_names, belong_brand_name_jp, belong_brand_name_en] &@~ pgroonga_query_expand('synonyms'::cstring, 'term'::text, 'synonyms'::text, 'ロング'::text)) AND (genre_id = '133'::smallint))
        Filter: (status = 1)
        ->  BitmapAnd  (cost=2.80..2.80 rows=1 width=0)
              ->  Bitmap Index Scan on product_view_stg_full_text_search_part_00_idx01  (cost=0.00..0.00 rows=72 width=0)
                    Index Cond: (ARRAY[name, seller_comment, material, country, size_on_tag_web_names, genre_names, belong_brand_name_jp, belong_brand_name_en] &@~ pgroonga_query_expand('synonyms'::cstring, 'term'::text, 'synonyms'::text, 'ロング'::text))
              ->  Bitmap Index Scan on product_view_stg_part_00_idx07  (cost=0.00..2.54 rows=17 width=0)
                    Index Cond: (genre_id = '133'::smallint)
```

**Comment by dodaisuke** [comment]
こちらこそありがとうございます！
再現方法が分かっていますので、追加情報等、必要でしたら言ってください。
よろしくお願いいたします。

**Comment by kou** [comment]
ありがとうございます。

masterにデバッグログを追加したので、masterをビルドして`set pgroonga.log_level = debug;`した状態で`REINDEX`してからもう一度再現させてもらえますか？ものすごくログがでると思うんですが。。。

**Comment by dodaisuke** [comment]
報告遅くなり申し訳ありません。

[logs.zip](https://github.com/pgroonga/pgroonga/files/2560748/logs.zip)

ログを添付いたします。
`2018-11-08 16:33:36.991`に`autovacuum`が実行され、`2018-11-08 16:34:17.985`にエラーが発生しております。

`postgreqsl-Thu.log`では何度かリカバリモードに入っておりますが、操作？方法が悪かったのかもしれず、色々とやり直したりして実行しています。
最終的には一度`pgroonga(FUNCTION)`を再インストールし、インデックス作成、その後いつも再現する操作を行わなくても`autovacuum`が実行されたため、SQLを実行してエラーが発生することを確認いたしました。

`pgroonga.log`ファイルは該当時間帯のみ抜き出しておりますので、もし前後のログが必要であれば仰ってください。
よろしくお願いいたします。

**Comment by kou** [comment]
ありがとうございます！
`REINDEX`後からの状態を確認したいので「2018-11-08 15:34:04」からの`pgroonga.log`ももらえますか！？

```text
<2018-11-08 15:38:46.172 JST>[d:waja r:[local] p:5117 c:5be3d8dc.13fd l:2 s:2018-11-08 15:34:04 JST v:2/0 x:0]LOG:  duration: 238836.068 ms  statement: reindex index product_view_stg_full_text_search_part_01_idx01;
```

**Comment by kou** [comment]
クラッシュするのはPGroongaのバグなので直しておきます。。。

**Comment by kou** [comment]
クラッシュするのはmasterでは直したつもりです。

**Comment by dodaisuke** [comment]
ありがとうございます！
`16:34:17.985`に発生したエラーに対して作成したインデックスは`16:21:26.497`, `16:22:26.021`, `16:27:37.664`の3つの`create index product_view_stg_full_text_search_part_0X_idx01`になりますので、この時間帯のログを添付しますね。
準備次第添付します。

**Comment by dodaisuke** [comment]
あ、念のため？`REINDEX`した際のログも用意します！

**Comment by dodaisuke** [comment]
[logs.zip](https://github.com/pgroonga/pgroonga/files/2561086/logs.zip)

取り急ぎ、`16:21:26`以降のログを添付いたします。
`15:34:04`は実験開始前の`REINDEX`で、こちらはまだデバッグレベルにする前でした。
見づらくて申し訳ありません。。

`15:45:15.136`に`REINDEX`していますが、直後にエラーが出ているように、操作手順がまずかった可能性があり、その後`pgroonga`再インストール等行いました。

`16:20:34`に`PostgreSQL`を起動していますので、ここからがちゃんとした？一連の実験になります。
すみませんがよろしくお願いいたします。

**Comment by kou** [comment]
ありがとうございます。助かりました。

可能性は削除したレコードがヒットしてしまっている（Groongaのインデックスが壊れていそうなので直すのが大変そう）か、削除していないけどレコードが壊れてしまっている（なんで壊れるんだ。。。）のどちらかかなぁと思いました。

どちらかを切り分けるためのログを追加したのでmasterでもう一度再現させてログを見せてもらえませんか？

**Comment by dodaisuke** [comment]
[logs1.zip](https://github.com/pgroonga/pgroonga/files/2564836/logs1.zip)
[logs2.zip](https://github.com/pgroonga/pgroonga/files/2564837/logs2.zip)
[logs3.zip](https://github.com/pgroonga/pgroonga/files/2564838/logs3.zip)
[logs4.zip](https://github.com/pgroonga/pgroonga/files/2564839/logs4.zip)
[logs5.zip](https://github.com/pgroonga/pgroonga/files/2564840/logs5.zip)

再度ログを取得いたしました。
`logs2.zip`〜`logs5.zip`まで数字（実際のファイルはアルファベットです）が時系列になっています。

`15:07:00.105`, `15:08:46.422`, `15:12:56.270`が`pgroonga`のインデックス作成終了時刻です。
`autovacuum`は`15:20:11.019`に実行されています。
その前の`15:20:01.806`にエラーが発生していますが、こちらは手動操作を特に実行していないですし、なぜエラーが出たのかはっきりとしません。
※もしかすると`autovacuum`中で、既に現象が発生していたのかもしれません。

`15:20:25.677`のエラーがマニュアルで発生させた（意図した）エラーになります。
ログは十分でしょうか。
お手数をおかけしますが、よろしくお願いいたします。

**Comment by kou** [comment]
ありがとうございます。
削除したレコードがヒットしてしまっていたことが確定しました。
つまり、Groongaのインデックスに削除したレコードが残ってしまっています。

Groongaのmasterで直したつもりなので、Groongaをmasterにして再度再現を試みてもらえますか？

**Comment by kou** [comment]
ちょっと罠が多そうですね。。。
テスト用のパッケージを作りますね。CentOS 7でしたっけ？

アップグレードはパッケージ更新語にPostgreSQLに接続し直して`CREATE INDEX`または`REINDEX`だけで大丈夫です。

**Comment by dodaisuke** [comment]
おお、それはありがたいです！CentOS 6になります・・！
アップグレード方法も、ありがとうございます、了解しました。

**Comment by kou** [comment]
https://packages.groonga.org/tmp/2018-11-12/ にアップロードしたのでダウンロードして`rpm -U`でアップグレードしてみてください。

**Comment by dodaisuke** [comment]
ありがとうございます！助かります・・！

**Comment by dodaisuke** [comment]
いただいたパッケージでアップグレード後、再現手順を踏みましたがエラーは発生しませんでした！
大変感謝です、ありがとうございます・・！！
また継続運転して、問題等発生しないか確認したいと思います。
よろしくお願いいたします。

**Comment by kou** [comment]
よかったです！

**Comment by dodaisuke** [comment]
1週間ほど連続稼働させておりますが、エラーやリソース上の問題など、発生しませんでした。
検証を進めているアプリケーションも、近々本番稼働にもっていきたいと思います。
多々ご対応いただき、ありがとうございました！

なお、一連の修正分はリリースされる予定はありますでしょうか？
よろしくお願いいたします。

**Comment by dodaisuke** [comment]
おお、共有いただきありがとうございます！
では開発中のもののリリースはその後にスケジュールしたいと思います。
