### ISSUE TITLE
Jsonb - full text search on certan fields only

### ISSUE THREAD

**Issue by PlkMarudny** [pgroonga/pgroonga#86]
Is it possible to perform full text search on Jsonb excluding certain fields?

**Comment by komainu8** [comment]
Yes. We can do it as below example.

Here are sample schema and data for examples:

```sql
CREATE TABLE logs (
  record jsonb
);

CREATE INDEX pgroonga_logs_index ON logs USING pgroonga (record);

INSERT INTO logs
     VALUES ('{
                "message": "Server is started.",
                "host":    "www.example.com",
                "tags": [
                  "web",
                  "example.com"
                ]
              }');
INSERT INTO logs
     VALUES ('{
                "message": "GET /",
                "host":    "www.example.com",
                "code":    200,
                "tags": [
                  "web",
                  "example.com"
                ]
              }');
INSERT INTO logs
     VALUES ('{
                "message": "Send to <info@example.com>.",
                "host":    "mail.example.net",
                "tags": [
                  "mail",
                  "example.net"
                ]
              }');
```

For example, If we want full-text search on jsonb to exclude "message" field, use "AND NOT" as below example.

```sql
SELECT jsonb_pretty(record)
FROM logs
WHERE record &` 'string @ "example.com"'
  AND NOT record &` 'paths @ "message" && string @ "example.com"';
```

Here is the result of above the query.
```sql
            jsonb_pretty             
-------------------------------------
 {                                  +
     "host": "www.example.com",     +
     "tags": [                      +
         "web",                     +
         "example.com"              +
     ],                             +
     "message": "Server is started."+
 }
 {                                  +
     "code": 200,                   +
     "host": "www.example.com",     +
     "tags": [                      +
         "web",                     +
         "example.com"              +
     ],                             +
     "message": "GET /"             +
 }
```

Perhaps, if you tell me schema and data specifically, I may be able to tell more specific ideas.

**Comment by PlkMarudny** [comment]
Hi,
Thas works - thank you - however it seems to use a sequential scan, while the &@ operator uses the index.

**Comment by komainu8** [comment]
Because of a sequential scan is low-cost more than an index scan in above example, it uses a sequential scan.
I think that if we use more complex data, PostgreSQL select index scan.

Here is the result of each search cost.

Sequential scan:
```sql
Seq Scan on public.logs  (cost=0.00..4.03 rows=1 width=32)
```

Index scan:
```sql
Index Scan using pgroonga_logs_index on public.logs  (cost=0.00..4.51 rows=1 width=32)
```

**Comment by komainu8** [comment]
I also introduce other a query.
Because of this query very faster than a query that was in the previous.

```sql
SELECT jsonb_pretty(record)
FROM logs
WHERE record &` 'string @ "example.com" &! paths @ "message"';
            jsonb_pretty             
-------------------------------------
 {                                  +
     "host": "www.example.com",     +
     "tags": [                      +
         "web",                     +
         "example.com"              +
     ],                             +
     "message": "Server is started."+
 }
 {                                  +
     "code": 200,                   +
     "host": "www.example.com",     +
     "tags": [                      +
         "web",                     +
         "example.com"              +
     ],                             +
     "message": "GET /"             +
 }
```

This query excludes search result of `message` field from a result of `string @ "example.com"` with `&!` operator.

Please refer to the below URL about `&!` operator.
http://groonga.org/docs/reference/grn_expr/script_syntax.html#logical-and-not-operator

Indexes are often used in this query.
However, this query doesn't also use indexes above example:(

**Comment by ZenLiuCN** [comment]
> I also introduce other a query.
> Because of this query very faster than a query that was in the previous.
> 
> ```sql
> SELECT jsonb_pretty(record)
> FROM logs
> WHERE record &` 'string @ "example.com" &! paths @ "message"';
>             jsonb_pretty             
> -------------------------------------
>  {                                  +
>      "host": "www.example.com",     +
>      "tags": [                      +
>          "web",                     +
>          "example.com"              +
>      ],                             +
>      "message": "Server is started."+
>  }
>  {                                  +
>      "code": 200,                   +
>      "host": "www.example.com",     +
>      "tags": [                      +
>          "web",                     +
>          "example.com"              +
>      ],                             +
>      "message": "GET /"             +
>  }
> ```
> 
> This query excludes search result of `message` field from a result of `string @ "example.com"` with `&!` operator.
> 
> Please refer to the below URL about `&!` operator.
> http://groonga.org/docs/reference/grn_expr/script_syntax.html#logical-and-not-operator
> 
> Indexes are often used in this query.
> However, this query doesn't also use indexes above example:(

``` @` ``` now is only exists in `jsob_ops_v2` and it's limited by 4k length~ that is lesser useful

**Comment by kou** [comment]
Does your query use index after you run `ALTER FUNCTION pgroonga_script_jsonb(jsonb, text) COST 1000;`?

**Comment by PlkMarudny** [comment]
No, it still performs the sequential scan.

So,

`select data from media where data &@ 'ecd3';`

uses the index, while:

`select data from media where data &` 'string @ "ecd3" &! paths @ "Filename"';`

performs only the sequential scan after the command:

`ALTER FUNCTION pgroonga_script_jsonb(jsonb, text) COST 1000;?`

Currently, I have only over 8 thousand documents in the database.

**Comment by kou** [comment]
Can you show the output of

```sql
EXPLAIN ANALYZE VERBOSE select data from media where data &` 'string @ "ecd3" &! paths @ "Filename"';
```

and

```sql
SET enable_seqscan = off;
EXPLAIN ANALYZE VERBOSE select data from media where data &` 'string @ "ecd3" &! paths @ "Filename"';
```

?

**Comment by kou** [comment]
Thanks. Can you also show the output of the following:

```sql
SET enable_seqscan = off;
EXPLAIN ANALYZE VERBOSE select data from media where data &` 'string @ "ecd3" &! paths @ "Filename"';
```

**Comment by kou** [comment]
Ah, you can't use "&`" with `pgroonga_jsonb_full_text_search_ops_v2`. You need to remove it from `CREATE INDEX`.

**Comment by PlkMarudny** [comment]
But I want to have te full text search possibility on the `jsonb` column. Just wanted to know if there is way of excluding certain fields from search. Of course I can always split my json document into two separate columns and index only one column with only desired fields, but this is less than ideal solution.

**Comment by PlkMarudny** [comment]
Indeed, this works as expected, thank you very much
