### ISSUE TITLE
"ERROR: tuple offset out of range" occurred

### ISSUE THREAD

**Issue by dodaisuke** [pgroonga/pgroonga#89]
本日時点でPGroongaのmasterの最新版、Groonga8.0.9を利用し、更新処理の多い状態でインデックスを利用した検索を行うとまれに"ERROR: tuple offset out of range"が発生します。

ログを添付しますのでお手数ですがご確認お願いします。
[logs.zip](https://github.com/pgroonga/pgroonga/files/2656128/logs.zip)

何度か発生していますが、デバッグログを取得したエラーは`15:26:56.153`のエラー（postgresql-Fri.log）になります。
プロセス番号は`7244`です。

よろしくお願いいたします。

**Comment by kou** [comment]
確認しました。

PostgreSQLは`SELECT`時に不要なレコードを削除する機能がある（`VACUUM`まで待たずにゴミを減らせる）のですが、そのときに消したレコードが何度もヒットするのが原因でした。

が、なんで何度もヒットするのかはわかりませんでした。削除してもインデックスに残ってしまっているような気もしますが、該当レコードが追加した頃のログがないのでわかりませんでした。

masterにログを追加したのでPGroongaを更新してもう一度ログを取ってもらえますか？ログはデータ投入時の分から全部もらえると助かります。

**Comment by kou** [comment]
ありがとうございます。
原因がわかりました。

`SELECT`と`AUTO VACUUM`が同時に走ると、`SELECT`でヒットしたレコードが`AUTO VACUUM`中に削除されて変な値が取れてしまうのが原因でした。（複数の`SELECT`が同時に走ったときも内部的にレコードが削除されることがあるので同様の状態になりえます。）

近いうちに直しておきます。

**Comment by kou** [comment]
直したつもりなのでmasterを試してみてもらえませんか？

**Comment by dodaisuke** [comment]
おお、なんと、ありがとうございます・・！！
さっそく試してみますね。

**Comment by dodaisuke** [comment]
色々と試してみましたが、エラーは発生しないようです・・！
ご対応いただきありがとうございました！

**Comment by kou** [comment]
よかったです。
近いうちに新しいバージョンをリリースする予定です。
