### ISSUE TITLE
zero-cost estimates cause sub-optimal query planning

### ISSUE THREAD

**Issue by rtpg** [pgroonga/pgroonga#94]
Over at:
https://github.com/pgroonga/pgroonga/blob/6c86941ec0f819589ed48d8e738d4c82317d1945/src/pgroonga.c#L6982

```C
	*indexStartupCost = 0.0; /* TODO */
	*indexTotalCost = 0.0; /* TODO */
	*indexCorrelation = 0.0;
#ifdef PGRN_AM_COST_ESTIMATE_HAVE_INDEX_PAGES
	*indexPages = 0.0; /* TODO */
#endif
```

pgroonga is reporting that using its index is always free. In practice this isn't true, but it means that the planner ends up taking this index instead of faster indexes 

we've seen this notably when trying to iterate over a lot of rows:

 - index on (tenant_id)
 - pgroonga index on (tenant_id, some_text_blob)

when querying only by tenant_id, the first index will likely be faster in every way, but pgroonga reports zero cost, so the planner ends up choosing it instead.

Digging around, I think that I've seen that pgroonga 1.x would do "real" cost estimation, but I'm having a hard time finding the relevant code. 

Personally, I would not have an issue trying to put together a patch to improve on this issue, but I don't know what would make sense as cost values for this index.

**Comment by komainu8** [comment]
Thank you for your report!

We'll confirm this issue.
We appreciate your patience as it might take some time.

**Comment by komainu8** [comment]
It would be helpful if you could offer problematic a schema, a query, and a result of `EXPLAIN ANALYZE VERBOSE` when the query execution.

Because we don't figure out if whether PGroonga needs improvement or the query needs improvement with the current information.

**Comment by kou** [comment]
No feedback.
