### ISSUE TITLE
[BUG] Failed to set sources: system call error, failed to open path

### ISSUE THREAD

**Issue by javiertury** [pgroonga/pgroonga#97]
Hi, this bug happens randomly but occurs quite often. I've check SELinux and there isn't any denial, so it must be a pgroonga bug. Any idea about what could be failing?

```
Error: pgroonga: failed to set sources: <DDDDDDDDDD.index>: <[DDDDDDDDDD]>: system call error: No such file or directory: failed to open path: <base/DDDDDDD/pgrn.0001F91>
severity: 'ERROR',
code: '58030',
file: 'pgrn-groonga.c',
line: '119',
routine: 'PGrnCheck',
sql: 'SELECT * FROM table WHERE ARRAY["table"."title", "table"."description"] &@~ \'DescripcionC\''
```

**Comment by kenhys** [comment]
Thanks for reporting!

In point view of error message, it indicates that this error message is shown by: 
https://github.com/pgroonga/pgroonga/blob/master/src/pgrn-groonga.c#L419

So there are some question to clarify this situation.

* Does `/var/lib/pgsql/data/base/DDDDDDD/pgrn.0001F91` exist?
  * If it exists, access was denied by something (SELinux?)
  * If it doesn't  exists, unexpectedly database file is removed or database metadata may be corrupted.
     * As there is no further clue about it, could you attach /var/lib/pgsql/data/pgroonga.log?
* Are there minimum dataset and schema, query to reproduce it?
  * If it exists, (even though randomly) it may help to resolve issue.

**Comment by javiertury** [comment]
In the previous post, I replaced some digits with `DDDDDDD`. However, as soon as I found the error I looked for the file `/var/lib/pgsql/data/base/DDDDDDD/pgrn.0001F91`, but this file didn't exist. SELinux didn't deny the access.

The DB runs on a laptop with a NVME SSD, in the same ext4 partition as the OS, Fedora 29. SMART tool says the disk is in good health.

The following error logs also include some context, `Before ERR`.

[Log of error 1](https://pastebin.com/tzGpv70T)
[Log of error 2](https://pastebin.com/J2dWFHxH)

**Comment by kenhys** [comment]
Thanks,
Around `2019-04-06 15:50:56` and `2019-04-10 11:47:49`, PGroonga records removing many lexcon table(indexes) soon after initializing PGroonga. (autorecovery was running?) 
Did you observed PostgreSQL crashed or shutdown was failed at that time? If so, PGroonga database was corrupted.

**Comment by javiertury** [comment]
PostgreSQL didn't crash or shutdown during that time. It was running continuously for the whole day. The explanation for the removed indexes is that I execute batches of commands like this.

```
// First, clean the table
DELETE FROM "test";

// Second, insert dummy data for a given context
INSERT INTO test (lang, title, description) VALUES ('en', 'TitleA', 'DescriptionA');
INSERT INTO test (lang, title, description) VALUES ('es', 'TituloA', 'DescripcionA');
INSERT INTO test (lang, title, description) VALUES ('de', 'TitelA', 'BeschreibungA');
INSERT INTO test (lang, title, description) VALUES ('fr', 'TitreA', 'DescriptionA');

INSERT INTO test (lang, title, description) VALUES ('en', 'TitleB', 'DescriptionB');
INSERT INTO test (lang, title, description) VALUES ('es', 'TituloB', 'DescripcionB');
INSERT INTO test (lang, title, description) VALUES ('de', 'TitelB', 'BeschreibungB');
INSERT INTO test (lang, title, description) VALUES ('fr', 'TitreB', 'DescriptionB');

// Even more data ...

// Finally execute the query(s) I'm interested in
SELECT * FROM test WHERE ARRAY["table"."title", "table"."description"] &@~ \'DescripcionC\';

// End of batch commands, now I usually execute some commands manually
// Perhaps do some data modifications, notice the characters *í* and *ó*.
INSERT INTO test (lang, title, description) VALUES ('es', 'TítuloB', 'DescripciónB');

// Execute yet another query
SELECT * FROM test WHERE description &@ 'DescripcionB';
SELECT * FROM test WHERE description &@ 'DescripciónB';
```

I'm exploring how pgroonga operators works. I try to create examples myself and see which rows does a particular operator match and which don't in a variety of contexts.

Sometimes I also recreate the table schema, but that day I don't remember doing it.

```
DROP TABLE "test";

CREATE TABLE test (
    id UUID NOT NULL DEFAULT uuid_generate_v4(),
    lang VARCHAR(10) NOT NULL,
    title VARCHAR(90) NOT NULL,
    description VARCHAR(900) NOT NULL DEFAULT ''
);
CREATE INDEX test_content ON test USING pgroonga (title, description);
```

**Comment by kenhys** [comment]
> PostgreSQL didn't crash or shutdown during that time. It was running continuously for the whole day. The explanation for the removed indexes is that I execute batches of commands like this.

@javiertury Thanks for more additional information, I've misunderstood manual batch operation as unexpected ones.

But I have no luck with reproducing this issue yet, so there are some missing parts... ( `// Even more data ...` maybe caused issue)
You said "this bug happens randomly but occurs quite often.", could you try investigating this further more?
If we can confirm **reproducible minimum dataset** (even though it happens randomly) includes schema, executed query, pgroonga.log wih debug level from the beginning, it may helps.

https://pgroonga.github.io/reference/parameters/log-level.html

**Comment by kenhys** [comment]
@javiertury As one another idea, this issue still occurs on Groonga 9.0.1? Groonga 9.0.1 are available on Fedora 29(some index related bugs are fixed)

**Comment by javiertury** [comment]
@kenhys, I have just updated Groonga to version 9.0.1 from 8.1.1. I will enable debug logging and come back if the issue persists.
