### ISSUE TITLE
citext support

### ISSUE THREAD

**Issue by allenwu1973** [pgroonga/pgroonga#98]
Hi

Citext is a very popular built-in module that ships with postgres, it's a data type to store case insensitive text.

https://www.postgresql.org/docs/current/citext.html

Currentlly, pgroonga doesn't support citext.

```
ERROR:  pgroonga: unsupported type: 124217
```

It would be very helpful if this type is supported.

**Comment by kou** [comment]
How about casting to `text`  on creating an index?

```sql
CREATE INDEX pgroonga_content_index ON memos USING pgroonga ((content::text));
```

**Comment by allenwu1973** [comment]
It works, thanks!!

It would be nice if this is documented on the manual.
