### ISSUE TITLE
Scoring with join

### ISSUE THREAD

**Issue by anthonydafc** [pgroonga/pgroonga#99]
i try to use the scoring process that workds fine, but when i try to do a join i get an error saying that the tableoid doesn't exist. How can i reoslve it.
Here's a basic example with your example : 

`SELECT *, pgroonga_score(tableoid, ctid) AS score
FROM score_memos
inner join memos on score_memos.id = memos.id
--inner join files on score_memos.id = files.id
WHERE (content &~ '.*extension' )`

thanks for your help

**Comment by kou** [comment]
What is "your example"?
Could you also show schema (`CREATE TABLE` and `CREATE INDEX`) and sample data (`INSERT`) to run the `SELECT`?

**Comment by anthonydafc** [comment]
Hi, it is exactly the same tables as the ones in your example, with same indexes

**Comment by kou** [comment]
https://gitter.im/groonga/en?at=5cd9d0f50824230a772cc064 ?
There is only `CREATE INDEX`.

Again, could you provide full `CREATE TABLE`, `CREATE INDEX` and `INSERT` explicitly to reproduce this case?

**Comment by anthonydafc** [comment]
ok here it is :
First i created a table called files
`CREATE TABLE public.files
(
    id integer NOT NULL,
    content text COLLATE pg_catalog."default",
    id_file text COLLATE pg_catalog."default",
    CONSTRAINT files_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.files
    OWNER to postgres;`

secondly i create table scorer_memos with index score
`CREATE TABLE public.memos
(
    id integer,
    content text COLLATE pg_catalog."default"
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.memos
    OWNER to postgres;

-- Index: pgroonga_content_index

-- DROP INDEX public.pgroonga_content_index;

CREATE INDEX pgroonga_content_index
    ON public.memos USING pgroonga
    (content COLLATE pg_catalog."default")
    TABLESPACE pg_default;`

data score table
`data score_memos

INSERT INTO score_memos VALUES (1, 'PostgreSQL is a relational database management system.');
INSERT INTO score_memos VALUES (2, 'Groonga is a fast full text search engine that supports all languages.');
INSERT INTO score_memos VALUES (3, 'PGroonga is a PostgreSQL extension that uses Groonga as index.');
INSERT INTO score_memos VALUES (4, 'There is groonga command.');`

data files table
`INSERT INTO files VALUES (1, 'file a');
INSERT INTO files VALUES (2, 'file b');
INSERT INTO files VALUES (3, 'file c');
INSERT INTO files VALUES (4, 'file d');
INSERT INTO files VALUES (5, 'file e');`

i systematically have to disable seqscan
`SET enable_seqscan = off;`

and my select 
`SELECT *, pgroonga_score(tableoid, ctid) AS score
  FROM score_memos
  inner join files on score_memos.id = files.id
 WHERE content &~ '.*that'`

you will get error column tableoid doesn't exist

**Comment by kou** [comment]
Thanks.
It's helpful.

**Comment by kou** [comment]
You should use sub query for this case:

```sql
SELECT *
  FROM (SELECT *, pgroonga_score(tableoid, ctid) AS score
        FROM public.score_memos
	WHERE content &~ 'that') AS filtered_score_memos
  inner join files on filtered_score_memos.id = files.id;
```

**Comment by kou** [comment]
No response.
Closing.
